export const FunctionOptionData = [
  {
    type: "toUpperCase()",
    description: "Converts a string to uppercase.",
    toUpperCase: (str: string) => str.toUpperCase(),
    category: "String",
  },
  {
    type: "toLowerCase()",
    description: "Converts a string to lowercase.",
    toLowerCase: (str: string) => str.toLowerCase(),
    category: "String",
  },
  {
    type: "parseInt()",
    description: "Converts a string to an integer.",
    parseInt: (str: string) => parseInt(str),
    category: "String",
  },
  {
    type: "parseFloat()",
    description: "Converts a string to a floating-point number.",
    parseFloat: (str: string) => parseFloat(str),
    category: "String",
  },
  {
    type: "isNaN()",
    description: "Checks if a value is NaN (Not a Number).",
    isNaN: (value: number) => isNaN(value),
    category: "Number",
  },
  {
    type: "trim()",
    description: "Removes whitespace from both ends of a string.",
    trim: (str: string) => str.trim(),
    category: "String",
  },
  {
    type: "Math.abs()",
    description: "Returns the absolute value of a number.",
    abs: (num: number) => Math.abs(num),
    category: "Math",
  },
  {
    type: "Math.ceil()",
    description: "Rounds a number UP to the nearest integer.",
    ceil: (num: number) => Math.ceil(num),
    category: "Math",
  },
  {
    type: "Math.floor()",
    description: "Rounds a number DOWN to the nearest integer.",
    floor: (num: number) => Math.floor(num),
    category: "Math",
  },
  {
    type: "Math.round()",
    description: "Rounds a number to the nearest integer.",
    round: (num: number) => Math.round(num),
    category: "Math",
  },
  {
    type: "String()",
    description: "Converts any value to a string.",
    String: (value: string) => String(value),
    category: "String",
  },
  {
    type: "Number()",
    description: "Converts a value to a number.",
    Number: (value: string) => Number(value),
    category: "Number",
  },
  {
    type: "Boolean()",
    description: "Converts a value to a Boolean.",
    Boolean: (value: boolean) => Boolean(value),
    category: "Boolean",
  },
  {
    type: "isFinite()",
    description: "Determines whether a value is a finite, legal number.",
    isFinite: (value: number) => isFinite(value),
    categoey: "Number",
  },
  {
    type: "charAt()",
    description: "Returns the character at the specified index.",
    charAt: (str: string, index: number) => str.charAt(index),
    category: "String",
  },
  {
    type: "concat()",
    description: "Combines two or more strings.",
    concat: (str1: string, str2: string) => str1.concat(str2),
    category: "String",
  },
  {
    type: "includes()",
    description: "Checks if a string contains the specified substring.",
    includes: (str: string, substring: string) => str.includes(substring),
    category: "String",
  },
  {
    type: "indexOf()",
    description:
      "Returns the index of the first occurrence of a specified value.",
    indexOf: (str: string, value: string) => str.indexOf(value),
    category: "String",
  },
];
