/* eslint-disable @typescript-eslint/no-explicit-any */
import { rxdb } from "$lib/database/app.database";
export class HeadersViewModel {
  constructor() {}
  public updateHeaders = async (data: any, route: string) => {
    await rxdb.tab.setRequestProperty(data, route);
    return;
  };
  public updateAutoGeneratedHeaders = async (data: any, route: string) => {
    await rxdb.tab.setRequestProperty(data, route);
    return;
  };
}
