<script lang="ts">
  import { handleRequestChange } from "$lib/store/request-response-section";
  import type {
    KeyValuePair,
    NewTab,
  } from "$lib/utils/interfaces/request.interface";
  import KeyValue from "$lib/components/key-value/KeyValue.svelte";
  import { createDeepCopy } from "$lib/utils/helpers/conversion.helper";
  import angleUp from "$lib/assets/angle-up.svg";
  import angleDown from "$lib/assets/angle-down2.svg";
  import { onMount } from "svelte";
  import { findAuthHeader } from "$lib/utils/helpers/auth.helper";
  import { RequestProperty } from "$lib/utils/enums/request.enum";

  export let currentTabId: string;
  export let requestData: NewTab;

  let authValue: { key: string; value: string } = {
    key: "",
    value: "",
  };
  let showGeneratedHeader: boolean = false;

  $: {
    if (requestData) {
      authValue = findAuthHeader(requestData);
    }
  }

  $: {
    if (currentTabId) {
      authValue = findAuthHeader(requestData);
    }
  }

  onMount(() => {
    authValue = findAuthHeader(requestData);
  });

  const handleHeaderChange = (pairs: KeyValuePair[]): void => {
    handleRequestChange(pairs, RequestProperty.HEADERS, currentTabId);
  };

  const handleAutoGeneratedChange = (pairs: KeyValuePair[]): void => {
    handleRequestChange(
      pairs,
      RequestProperty.AUTO_GENERATED_HEADERS,
      currentTabId,
    );
  };
</script>

<section class="w-100">
  {#if showGeneratedHeader}
    <KeyValue
      mode={"READ"}
      readable={authValue}
      keyValue={createDeepCopy(requestData.request.autoGeneratedHeaders)}
      callback={handleAutoGeneratedChange}
    />
    <div>
      <small
        on:click={() => {
          showGeneratedHeader = false;
        }}
        class="text-labelColor generated-para"
        >Hide auto-generated headers<img src={angleUp} alt="angleUp" /></small
      >
    </div>
    <hr class="mt-1" />
  {/if}
  <KeyValue
    keyValue={createDeepCopy(requestData.request.headers)}
    callback={handleHeaderChange}
  />
  {#if !showGeneratedHeader}
    <div>
      <small
        on:click={() => {
          showGeneratedHeader = true;
        }}
        class="text-labelColor generated-para"
        >Show auto-generated headers <img
          src={angleDown}
          alt="angleDown"
        /></small
      >
    </div>
  {/if}
</section>

<style>
  .generated-para {
    font-size: 12px;
    cursor: pointer;
  }
</style>
