export enum ItemType {
  FOLDER = "FOLDER",
  REQUEST = "REQUEST",
  COLLECTION = "COLLECTION",
  WORKSPACE = "WORKSPACE",
  PERSONAL = "PERSONAL",
  WEB_SOCKET = "WEBSOCKET",
  ENVIRONMENT = "ENVIRONMENT",
  TESTFLOW = "TESTFLOW",
  SOCKET_IO = "SOCKETIO",
  GRAPHQL = "GRAPHQL",
  MOCK_REQUEST = "MOCK_REQUEST",
  AI_REQUEST = "AI_REQUEST",
}

export enum UntrackedItems {
  UNTRACKED = "UNTRACKED-",
}
