export enum ItemType {
  FOLDER = "FOLDER",
  REQUEST = "REQUEST",
  COLLECTION = "COLLECTION",
  WORKSPACE = "WORKSPACE",
  PERSONAL = "PERSONAL",
  ENVIRONMENT="ENVIRONMENT"
}

export enum UntrackedItems {
  UNTRACKED = "UNTRACKED-",
}
