export enum ItemType {
  FOLDER = "FOLDER",
  REQUEST = "REQUEST",
  COLLECTION = "COLLECTION",
  WORKSPACE = "WORKSPACE",
  PERSONAL = "PERSONAL",
  WEB_SOCKET = "WEBSOCKET",
  ENVIRONMENT = "ENVIRONMENT",
}

export enum UntrackedItems {
  UNTRACKED = "UNTRACKED-",
}
