<script lang="ts">
  // ---- Assets
  import { floppyDiskIcon as floppyDisk } from "@sparrow/library/assets";

  // ---- Components
  import {
    HttpUrlSection,
    RequestHeaders,
    RequestNavigator,
    ResponseNavigator,
    RequestAuth,
    ResponseDefaultScreen,
    ResponseErrorScreen,
    ResponseHeaders,
    RequestName,
    ResponseStatus,
    ResponseBody,
    RequestQuery,
    RequestSchema,
    GenerateQuery,
  } from "../components";
  import { Loader } from "@sparrow/library/ui";
  import { notifications } from "@sparrow/library/ui";
  import { Splitpanes, Pane } from "svelte-splitpanes";
  import { Button } from "@sparrow/library/ui";
  import type { Observable } from "rxjs";
  import { SaveAsCollectionItem } from "@sparrow/workspaces/features";
  import {
    RequestSectionEnum,
    ResponseSectionEnum,
    type KeyValue,
  } from "@sparrow/common/types/workspace";
  import { type graphqlExplorerData } from "../store";

  import { Modal } from "@sparrow/library/ui";
  import { ResponseStatusCode } from "@sparrow/common/enums";

  import {
    GraphqlRequestOperationTabEnum,
    GraphqlRequestSectionTabEnum,
  } from "@sparrow/common/types/workspace/graphql-request-tab";
  import { TabTypeEnum } from "@sparrow/common/types/workspace/tab";
  import { WarningIcon } from "@sparrow/library/icons";
  import RequestVariables from "../components/request-variables/RequestVariables.svelte";
  import { onMount } from "svelte";
  import { writable } from "svelte/store";
  import { loadingState } from "../../../../../@sparrow-common/src/store";

  export let tab;
  export let collections;
  export let requestAuthHeader: Observable<KeyValue>;
  export let onUpdateRequestUrl;
  export let onSendRequest;
  export let onCancelRequest;
  export let onUpdateRequestName;
  export let onUpdateRequestAuth;
  export let onUpdateHeaders;
  export let onUpdateAutoGeneratedHeaders;
  export let onUpdateRequestState;
  export let onUpdateResponseState;
  export let onSaveRequest;
  export let readWorkspace;
  export let onSaveAsRequest;
  export let onCreateFolder;
  export let onCreateCollection;
  export let onUpdateRequestQuery;
  export let onUpdateEnvironment;
  export let environmentVariables;
  export let storeData: graphqlExplorerData | undefined;
  export let onRenameCollection;
  export let onRenameFolder;
  export let isGraphqlEditable;
  export let onClearQuery;
  export let onFetchSchema;
  export let updateSchema;
  export let onUpdateVariables;
  export let updateOperationSearch;
  export let checkQueryErrorStatus;
  
  export let isWebApp;
  const loading = writable<boolean>(false);

  let isExposeSaveAsRequest = false;
  let isLoading = true;
  let isSchemaFetching = false;
  let isQueryInvalid = false;
  let errorStartIndex = 0;
  let errorEndIndex = 0;
  let queryErrorMessage = "";
  $: {
    if ($tab?.property?.graphql?.url?.length > 0) {
      isLoading = false;
    }
  }

  /**
   * Toggles the "Save As Request" flag.
   */
  const toggleSaveRequest = (flag: boolean): void => {
    isExposeSaveAsRequest = flag;
  };

  /**
   * Handles the process of fetching the GraphQL schema.
   * Sets the `isSchemaFetching` flag while fetching and resets it after completion.
   */
  const handleFetchSchema = async () => {
    isSchemaFetching = true;
    await onFetchSchema(environmentVariables?.filtered || []);
    isSchemaFetching = false;
  };

  /**
   * Checks and handles the query error status.
   * Updates error-related variables if the query is invalid.
   */
  const handleQueryErrorStatus = async () => {
    const errorStatus = await checkQueryErrorStatus();
    if (errorStatus?.isQueryInvalid) {
      isQueryInvalid = true;
      errorStartIndex = errorStatus.start;
      errorEndIndex = errorStatus.end;
      queryErrorMessage = errorStatus.queryErrorMessage;
    } else {
      isQueryInvalid = false;
      errorStartIndex = 0;
      errorEndIndex = 0;
    }
  };
  onMount(async () => {
    setTimeout(async () => {
      isQueryInvalid = false;
      errorStartIndex = 0;
      errorEndIndex = 0;
      await handleQueryErrorStatus();
    }, 200);
  });

  /**
   * Updates the request query and checks for query errors.
   */
  const handleUpdateRequestQuery = async (data: string) => {
    isQueryInvalid = false;
    errorStartIndex = 0;
    errorEndIndex = 0;
    await onUpdateRequestQuery(data);
    await handleQueryErrorStatus();
  };

  /**
   * Updates the request state and resets the query error status.
   */
  const handleUpdateRequestState = async (data: any) => {
    isQueryInvalid = false;
    errorStartIndex = 0;
    errorEndIndex = 0;
    await onUpdateRequestState(data);
    await handleQueryErrorStatus();
  };

  const handleUpdateSchema = async (data: any) => {
    isQueryInvalid = false;
    errorStartIndex = 0;
    errorEndIndex = 0;
    await updateSchema(data);
    await handleQueryErrorStatus();
  };

  loadingState.subscribe((tab) => {
    const tabIdValue = tab.get($tab.tabId);
    if (tabIdValue === undefined) {
      loading.set(false);
    } else {
      loading.set(tabIdValue);
    }
  });
</script>

{#if $tab.tabId}
  <div class="d-flex rest-explorer-layout h-100">
    <div class="w-100 d-flex flex-column h-100 px-3 pt-3 pb-2">
      <!-- Request Name Header -->
      <!-- 
        --
        -- Rest name header is set to display none 
        --
      -->
      <div class="d-flex justify-content-between w-100 p-3 d-none">
        <RequestName name={$tab.name} {onUpdateRequestName} />

        <div class="d-flex justify-content-between">
          <Button
            title="Save Request"
            type={"secondary"}
            loader={false}
            buttonClassProp="ms-2"
            buttonStartIcon={floppyDisk}
            onClick={async () => {
              const x = await onSaveRequest();
              if (
                x.status === "error" &&
                x.message ===
                  "request is not a part of any workspace or collection"
              ) {
                isExposeSaveAsRequest = true;
              } else if (x.status === "success") {
                notifications.success("API request saved successfully.");
              }
            }}
          />

          <span class="position-relative" style="width:35px;"> </span>
          <Button
            title="Share"
            type={"secondary"}
            buttonClassProp="ms-2"
            onClick={() => {}}
          />
        </div>
      </div>

      <!-- HTTP URL Section -->
      <HttpUrlSection
        class=""
        isSaveLoad={$loading}
        isSave={$tab.isSaved}
        {isGraphqlEditable}
        requestUrl={$tab.property.graphql.url}
        isSendRequestInProgress={storeData?.isSendRequestInProgress}
        onSendButtonClicked={onSendRequest}
        onCancelButtonClicked={onCancelRequest}
        {onUpdateEnvironment}
        {environmentVariables}
        {onUpdateRequestUrl}
        {toggleSaveRequest}
        {onSaveRequest}
      />
      <!--Disabling the Quick Help feature, will be taken up in next release-->
      <div class="" style="margin-top: 10px;"></div>
      <div class="pt-2"></div>
      <div style="flex:1; overflow:auto;">
        {#if !isLoading}
          <Splitpanes
            class="graph-ql-splitter w-100 h-100"
            id={""}
            horizontal={true}
            dblClickSplitter={false}
            on:resize={(e) => {
              onUpdateRequestState({
                requestBuilderLeftSplitterWidthPercentage: e.detail[0].size,
              });
              onUpdateRequestState({
                requestBuilderRightSplitterWidthPercentage: e.detail[1].size,
              });
            }}
          >
            <Pane
              minSize={30}
              size={$tab.property.graphql?.state
                ?.requestBuilderLeftSplitterWidthPercentage}
              class="position-relative bg-transparent"
            >
              <div class="h-100">
                <Splitpanes
                  class="graph-rest-splitter w-100 h-100"
                  id={""}
                  horizontal={false}
                  dblClickSplitter={false}
                  on:resize={(e) => {
                    onUpdateRequestState({
                      requestLeftSplitterWidthPercentage: e.detail[0].size,
                    });
                    onUpdateRequestState({
                      requestRightSplitterWidthPercentage: e.detail[1].size,
                    });
                  }}
                >
                  <Pane
                    minSize={30}
                    size={$tab.property.graphql?.state
                      ?.requestLeftSplitterWidthPercentage}
                    class="position-relative bg-transparent"
                  >
                    <!-- Request Pane -->
                    <div
                      class="h-100 d-flex flex-column position-relative pe-2"
                    >
                      <RequestNavigator
                        requestStateSection={$tab.property.graphql?.state
                          ?.requestNavigation}
                        {onUpdateRequestState}
                        authHeaderLength={$requestAuthHeader.value ? 1 : 0}
                        headersLength={$tab.property?.graphql?.headers
                          ?.length || 0}
                        autoGeneratedHeadersLength={$tab.property?.graphql
                          ?.autoGeneratedHeaders?.length || 0}
                        onRefreshSchema={handleFetchSchema}
                        {isSchemaFetching}
                      />
                      <div style="flex:1; overflow:auto;" class="p-0">
                        {#if $tab.property.graphql?.state?.requestNavigation === GraphqlRequestSectionTabEnum.QUERY}
                          <RequestQuery
                            value={$tab.property.graphql.state
                              .operationNavigation ===
                            GraphqlRequestOperationTabEnum.MUTATION
                              ? $tab.property.graphql.mutation
                              : $tab.property.graphql.query}
                            onUpdateRequestQuery={handleUpdateRequestQuery}
                            isError={isQueryInvalid}
                            errorMessage={queryErrorMessage}
                            {errorStartIndex}
                            {errorEndIndex}
                            {onClearQuery}
                          />
                        {:else if $tab.property.graphql?.state?.requestNavigation === GraphqlRequestSectionTabEnum.VARIABLES}
                          <RequestVariables
                            value={$tab.property.graphql.variables}
                            onUpdateRequestVariable={onUpdateVariables}
                            {onClearQuery}
                          />
                        {:else if $tab.property.graphql?.state?.requestNavigation === RequestSectionEnum.HEADERS}
                          <RequestHeaders
                            isBulkEditActive={$tab?.property?.graphql.state
                              ?.isHeaderBulkEditActive}
                            {onUpdateRequestState}
                            {environmentVariables}
                            {onUpdateEnvironment}
                            headers={$tab.property.graphql.headers}
                            autoGeneratedHeaders={$tab.property.graphql
                              .autoGeneratedHeaders}
                            authHeader={$requestAuthHeader}
                            onHeadersChange={onUpdateHeaders}
                            onAutoGeneratedHeadersChange={onUpdateAutoGeneratedHeaders}
                          />
                        {:else if $tab.property.graphql?.state?.requestNavigation === RequestSectionEnum.AUTHORIZATION}
                          <RequestAuth
                            requestStateAuth={$tab.property.graphql.state
                              .requestAuthNavigation}
                            {onUpdateRequestState}
                            auth={$tab.property.graphql.auth}
                            {onUpdateRequestAuth}
                            {onUpdateEnvironment}
                            {environmentVariables}
                          />
                        {/if}
                      </div>
                    </div>
                  </Pane>
                  <Pane
                    minSize={30}
                    size={$tab.property.graphql?.state
                      ?.requestRightSplitterWidthPercentage}
                    class="bg-transparent position-relative"
                  >
                    <!-- Response Pane -->
                    <div
                      class="d-flex flex-column h-100 ps-2"
                      style="overflow:auto;"
                    >
                      <div class="h-100 d-flex flex-column">
                        <div style="flex:1; overflow:auto;">
                          {#if storeData?.isSendRequestInProgress}
                            <ResponseDefaultScreen {isWebApp} />
                            <div
                              style="top: 0px; left: 0; right: 0; bottom: 0; z-index:3; position:absolute;"
                            >
                              <Loader loaderSize={"20px"} />
                            </div>
                          {:else if !storeData?.response.status}
                            <ResponseDefaultScreen {isWebApp} />
                          {:else if storeData?.response.status === ResponseStatusCode.ERROR}
                            <ResponseErrorScreen
                              response={storeData.response}
                            />
                          {:else if storeData?.response.status}
                            <div class="h-100 d-flex flex-column">
                              <ResponseNavigator
                                requestStateSection={storeData?.response
                                  .navigation}
                                {onUpdateResponseState}
                                responseHeadersLength={storeData?.response
                                  .headers?.length || 0}
                                response={storeData?.response}
                              />
                              {#if storeData?.response.navigation === ResponseSectionEnum.RESPONSE}
                                <div style="flex:1; overflow:auto;">
                                  <ResponseBody
                                    response={storeData?.response}
                                  />
                                </div>
                              {:else if storeData?.response.navigation === ResponseSectionEnum.HEADERS}
                                <div style="flex:1; overflow:auto;">
                                  <ResponseHeaders
                                    responseHeader={storeData.response?.headers}
                                  />
                                </div>
                              {/if}
                            </div>
                          {/if}
                        </div>
                      </div>
                    </div></Pane
                  >
                </Splitpanes>
              </div></Pane
            >
            <Pane
              minSize={30}
              size={$tab.property.graphql?.state
                ?.requestBuilderRightSplitterWidthPercentage}
              class="position-relative bg-transparent"
            >
              <div class="h-100 d-flex flex-column">
                <!-- <div class="mb-2 pt-1">
                  <ResponseStatus
                    response={storeData?.response}
                    {onClearQuery}
                    value={$tab.property.graphql.state.operationNavigation ===
                    GraphqlRequestOperationTabEnum.MUTATION
                      ? $tab.property.graphql.mutation
                      : $tab.property.graphql.query}
                  />
                </div> -->
                <div style="flex:1; overflow: auto;">
                  {#if $tab.property.graphql.state.isRequestSchemaFetched}
                    <GenerateQuery
                      schema={$tab.property.graphql.schema}
                      updateSchema={handleUpdateSchema}
                      requestOperationSection={$tab.property.graphql?.state
                        ?.operationNavigation}
                      onUpdateRequestState={handleUpdateRequestState}
                      operationSearch={$tab.property.graphql?.operationSearch}
                      {updateOperationSearch}
                      onRefreshSchema={handleFetchSchema}
                      {isSchemaFetching}
                    />
                  {:else}
                    <div style="flex: 1;">
                      <div class="error-message">
                        <div class="error-icon">
                          <WarningIcon
                            height="16"
                            width="16"
                            color="var(--icon-danger-200)"
                          />
                        </div>
                        <span class="error-text"
                          >"Unable to load schema. Please check the URL and try
                          again."</span
                        >
                      </div>
                    </div>
                  {/if}
                </div>
              </div>
            </Pane>
          </Splitpanes>
        {:else}
          <!-- loading state -->
          <ResponseDefaultScreen {isWebApp} isMainScreen={true} />
        {/if}
      </div>
    </div>
  </div>
  <Modal
    title={"Save Request"}
    type={"dark"}
    width={"55%"}
    zIndex={10000}
    isOpen={isExposeSaveAsRequest}
    handleModalState={(flag = false) => {
      isExposeSaveAsRequest = flag;
    }}
  >
    <SaveAsCollectionItem
      onClick={(flag = false) => {
        isExposeSaveAsRequest = flag;
      }}
      requestMethod={TabTypeEnum.GRAPHQL}
      requestUrl={$tab.property.graphql?.url}
      requestName={$tab.name}
      requestDescription={$tab.description}
      requestPath={$tab.path}
      collections={$collections}
      {readWorkspace}
      onSave={onSaveAsRequest}
      {onCreateFolder}
      {onCreateCollection}
      {onRenameCollection}
      {onRenameFolder}
    />
  </Modal>
{/if}

<style>
  .rest-explorer-layout {
    background-color: var(--bg-ds-surface-900);
  }

  :global(.graph-rest-splitter.splitpanes--vertical > .splitpanes__splitter) {
    width: 11px !important;
    height: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-left: 5px solid var(--border-ds-surface-900) !important;
    border-right: 5px solid var(--border-ds-surface-900) !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
  }
  :global(.graph-rest-splitter.splitpanes--horizontal > .splitpanes__splitter) {
    height: 11px !important;
    width: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-top: 5px solid var(--border-ds-surface-900) !important;
    border-bottom: 5px solid var(--border-ds-surface-900) !important;
    border-left: 0 !important;
    border-right: 0 !important;
  }
  :global(
    .graph-rest-splitter > .splitpanes__splitter:active,
    .graph-rest-splitter > .splitpanes__splitter:hover
  ) {
    background-color: var(--bg-primary-200) !important;
  }
  :global(.graph-ql-splitter.splitpanes--vertical > .splitpanes__splitter) {
    width: 11px !important;
    height: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-left: 5px solid var(--border-ds-surface-900) !important;
    border-right: 5px solid var(--border-ds-surface-900) !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
  }
  :global(.graph-ql-splitter.splitpanes--horizontal > .splitpanes__splitter) {
    height: 11px !important;
    width: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-top: 5px solid var(--border-ds-surface-900) !important;
    border-bottom: 5px solid var(--border-ds-surface-900) !important;
    border-left: 0 !important;
    border-right: 0 !important;
  }
  :global(
    .graph-ql-splitter > .splitpanes__splitter:active,
    .graph-ql-splitter > .splitpanes__splitter:hover
  ) {
    background-color: var(--bg-primary-200) !important;
  }
  .link {
    color: var(--bg-primary-300);
    text-decoration: underline;
  }
  .error-message {
    display: flex;
    align-items: center;
    background-color: var(--bg-tertiary-300);
    padding: 10px 15px;
    border-radius: 4px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    max-width: 100vw;
    justify-content: center;
  }

  .error-icon {
    margin-right: 10px;
  }

  .error-text {
    color: var(--text-secondary-110);
    font-size: 12px;
  }
</style>
