interface Window {
  runtimeConfig?: {
    VITE_WEB_API_URL?: string;
    VITE_WEB_SPARROW_SUPPORT_EMAIL?: string;
    VITE_WEB_SPARROW_OAUTH?: string;
    VITE_WEB_ENABLE_MIX_PANEL?: string;
    VITE_WEB_MIX_PANEL_TOKEN?: string;
    VITE_WEB_TERMS_OF_SERVICE?: string;
    VITE_WEB_SPARROW_WEB_URL?: string;
    VITE_WEB_SPARROW_ADMIN_URL?: string;
    VITE_WEB_SPARROW_PRIVACY_POLICY?: string;
    VITE_WEB_CANNY_URL?: string;
    VITE_WEB_APP_EDITION?: string;
    VITE_WEB_SPARROW_CONTACT_SALES_URL?: string;
    VITE_WEB_POSTHOG_CONNECTION_API_KEY?: string;
    VITE_WEB_POSTHOG_API_URL?: string;
    VITE_WEB_API_TIMEOUT?: string;
    VITE_WEB_AUTH_URL?: string;
    VITE_WEB_DOWNLOAD_LINK?: string;
    VITE_WEB_RELEASE_NOTES_PAT_TOKEN?: string;
    VITE_WEB_RELEASE_NOTES_API?: string;
    VITE_WEB_AZURE_CDN_URL?: string;
    VITE_WEB_CANNY_API?: string;
    VITE_WEB_AZURE_INSIGHTS_CONNECTION_STRING?: string;
    VITE_WEB_BASE_URL?: string;
    VITE_WEB_MARKETING_URL?: string;
    VITE_WEB_SPARROW_DOCS?: string;
    VITE_WEB_PROXY_SERVICE?: string;
    VITE_WEB_SOCKET_IO_API_URL?: string;
    VITE_WEB_APP_ENVIRONMENT_PATH?: string;
    VITE_WEB_SPARROW_AI_WEBSOCKET?: string;
    VITE_WEB_SENTRY_DSN?: string;
    VITE_WEB_APP_ENVIRONMENT?: string;
    VITE_WEB_SPARROW_WEB_APP_URL?: string;
    VITE_WEB_SPARROW_LINKEDIN?: string;
    VITE_WEB_SPARROW_GITHUB?: string;
  };
}
