apiVersion: v1
kind: Service
metadata:
  name: sparrow-web-preview-pr-${PR_NUMBER}
  namespace: sparrow-dev-preview
  labels:
    app: sparrow-web-preview
    pr: "${PR_NUMBER}"
spec:
  selector:
    app: sparrow-web-preview-pr-${PR_NUMBER}
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP