<script lang="ts">
  import { type UpdateRequestStateType } from "@sparrow/workspaces/type";
  import { RequestSectionEnum } from "@sparrow/common/types/workspace";

  import { Navigator } from "@sparrow/library/ui";
  export let requestStateSection: string;
  export let authParameterLength = 0;
  export let authHeaderLength = 0;
  export let paramsLength = 0;
  export let headersLength = 0;
  export let autoGeneratedHeadersLength = 0;
  export let onUpdateRequestState: UpdateRequestStateType;
  export let generateMockData: () => void;
  import { ThreeDotIcon } from "@sparrow/library/assets";
  import { SparkleColoredIcon } from "@sparrow/common/icons";

  let tabs: {
    name: string;
    id: RequestSectionEnum;
    count: number;
  }[] = [];

  /**
   * @description - refresh tabs label count
   * @param _paramsLength - query parameter length
   * @param _authParameterLength - auth parameter length
   * @param _headersLength - headers length
   * @param _autoGeneratedHeadersLength - auto generated headers length
   * @param _authHeaderLength - auth headers length
   */
  const refreshTabs = (
    _paramsLength: number,
    _authParameterLength: number,
    _headersLength: number,
    _autoGeneratedHeadersLength: number,
    _authHeaderLength: number,
  ) => {
    return [
      {
        name: "Params",
        id: RequestSectionEnum.PARAMETERS,
        count: _paramsLength + _authParameterLength - 1,
      },
      {
        name: "Body",
        id: RequestSectionEnum.REQUEST_BODY,
        count: 0,
      },
      {
        name: "Headers",
        id: RequestSectionEnum.HEADERS,
        count:
          _headersLength + _autoGeneratedHeadersLength + _authHeaderLength - 1,
      },
      { name: "Auth", id: RequestSectionEnum.AUTHORIZATION, count: 0 },
      { name: "Doc", id: RequestSectionEnum.DOCUMENTATION, count: 0 },
    ];
  };

  /**
   * @description - re-calculates value when dependency changes
   */
  $: {
    if (
      authParameterLength ||
      authHeaderLength ||
      paramsLength ||
      headersLength ||
      autoGeneratedHeadersLength
    ) {
      tabs = refreshTabs(
        paramsLength,
        authParameterLength,
        headersLength,
        autoGeneratedHeadersLength,
        authHeaderLength,
      );
    }
  }

  /**
   * @description - handles different key press
   * @param event - keyboard events
   */
  const handleKeyPress = (event: KeyboardEvent) => {
    if (event.altKey && event.code === "KeyP") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.PARAMETERS,
      });
    } else if (event.altKey && event.code === "KeyH") {
      onUpdateRequestState({ requestNavigation: RequestSectionEnum.HEADERS });
    } else if (event.altKey && event.code === "KeyB") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.REQUEST_BODY,
      });
    } else if (event.altKey && event.code === "KeyA") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.AUTHORIZATION,
      });
    }
  };

  const onTabClick = (tabId: ResponseSectionEnum) => {
    onUpdateRequestState({ requestNavigation: tabId });
  };
</script>

<div style="padding-bottom: 12px; position:relative;">
  <div
    class="button-container"
    style="position: absolute; top: 3px; right: 5px;"
  >
    <button
      class="generate-mock-button"
      tabindex="0"
      on:click={() => generateMockData()}
    >
      <span class="button-icon">
        <SparkleColoredIcon />
      </span>
      <span class="button-text">Generate Mock Data</span>
    </button>
  </div>
  <Navigator {tabs} {onTabClick} currentTabId={requestStateSection} />
</div>
<svelte:window on:keydown={handleKeyPress} />

<style>
  .generate-mock-button {
    font-family: "Inter", sans-serif;
    font-weight: 500;
    font-style: normal;
    font-size: 12px;
    line-height: 150%;
    letter-spacing: 0;
    vertical-align: middle;
    background-color: var(--bg-ds-surface-700);
    outline: 1px solid var(--border-ds-surface-100);
    color: var(--text-ds-neutral-50);
    gap: 4px;
    border: none;
    padding: 6px 8px;
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    position: relative;
    z-index: 1;
    min-height: 28px;
    white-space: nowrap;
  }
  .generate-mock-button * {
    pointer-events: none;
  }
  .generate-mock-button:hover {
    outline: 1px solid var(--border-ds-primary-400);
    box-shadow: 0px 0px 4px 1px #11adf04d;
    cursor: pointer;
  }
  .generate-mock-button:focus-visible {
    outline: 2px solid var(--border-ds-primary-400);
    outline-offset: 2px;
    box-shadow: 0px 0px 4px 1px #11adf04d;
    cursor: pointer;
  }
  .generate-mock-button:active {
    outline: 2px solid var(--border-ds-primary-400);
    box-shadow: 0px 0px 4px 1px #11adf04d;
    cursor: pointer;
  }

  .navigation__link {
    color: var(--text-secondary-100);
    background-color: transparent;
    border-bottom: 2px transparent;
  }

  .navigation__link:hover {
    background-color: var(--text-secondary-500);
    border-radius: 2px;
  }
  .tab-active {
    color: var(--text-secondary-100);
    border-bottom: 2px solid var(--border-primary-300) !important;
  }
</style>
