<script lang="ts">
  import { GraphqlRequestSectionTabEnum } from "@sparrow/common/types/workspace/graphql-request-tab";
  import { Navigator } from "../../../../components";
  export let requestStateSection: string;
  export let authHeaderLength = 0;
  export let headersLength = 0;
  export let autoGeneratedHeadersLength = 0;
  export let onUpdateRequestState;

  let tabs: {
    name: string;
    id: GraphqlRequestSectionTabEnum;
    count: number;
  }[] = [];

  /**
   * @description - refresh tabs label count
   * @param _headersLength - headers length
   * @param _autoGeneratedHeadersLength - auto generated headers length
   * @param _authHeaderLength - auth headers length
   */
  const refreshTabs = (
    _headersLength: number,
    _autoGeneratedHeadersLength: number,
    _authHeaderLength: number,
  ) => {
    return [
      {
        name: "Query",
        id: GraphqlRequestSectionTabEnum.QUERY,
        count: 0,
      },
      { name: "Schema", id: GraphqlRequestSectionTabEnum.Schema, count: 0 },
      {
        name: "Headers",
        id: GraphqlRequestSectionTabEnum.HEADERS,
        count:
          _headersLength + _autoGeneratedHeadersLength + _authHeaderLength - 1,
      },
      {
        name: "Auth",
        id: GraphqlRequestSectionTabEnum.AUTHORIZATION,
        count: 0,
      },
    ];
  };

  /**
   * @description - re-calculates value when dependency changes
   */
  $: {
    if (authHeaderLength || headersLength || autoGeneratedHeadersLength) {
      tabs = refreshTabs(
        headersLength,
        autoGeneratedHeadersLength,
        authHeaderLength,
      );
    }
  }

  /**
   * @description - handles different key press
   * @param event - keyboard events
   */
  const handleKeyPress = (event: KeyboardEvent) => {
    if (event.altKey && event.code === "KeyQ") {
      onUpdateRequestState({
        requestNavigation: GraphqlRequestSectionTabEnum.QUERY,
      });
    } else if (event.altKey && event.code === "KeyH") {
      onUpdateRequestState({
        requestNavigation: GraphqlRequestSectionTabEnum.HEADERS,
      });
    } else if (event.altKey && event.code === "KeyS") {
      onUpdateRequestState({
        requestNavigation: GraphqlRequestSectionTabEnum.Schema,
      });
    } else if (event.altKey && event.code === "KeyA") {
      onUpdateRequestState({
        requestNavigation: GraphqlRequestSectionTabEnum.AUTHORIZATION,
      });
    }
  };

  const onTabClick = (tabId: GraphqlRequestSectionTabEnum) => {
    onUpdateRequestState({ requestNavigation: tabId });
  };
</script>

<Navigator {tabs} {onTabClick} currentTabId={requestStateSection} />

<svelte:window on:keydown={handleKeyPress} />
