<script lang="ts">
    import { AuthSection, AuthType } from "$lib/utils/enums/authorization.enum";
    import { ItemType } from "$lib/utils/enums/item-type.enum";
    import { RequestDataType, RequestDataset, RequestDefault, RequestSection } from "$lib/utils/enums/request.enum";
    import { moveNavigation } from "$lib/utils/helpers/navigation";
  import type { CollectionsMethods } from "$lib/utils/interfaces/collections.interface";
  import type { Path } from "$lib/utils/interfaces/request.interface";
  export let name: string;
  export let id: string;
  export let collectionId: string;
  export let currentWorkspaceId: string;
  export let folderId: string;
  export let folderName: string;
  export let api;
  export let collectionsMethods: CollectionsMethods;

  let url, method, body, headers, queryParams, type;

  let apiClass = "red-api";

  const handleClick = () => {
    collectionsMethods.handleCreateTab({
      id,
    name: name,
    type: ItemType.REQUEST,
    description: "",
    property: {
      request: {
        method,
        body: {
          raw: "",
          urlencoded: [
            {
              key: "",
              value: "",
              checked: false,
            },
          ],
          formdata: {
            text: [
              {
                key: "",
                value: "",
                checked: false,
              },
            ],
            file: [
              {
                key: "",
                value: "",
                checked: false,
                base: "",
              },
            ],
          },
        },
        url:url?url:"",
        headers: [
          {
            key: "",
            value: "",
            checked: false,
          },
        ],
        queryParams: [
          {
            key: "",
            value: "",
            checked: false,
          },
        ],
        autoGeneratedHeaders: [
          {
            key: "Accept",
            value: "*/*",
            checked: true,
          },
          {
            key: "Connection",
            value: "keep-alive",
            checked: true,
          },
        ],
        state: {
          raw: RequestDataType.TEXT,
          dataset: RequestDataset.NONE,
          auth: AuthType.NO_AUTH,
          section: RequestSection.PARAMETERS,
        },
        auth: {
          bearerToken: "",
          basicAuth: {
            username: "",
            password: "",
          },
          apiKey: {
            authKey: "",
            authValue: "",
            addTo: AuthSection.HEADER,
          },
        },
        response: {
          headers: "",
          status: "",
          body: "",
          time: 0,
          size: 0,
        },
        requestInProgress: false,
      },
    },
    save: false,
    path: {},
    isActive: true,
    createdAt: new Date().toString(),
  });
    }
  $: {
    if (api) {
      if (api.property) {
        api = api.property;
      }
      url = api.request.url;
      method = api.request.method;
      headers = api.request.headers;
      queryParams = api.request.queryParams;
      body = api.request.body;
      type = api.request.type;
    }
  }
  $: {
    if (method) {
      if (method === "DELETE") apiClass = "red-api";
      else if (method === "GET") apiClass = "green-api";
      else if (method === "POST") apiClass = "yellow-api";
      else if (method === "PUT") apiClass = "blue-api";
      else if (method === "ARC") apiClass = "grey-api";
    }
  }

  let path: Path = {
    workspaceId: currentWorkspaceId,
    collectionId,
    folderId,
    folderName,
  };
</script>

<div
  class="d-flex align-items-center"
  style="height:32px;"
  on:click={()=>{handleClick()}}
>
  <div class="api-method {apiClass}">
    {method.toUpperCase()}
  </div>
  <div class="api-name">
    {name}
  </div>
</div>

<style>
  .red-api {
    color: var(--request-delete);
  }
  .green-api {
    color: var(--request-get);
  }
  .yellow-api {
    color: var(--request-post);
  }
  .blue-api {
    color: var(--request-put);
  }
  .grey-api {
    color: var(--request-arc);
  }
  .api-method {
    font-size: 12px;
    font-weight: 500;
    margin-right: 8px;
    text-align: left;
  }
  .api-name {
    font-size: 12px;
    font-weight: 400;
  }
</style>
