<script lang="ts">
  import { type UpdateRequestStateType } from "@sparrow/workspaces/type";
  import { RequestSectionEnum } from "@sparrow/common/types/workspace";
  import { Label } from "@sparrow/library/ui";
  import { SocketSectionEnum } from "@sparrow/common/types/workspace/web-socket";
  export let requestStateSection: string | undefined;
  export let paramsLength = 0;
  export let headersLength = 0;
  export let autoGeneratedHeadersLength = 0;
  export let onUpdateRequestState: UpdateRequestStateType;

  let tabs: {
    name: string;
    id: RequestSectionEnum;
    count: number;
  }[] = [];

  /**
   * @description - refresh tabs label count
   * @param _paramsLength - query parameter length
   * @param _authParameterLength - auth parameter length
   * @param _headersLength - headers length
   * @param _autoGeneratedHeadersLength - auto generated headers length
   * @param _authHeaderLength - auth headers length
   */
  const refreshTabs = (
    _paramsLength: number,
    _headersLength: number,
    _autoGeneratedHeadersLength: number,
  ) => {
    return [
      {
        name: "Message",
        id: SocketSectionEnum.MESSAGE,
        count: 0,
      },
      {
        name: "Parameters",
        id: SocketSectionEnum.PARAMETERS,
        count: _paramsLength - 1,
      },
      {
        name: "Headers",
        id: SocketSectionEnum.HEADERS,
        count: _headersLength + _autoGeneratedHeadersLength - 1,
      },
    ];
  };

  /**
   * @description - re-calculates value when dependency changes
   */
  $: {
    if (paramsLength || headersLength || autoGeneratedHeadersLength) {
      tabs = refreshTabs(
        paramsLength,
        headersLength,
        autoGeneratedHeadersLength,
      );
    }
  }
</script>

<div class="pb-2">
  <!-- Tabs -->
  <div class="d-flex mb-2">
    {#each tabs as tab}
      <button
        class="navigation__link border-0 sparrow-fs-12 request-tab me-3 {tab.id ===
        requestStateSection
          ? 'tab-active'
          : ''}"
        role="tab"
        on:click={() => {
          onUpdateRequestState({ socketNavigation: tab.id });
        }}
      >
        <span class="d-flex align-items-center ps-1 pe-1"
          ><span>{tab.name}</span>
          {#if tab.count}
            <span class="ms-1"></span>
            <Label number={tab.count} />
          {/if}
        </span>
      </button>
    {/each}
  </div>
</div>

<!-- <svelte:window on:keydown={handleKeyPress} /> -->

<style>
  .navigation__link {
    color: var(--text-secondary-200);
    background-color: transparent;
    border-bottom: 2px transparent;
  }

  .navigation__link:hover {
    background-color: var(--text-secondary-500);
    border-radius: 2px;
  }
  .tab-active {
    color: var(--text-secondary-100);
    border-bottom: 2px solid var(--border-primary-300) !important;
  }
</style>
