import {
  toTypedRxJsonSchema,
  type ExtractDocumentTypeFromTypedRxJsonSchema,
  type RxJsonSchema,
} from "rxdb";

const keyValueTextLiteral = {
  type: "array",
  items: {
    type: "object",
    properties: {
      key: {
        type: "string",
      },
      value: {
        type: "string",
      },
      checked: {
        type: "boolean",
      },
    },
  },
};

const keyValueFileLiteral = {
  type: "array",
  items: {
    type: "object",
    properties: {
      key: {
        type: "string",
      },
      value: {
        type: "string",
      },
      base: {
        type: "string",
      },
      checked: {
        type: "boolean",
      },
    },
  },
};

const formdataLiteral = {
  type: "object",
  properties: {
    text: keyValueTextLiteral,
    file: keyValueFileLiteral,
  },
};

const bodyLiteral = {
  type: "object",
  properties: {
    raw: {
      type: "string",
    },
    urlencoded: {
      type: "string",
    },
    formdata: formdataLiteral,
  },
};

const responseLiteral = {
  type: "object",
  properties: {
    headers: {
      type: "string",
    },
    status: {
      type: "string",
    },
    body: {
      type: "string",
    },
    size: {
      type: "number",
    },
    time: {
      type: "number",
    },
  },
};
const stateLiteral = {
  type: "object",
  properties: {
    requestBodyLanguage: {
      type: "string",
    },
    requestBodyNavigation: {
      type: "string",
    },
    requestAuthNavigation: {
      type: "string",
    },
    requestNavigation: {
      type: "string",
    },
    responseNavigation: {
      type: "string",
    },
    responseBodyLanguage: {
      type: "string",
    },
    responseBodyFormatter: {
      type: "string",
    },
    requestExtensionNavigation: {
      type: "string",
    },
    requestSplitterDirection: {
      type: "string",
    },
    requestLeftSplitterWidthPercentage: {
      type: "number",
    },
    requestRightSplitterWidthPercentage: {
      type: "number",
    },
    isExposeEditDescription: {
      type: "boolean",
    },
    isSendRequestInProgress: {
      type: "boolean",
      default: false,
    },
    isSaveDescriptionInProgress: {
      type: "boolean",
      default: false,
    },
    isSaveRequestInProgress: {
      type: "boolean",
    },
  },
};
const basicAuthLiteral = {
  type: "object",
  properties: {
    username: {
      type: "string",
    },
    password: {
      type: "string",
    },
  },
};

const apiKeyLiteral = {
  type: "object",
  properties: {
    authKey: {
      type: "string",
    },
    authValue: {
      type: "string",
    },
    addTo: {
      type: "string",
    },
  },
};

const authLiteral = {
  type: "object",
  properties: {
    bearerToken: {
      type: "string",
    },
    basicAuth: basicAuthLiteral,
    apiKey: apiKeyLiteral,
  },
};

const saveLiteral = {
  type: "object",
  properties: {
    api: {
      type: "boolean",
    },
    description: {
      type: "boolean",
    },
  },
};

const requestLiteral = {
  type: "object",
  properties: {
    method: {
      type: "string",
    },
    body: bodyLiteral,
    url: {
      type: "string",
    },
    headers: keyValueTextLiteral,
    queryParams: keyValueTextLiteral,
    autoGeneratedHeaders: keyValueTextLiteral,
    response: responseLiteral,
    state: stateLiteral,
    auth: authLiteral,
    save: saveLiteral,
  },
};

const propertyLiteral = {
  type: "object",
  properties: {
    request: requestLiteral,
    folder: {
      type: "string",
    },
    collection: {
      type: "string",
    },
    workspace: {
      type: "string",
    },
  },
};

const pathLiteral = {
  type: "object",
  properties: {
    workspaceId: {
      type: "string",
    },
    collectionId: {
      type: "string",
    },
    folderId: {
      type: "string",
    },
  },
};

export const tabSchemaLiteral = {
  title: "Opened tabs that will be shown on dashboard",
  primaryKey: {
    key: "tabId",
    fields: ["id"],
    separator: "|",
  },
  type: "object",
  version: 5,
  properties: {
    tabId: {
      // ---- RxDocumentId
      type: "string",
      maxLength: 100,
    },
    id: {
      // ---- MongoDocumentId
      type: "string",
      maxLength: 100,
    },
    name: {
      type: "string",
    },
    description: {
      type: "string",
    },
    isDeleted: {
      type: "boolean",
    },
    activeSync: {
      type: "boolean",
    },
    source: {
      type: "string",
    },
    type: {
      type: "string",
    },
    property: propertyLiteral,
    isActive: {
      type: "boolean",
      default: true,
    },
    isSaved: {
      type: "boolean",
    },
    path: pathLiteral,
    timestamp: {
      type: "string",
      maxLength: 100,
    },
    index: {
      type: "number",
    },
  },
  required: ["id", "name"],
  indexes: ["timestamp"],
} as const;

const schemaTyped = toTypedRxJsonSchema(tabSchemaLiteral);

export type TabDocType = ExtractDocumentTypeFromTypedRxJsonSchema<
  typeof schemaTyped
>;

export const tabSchema: RxJsonSchema<TabDocType> = tabSchemaLiteral;
