<script lang="ts">
  import { writable } from "svelte/store";
  import {
    SvelteFlow,
    Background,
    type Node,
    type NodeTypes,
  } from "@xyflow/svelte";

  import {
    StartBlock,
    RequestBlock,
    RequestBodyTestFlow,
    RunHistory,
    RequestHeaderTestFlow,
    RequestParameterTestFlow,
    RequestNavigatorTestFlow,
    ResponseErrorScreen,
    ResponseStatus,
    ResponseNavigator,
    ResponseBodyNavigator,
    ResponseBody,
    ResponseHeaders,
    TestFlowName,
    SaveTestflow,
  } from "../components";
  import {
    RequestDatasetEnum,
    RequestDataTypeEnum,
    RequestSectionEnum,
    ResponseFormatterEnum,
    ResponseSectionEnum,
    type CollectionDto,
  } from "@sparrow/common/types/workspace";
  import { type Tab } from "@sparrow/common/types/workspace/tab";

  import "@xyflow/svelte/dist/style.css";
  import { onDestroy, onMount } from "svelte";

  import "@xyflow/svelte/dist/style.css";
  import type { Observable } from "rxjs";
  import type { CollectionDocument } from "@app/database/database";
  import {
    TableSidebar,
    TestFlowTourGuide,
  } from "@sparrow/workspaces/components";
  import { PlayFilled, RunIcon, StopFilled } from "@sparrow/library/icons";
  import { Button, Modal, notifications } from "@sparrow/library/ui";
  import { BroomRegular } from "@sparrow/library/icons";
  import { Tooltip } from "@sparrow/library/ui";
  import DeleteNode from "../../../components/delete-node/DeleteNode.svelte";
  import CustomRequest from "../../../components/custom-request-modal/CustomRequest.svelte";
  import { ResponseStatusCode } from "@sparrow/common/enums";
  import type {
    TFDataStoreType,
    TFEdgeHandlerType,
    TFEdgeType,
    TFNodeHandlerType,
    TFNodeStoreType,
    TFNodeType,
  } from "@sparrow/common/types/workspace/testflow";
  import { Events } from "@sparrow/common/enums/mixpanel-events.enum";
  import MixpanelEvent from "@app/utils/mixpanel/MixpanelEvent";
  import {
    Debounce,
    InitFolderTab,
    InitRequestTab,
    OSDetector,
  } from "@sparrow/common/utils";
  import { stringify, v4 as uuidv4 } from "uuid";
  import {
    currentStep,
    isTestFlowTourGuideOpen,
  } from "../../../stores/guide.tour";
  import { platform } from "@tauri-apps/plugin-os";
  import {
    defaultAutoGeneratedHeaders,
    defaultState,
    defaultRequestData,
  } from "../../../../../@sparrow-common/src/utils/testFlow.helper";
  import SaveNode from "../../../components/save-node-modal/SaveNode.svelte";
  import TestFlowBottomPanel from "../components/test-flow-bottom-panel/TestFlowBottomPanel.svelte";
  import {
    HttpRequestAuthTypeBaseEnum,
    HttpRequestContentTypeBaseEnum,
  } from "@sparrow/common/types/workspace/http-request-base";
  import TestflowDynamicExpression from "../../testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte";
  // import { isDynamicExpressionModalOpen } from "../store/testflow";
  import { selectedRequestTypes } from "../store/testflow";
  import {
    isDynamicExpressionContent,
    updateDynamicExpressionValue,
  } from "../store/testflow";

  // Declaring props for the component
  export let tab: Observable<Partial<Tab>>;
  export let onUpdateNodes;
  export let onUpdateEdges;
  export let collectionList: Observable<CollectionDocument[]>;
  export let onClickRun;
  export let onRunSampleApi;
  export let testflowStore: TFDataStoreType;
  export let toggleHistoryDetails;
  export let toggleHistoryContainer;
  export let environmentVariables;
  export let isTestflowEditable;
  export let onRedrectRequest;
  export let onUpdateTestFlowName;
  export let onUpdateBlockData;
  export let onSaveTestflow;
  export let isWebApp;
  export let deleteNodeResponse;
  export let onClickStop;
  export let onClearTestflow;
  export let isTestFlowEmpty;
  export let onSelectRequest;
  export let userRole;
  export let onUpdateEnvironment;
  export let runSingleNode;
  export let onPreviewExpression;

  const checkRequestExistInNode = (_id: string) => {
    let result = false;
    nodes.update((nodes) => {
      for (let index = 0; index < nodes.length; index++) {
        if (nodes[index].id === _id) {
          if (nodes[index]?.data?.requestData?.method) {
            result = true;
            unsavedChangesModal.blockName = nodes[index]?.data
              ?.blockName as string;
            unsavedChangesModal.id = nodes[index].id;
            unsavedChangesModal.requestName =
              nodes[index]?.data?.requestData?.name;
            break;
          }
        }
      }
      return nodes;
    });
    return result;
  };

  const osDetector = new OSDetector();
  let userOS = osDetector.getOS();
  let limitNodesChange = 0;
  let deletedNodeId: string;
  let deleteNodeName: string = "";
  let customRequestName: string = "";
  let customRequestURL: string = "";
  let customHTTPRequestMethod: string = "GET";

  let isDeleteNodeModalOpen = false;
  let isSwitchNodeRequestModalOpen = false;
  let isAddCustomRequestModalOpen = false;

  let divElement: HTMLElement;
  let sampleApiData: TFNodeStoreType;
  let deleteCount = 0; // Variable to store the count of nodes to be deleted
  let selectedTab = "response";
  let requestNavigation = "Request Body";
  let responseNavigation = "Response";
  let nodesValue = 1;
  let selectedNodeName = "";
  let selectedNodeId = "";
  let selectedNode: TFNodeStoreType | undefined;
  let selectedBlock: any | undefined;
  let updateNodeId: string;
  let updateNodeName: string;
  let updateNodeRequestId: string;
  let updateNodeCollectionId: string;
  let updateNodeMethod: string;
  let updateNodeUrl: string;
  let updateNodeFolderId: any;
  // Flag to control whether nodes are draggable
  let isNodesDraggable = false;
  let blockName = `Block ${nodesValue}`;
  // List to store collection documents and filtered collections
  let collectionListDocument: CollectionDocument[];
  let filteredCollections = writable<CollectionDto[]>([]);

  // Writable stores for nodes and edges
  const nodes = writable<Node[]>([]);
  const edges = writable<TFEdgeHandlerType[]>([]);

  /**
   * Checks if edges exist for the given node ID.
   * @param _id - Node ID to check for connected edges.
   * @returns True if edges exist, otherwise false.
   */
  const checkIfEdgesExist = (_id: string) => {
    let edge: TFEdgeHandlerType[] = [];
    edges.subscribe((value) => {
      edge = value;
    })();
    let response = false;
    edge.forEach((it) => {
      if (it.id.replace("xy-edge__", "").split("-")[0] === _id) {
        response = true;
      }
    });
    return response;
  };

  const createBlankRequestObject = (
    _url: string,
    _method: string,
    _name: string,
  ) => {
    const response: any = {};
    const tempTab = new InitRequestTab("uuid", "uuid").getValue().property
      .request;
    response.url = _url; // getting url from Modal.
    response.method = _method; // getting method from Modal.
    response.name = _name; // getting name from Modal.
    response.queryParams = tempTab?.queryParams;
    response.headers = tempTab?.headers;
    response.autoGeneratedHeaders = tempTab?.autoGeneratedHeaders;
    response.body = tempTab?.body;
    response.body.formdata = {
      text: [
        {
          key: "",
          value: "",
          checked: false,
        },
      ],
      file: [],
    };
    response.auth = tempTab?.auth;
    response.state = tempTab?.state;
    return response;
  };

  const setBodyType = (header: string) => {
    let requestBodyNavigation = RequestDatasetEnum.RAW;
    let requestBodyLanguage = RequestDataTypeEnum.TEXT;
    switch (header) {
      case HttpRequestContentTypeBaseEnum["none"]:
        requestBodyNavigation = RequestDatasetEnum.NONE;
        requestBodyLanguage = RequestDataTypeEnum.TEXT;
        break;
      case HttpRequestContentTypeBaseEnum["application/json"]:
        requestBodyNavigation = RequestDatasetEnum.RAW;
        requestBodyLanguage = RequestDataTypeEnum.JSON;
        break;
      case HttpRequestContentTypeBaseEnum["application/xml"]:
        requestBodyNavigation = RequestDatasetEnum.RAW;
        requestBodyLanguage = RequestDataTypeEnum.XML;
        break;
      case HttpRequestContentTypeBaseEnum["application/javascript"]:
        requestBodyNavigation = RequestDatasetEnum.RAW;
        requestBodyLanguage = RequestDataTypeEnum.JAVASCRIPT;
        break;
      case HttpRequestContentTypeBaseEnum["text/plain"]:
        requestBodyNavigation = RequestDatasetEnum.RAW;
        requestBodyLanguage = RequestDataTypeEnum.TEXT;
        break;
      case HttpRequestContentTypeBaseEnum["text/html"]:
        requestBodyNavigation = RequestDatasetEnum.RAW;
        requestBodyLanguage = RequestDataTypeEnum.HTML;
        break;
      case HttpRequestContentTypeBaseEnum["application/x-www-form-urlencoded"]:
        requestBodyNavigation = RequestDatasetEnum.URLENCODED;
        break;
      case HttpRequestContentTypeBaseEnum["multipart/form-data"]:
        requestBodyNavigation = RequestDatasetEnum.FORMDATA;
        break;
    }
    return { requestBodyLanguage, requestBodyNavigation };
  };

  const setAuthType = (
    auth: HttpRequestAuthTypeBaseEnum,
  ): HttpRequestAuthTypeBaseEnum => {
    let requestAuthNavigation = HttpRequestAuthTypeBaseEnum.NO_AUTH;
    switch (auth) {
      case HttpRequestAuthTypeBaseEnum.NO_AUTH:
        requestAuthNavigation = HttpRequestAuthTypeBaseEnum.NO_AUTH;
        break;
      case HttpRequestAuthTypeBaseEnum.API_KEY:
        requestAuthNavigation = HttpRequestAuthTypeBaseEnum.API_KEY;
        break;
      case HttpRequestAuthTypeBaseEnum.BASIC_AUTH:
        requestAuthNavigation = HttpRequestAuthTypeBaseEnum.BASIC_AUTH;
        break;
      case HttpRequestAuthTypeBaseEnum.BEARER_TOKEN:
        requestAuthNavigation = HttpRequestAuthTypeBaseEnum.BEARER_TOKEN;
        break;
      case HttpRequestAuthTypeBaseEnum.INHERIT_AUTH:
        requestAuthNavigation = HttpRequestAuthTypeBaseEnum.NO_AUTH;
        break;
    }
    return requestAuthNavigation;
  };

  const createCustomRequestObject = async (
    collectionId: string,
    requestId: string,
    folderId: string,
  ) => {
    const response: any = {};
    const tempTab = new InitRequestTab("uuid", "uuid").getValue().property
      .request;
    const data = await onSelectRequest(collectionId, requestId, folderId);
    if (!data) {
      // something went wrong, lets debug.
    }
    if (data?.request?.autoGeneratedHeaders) {
      response.autoGeneratedHeaders = data?.request?.autoGeneratedHeaders;
    } else {
      response.autoGeneratedHeaders = tempTab?.autoGeneratedHeaders;
    }
    if (data?.request?.headers) {
      response.headers = data?.request?.headers;
    } else {
      response.headers = tempTab?.headers;
    }
    if (data?.request?.queryParams) {
      response.queryParams = data?.request?.queryParams;
    } else {
      response.queryParams = tempTab?.queryParams;
    }
    if (data?.request?.body) {
      response.body = data?.request?.body;
    } else {
      response.body = tempTab?.body;
      response.body.formdata = {
        text: [
          {
            key: "",
            value: "",
            checked: false,
          },
        ],
        file: [],
      };
    }
    if (data?.request?.auth) {
      response.auth = data?.request?.auth;
    } else {
      response.auth = tempTab?.auth;
    }
    if (data?.request?.url) {
      response.url = data?.request?.url;
    } else {
      response.url = tempTab?.url;
    }
    if (data?.request?.method) {
      response.method = data?.request?.method;
    } else {
      response.method = tempTab?.method;
    }
    if (data?.name) {
      response.name = data.name;
    } else {
      response.name = "Untitled";
    }
    response.state = tempTab?.state;
    if (data?.request?.selectedRequestBodyType) {
      const bodyType = setBodyType(data?.request?.selectedRequestBodyType);
      if (bodyType?.requestBodyLanguage) {
        response.state.requestBodyLanguage = bodyType.requestBodyLanguage;
      }
      if (bodyType?.requestBodyNavigation) {
        response.state.requestBodyNavigation = bodyType.requestBodyNavigation;
      }
    }
    if (data?.request?.selectedRequestAuthType) {
      const AuthType = setAuthType(data?.request?.selectedRequestAuthType);
      if (AuthType) {
        response.state.requestAuthNavigation = AuthType;
      }
    }
    return response;
  };

  let dynamicExpressionEditorContent = "";
  let dynamicExpressionModal = {};
  let handleOpenCurrentDynamicExpression = (obj) => {
    dynamicExpressionModal = {};
    dynamicExpressionModal = obj;
    dynamicExpressionEditorContent = obj?.source?.content?.slice(4, -4) || "";
    isDynamicExpressionModalOpen = true;
  };

  $: console.log(selectedNodeId, "selectedNodeId");

  const onInsertExpression = (newExpression) => {
    if (dynamicExpressionModal?.source) {
      dynamicExpressionModal.dispatch({
        changes: {
          from: dynamicExpressionModal.source.from,
          to: dynamicExpressionModal.source.to,
          insert: "[*$[" + newExpression + "]$*]",
        },
      });
    } else {
      dynamicExpressionModal.dispatch({
        changes: {
          from: 0,
          to: 0,
          insert: "[*$[" + newExpression + "]$*]",
        },
      });
    }
    isDynamicExpressionModalOpen = false;
    return;
    nodes.update((_nodes) => {
      const dbNodes = _nodes;
      for (let index = 0; index < dbNodes.length; index++) {
        if (dbNodes[index].id === selectedNodeId) {
          if (dynamicExpressionModal.type === "url") {
            //
            // URL
            //
            const requestUrl = dbNodes[index].data.requestData.url;
            let output = "";
            if (dynamicExpressionModal?.source) {
              output =
                requestUrl.slice(0, dynamicExpressionModal.source.from) +
                "[*$[" +
                newExpression +
                "]$*]" +
                requestUrl.slice(dynamicExpressionModal.source.to);
            } else {
              output = requestUrl + "[*$[" + newExpression + "]$*]";
            }
            dbNodes[index].data.requestData.url = output;
          } else if (dynamicExpressionModal.type === "headers") {
            //
            // Headers
            //
            const requestHeaders = dbNodes[index].data.requestData.headers;
            for (let i = 0; i < requestHeaders.length; i++) {
              if (dynamicExpressionModal.destination.index === i) {
                if (dynamicExpressionModal.destination.row === "value") {
                  let output = "";
                  if (dynamicExpressionModal?.source) {
                    output =
                      requestHeaders[i].value.slice(
                        0,
                        dynamicExpressionModal.source.from,
                      ) +
                      "[*$[" +
                      newExpression +
                      "]$*]" +
                      requestHeaders[i].value.slice(
                        dynamicExpressionModal.source.to,
                      );
                  } else {
                    output =
                      requestHeaders[i].value + "[*$[" + newExpression + "]$*]";
                  }
                  requestHeaders[i].value = output;
                  dbNodes[index].data.requestData.headers = requestHeaders;
                }
              }
            }
          } else if (dynamicExpressionModal.type === "parameters") {
            //
            // Parameters
            //
            const requestParams = dbNodes[index].data.requestData.queryParams;
            for (let i = 0; i < requestParams.length; i++) {
              if (dynamicExpressionModal.destination.index === i) {
                if (dynamicExpressionModal.destination.row === "value") {
                  let output = "";
                  if (dynamicExpressionModal?.source) {
                    output =
                      requestParams[i].value.slice(
                        0,
                        dynamicExpressionModal.source.from,
                      ) +
                      "[*$[" +
                      newExpression +
                      "]$*]" +
                      requestParams[i].value.slice(
                        dynamicExpressionModal.source.to,
                      );
                  } else {
                    output =
                      requestParams[i].value + "[*$[" + newExpression + "]$*]";
                  }
                  requestParams[i].value = output;
                  dbNodes[index].data.requestData.queryParams = requestParams;
                }
              }
            }
          }
        }
      }
      return dbNodes;
    });
    isDynamicExpressionModalOpen = false;
  };

  /**
   * Updates the selected API in a specific node.
   * @param id - Node ID.
   * @param name - Name of the API.
   * @param requestId - Request ID.
   * @param collectionId - Collection ID.
   * @param method - Request method (e.g., GET, POST).
   * @param folderId - Folder ID (optional).
   */
  const updateNodeRequest = async (
    id: string,
    name: string,
    requestId: string,
    collectionId: string,
    method: string,
    folderId?: string,
    url?: string,
  ) => {
    let response: any = {};
    if (collectionId) {
      response = await createCustomRequestObject(
        collectionId,
        requestId,
        folderId as string,
      );
    } else {
      // create custom API Request.
      response = await createBlankRequestObject(url as string, method, name);
    }

    nodes.update((_nodes) => {
      const dbNodes = _nodes;
      for (let index = 0; index < dbNodes.length; index++) {
        if (dbNodes[index].id === id) {
          dbNodes[index].data.requestId = requestId;
          dbNodes[index].data.collectionId = collectionId;
          dbNodes[index].data.folderId = folderId ?? "";
          dbNodes[index].data.requestData = response;
          dbNodes[index].data.isDeleted = false;
        }
      }
      return dbNodes;
    });
  };

  const handleUpdateRequestData = async (field: string, value: any) => {
    if (!selectedBlock) {
      console.warn("Invalid block data structure");
      return;
    }

    const updatedBlock = JSON.parse(JSON.stringify(selectedBlock));

    const updateMatchingKeys = (obj: any) => {
      if (typeof obj !== "object" || obj === null) return;

      for (const key in obj) {
        if (key === field) {
          obj[key] = value;
        } else if (typeof obj[key] === "object") {
          updateMatchingKeys(obj[key]);
        }
      }
    };

    updateMatchingKeys(updatedBlock);
    selectedBlock = updatedBlock;

    nodes.update((_nodes) => {
      let dbNodes = [..._nodes];

      for (let i = 0; i < dbNodes.length; i++) {
        if (dbNodes[i].id === updatedBlock.id) {
          // Preserve only the specified keys from the original data
          const preservedKeys: Array<string> = [
            "blocks",
            "collections",
            "connector",
            "onCheckEdges",
            "onClick",
            "onOpenAddCustomRequestModal",
            "onContextMenu",
            "onOpenSaveNodeRequestModal",
            "updateBlockName",
          ];

          const originalData = dbNodes[i].data || {};
          const updatedData = updatedBlock.data || {};

          const preservedData = {};
          for (const key of preservedKeys) {
            if (key in originalData) {
              preservedData[key] = originalData[key];
            }
          }

          dbNodes[i] = {
            ...dbNodes[i],
            ...updatedBlock,
            data: {
              ...updatedData,
              ...preservedData,
            },
          };
        }
      }

      return dbNodes;
    });
  };

  /**
   * Finds the next available node ID.
   * @param list - List of existing nodes.
   * @returns The next available node ID as a string.
   */
  const findNextNodeId = (list: { id: string }[]): string => {
    const isNameAvailable: (proposedName: string) => boolean = (
      proposedName,
    ) => {
      return list.some((element) => {
        return element.id === proposedName;
      });
    };

    for (let i = 1; i < list.length + 10; i++) {
      const proposedName: string = `${i}`;
      if (!isNameAvailable(proposedName)) {
        return proposedName;
      }
    }
    return "";
  };

  // Filter collections based on the current tab's workspace ID
  const collectionsSubscriber = collectionList.subscribe((value) => {
    if (value) {
      collectionListDocument = value?.filter(
        (value) => value.workspaceId === $tab?.path?.workspaceId,
      );
      filteredCollections.set(
        collectionListDocument as unknown as CollectionDto[],
      );
    }
  });

  nodes.subscribe((nodes) => {
    if (nodes?.length > 0) {
      if (!limitNodesChange) {
        limitNodesChange = limitNodesChange + 1;
      }
    }
  });

  /**
   * Opens the delete confirmation modal and sets the ID of the node to be deleted.
   * Also triggers the count of the next node to be deleted.
   *
   * @param id - The ID of the node to be deleted.
   */
  const handleDeleteModal = (id: string) => {
    if (!id) return;
    if (id === "1") return;
    isDeleteNodeModalOpen = true;
    deletedNodeId = id;
    let filteredNodes = $nodes.filter(
      (node) => node.id === id,
    ) as unknown as TFNodeHandlerType[];
    deleteNodeName = filteredNodes[0]?.data?.name;
    countNextDeletedNode(id);
  };

  /**
   * @description - Handles the creation of a custom request.
   * the selected HTTP method, request name, and request URL.
   */
  const handleCreateCustomRequest = async (
    _requestName: string,
    _requestMethod: string,
    _requestUrl: string,
  ) => {
    const isExist = await checkRequestExistInNode(customRequestModal.id);

    updateNodeId = customRequestModal.id;
    updateNodeName = _requestName;
    updateNodeRequestId = uuidv4();
    updateNodeCollectionId = "";
    updateNodeMethod = _requestMethod;
    updateNodeFolderId = "";
    updateNodeUrl = _requestUrl;

    if (isExist) {
      isSwitchNodeRequestModalOpen = true;
    } else {
      // populate new api from custom request button
      await updateNodeRequest(
        customRequestModal.id,
        _requestName,
        uuidv4(),
        "",
        _requestMethod,
        "",
        _requestUrl,
      );
    }
    isAddCustomRequestModalOpen = false;
  };

  /**
   * Opens the "Add Custom Request" modal.
   *
   * @param id - The ID associated with the custom request.
   */
  let customRequestModal = {
    id: "",
  };
  let unsavedChangesModal = {
    id: "",
    blockName: "",
    requestName: "",
  };
  const handleOpenAddCustomRequestModal = (_id: string) => {
    isAddCustomRequestModalOpen = true;
    customRequestModal.id = _id;
  };

  /**
   * Opens the "Save Request" modal and update the node's API request.
   **/

  const handleNodeRequestDropdown = async (
    nodeId: string,
    name: string,
    requestId: string,
    collectionId: string,
    method: string,
    folderId: string,
  ) => {
    const isExist = await checkRequestExistInNode(nodeId);

    updateNodeId = nodeId;
    updateNodeName = name;
    updateNodeRequestId = requestId;
    updateNodeCollectionId = collectionId;
    updateNodeMethod = method;
    updateNodeFolderId = folderId;
    updateNodeUrl = "";

    if (isExist) {
      isSwitchNodeRequestModalOpen = true;
    } else {
      // populate existing api for the first time from the api dropdown
      await updateNodeRequest(
        nodeId,
        name,
        requestId,
        collectionId,
        method,
        folderId,
        "",
      );
    }
  };

  /**
   * Creates a new node and connects it to the existing node.
   * @param _id - The ID of the existing node.
   */
  const createNewNode = async (_id: string, _requestData = undefined) => {
    if (!_id) return;

    let requestData;
    if (_requestData) {
      requestData = await createCustomRequestObject(
        _requestData?.collectionId,
        _requestData?.requestId,
        _requestData?.folderId,
      );
    }

    // handles run from from start button click
    if (_id === "0") {
      await onClickRun();
      selectNode("2");
      MixpanelEvent(Events.Run_TestFlows);
      return;
    }

    if (checkIfEdgesExist(_id)) {
      return;
    }

    const targetNode = findNextNodeId($nodes);

    nodes.update((_nodes: Node[] | any[]) => {
      let nextNodePosition;
      // Find the next node position based on the current node's position
      for (let i = 0; i < _nodes?.length; i++) {
        if (_nodes[i].id === _id) {
          const additionValue = i === 0 ? 0 : 50;
          nextNodePosition = {
            x: _nodes[i].position.x + 300 + additionValue,
            y: _nodes[i].position.y,
          };
        }
      }
      return [
        ...(_nodes || []),
        {
          id: targetNode,
          type: "requestBlock",
          data: {
            blockName: `block${targetNode - 1}`,
            blocks: nodes,
            connector: edges,
            onClick: function (_id: string, _options = undefined) {
              createNewNode(_id, _options);
            },
            onCheckEdges: function (_id: string) {
              return checkIfEdgesExist(_id);
            },
            onContextMenu: function (id: string, _event: string) {
              if (_event === "delete") {
                handleDeleteModal(id);
              } else if (
                _event === "run-from-here" ||
                _event === "run-till-here"
              ) {
                partialRun(id, _event);
              }
            },
            onOpenAddCustomRequestModal: function (id: string) {
              handleOpenAddCustomRequestModal(id);
            },
            onOpenSaveNodeRequestModal: function (
              nodeId: string,
              name: string,
              requestId: string,
              collectionId: string,
              method: string,
              folderId: string,
            ) {
              handleNodeRequestDropdown(
                nodeId,
                name,
                requestId,
                collectionId,
                method,
                folderId,
              );
            },
            updateBlockName: function (field: string, value: string) {
              handleUpdateRequestData(field, value);
            },
            collectionId: _requestData?.collectionId,
            folderId: _requestData?.folderId,
            requestId: _requestData?.requestId,
            collections: filteredCollections,
            tabId: $tab.tabId,
            requestData: requestData || createBlankRequestObject("", "", ""),
          },
          position: nextNodePosition,
          deletable: false,
          draggable: isNodesDraggable, // Disable dragging for this node
        },
      ];
    });
    edges.update((edges) => {
      return [
        ...edges,
        {
          id: "xy-edge__" + _id + "-" + targetNode,
          source: _id,
          target: targetNode,
          deletable: false,
        },
      ];
    });
  };

  /**
   * Initializes nodes and edges on component mount.
   */
  onMount(() => {
    // Load initial nodes from the tab property
    nodes.update((_nodes: Node[]) => {
      const dbNodes = $tab?.property?.testflow?.nodes as TFNodeType[];
      let res = [];
      for (let i = 0; i < dbNodes.length; i++) {
        res.push({
          id: dbNodes[i].id,
          type: dbNodes[i].type,
          data: {
            blockName: dbNodes[i]?.data?.blockName,
            blocks: nodes,
            connector: edges,
            onClick: function (_id: string, _options = undefined) {
              createNewNode(_id, _options);
            },
            onCheckEdges: function (_id: string) {
              return checkIfEdgesExist(_id);
            },
            onContextMenu: function (id: string, _event: string) {
              if (_event === "delete") {
                handleDeleteModal(id);
              } else if (
                _event === "run-from-here" ||
                _event === "run-till-here"
              ) {
                partialRun(id, _event);
              }
            },
            onOpenAddCustomRequestModal: function (id: string) {
              handleOpenAddCustomRequestModal(id);
            },
            onOpenSaveNodeRequestModal: function (
              nodeId: string,
              name: string,
              requestId: string,
              collectionId: string,
              method: string,
              folderId: string,
            ) {
              handleNodeRequestDropdown(
                nodeId,
                name,
                requestId,
                collectionId,
                method,
                folderId,
              );
            },
            updateBlockName: function (field: string, value: string) {
              handleUpdateRequestData(field, value);
            },
            collectionId: dbNodes[i].data?.collectionId,
            requestId: dbNodes[i].data?.requestId,
            folderId: dbNodes[i].data?.folderId,
            requestData: dbNodes[i].data?.requestData,
            collections: filteredCollections,
            tabId: $tab.tabId,
          },
          position: {
            x: dbNodes[i].position.x,
            y: dbNodes[i].position.y,
          },
          deletable: dbNodes[i].id === "1" ? false : false,
          draggable: isNodesDraggable, // Disable dragging for this node
        });
      }
      return res;
    });
    edges.update((_edges: TFEdgeHandlerType[]) => {
      const dbEdges = $tab?.property?.testflow?.edges as TFEdgeType[];
      let res = [];
      for (let i = 0; i < dbEdges.length; i++) {
        res.push({
          id: dbEdges[i].id,
          source: dbEdges[i].source,
          target: dbEdges[i].target,
          deletable: false,
        });
      }
      return res;
    });
  });

  // Reactive statement to handle selected node updates
  $: {
    if (testflowStore || selectedNodeId) {
      let isIdExist = false;
      testflowStore?.nodes?.forEach((element: TFNodeStoreType) => {
        if (element.id === selectedNodeId) {
          selectedNode = element;
          isIdExist = true;
        }
      });
      if (!isIdExist) {
        selectedNode = undefined;
      }
    }
  }

  /**
   * The node types used in the SvelteFlow graph.
   */
  const nodeTypes = {
    startBlock: StartBlock,
    requestBlock: RequestBlock,
  } as unknown as NodeTypes;

  // Subscribe to changes in the nodes
  const nodesSubscriber = nodes.subscribe((val: Node[]) => {
    if (val && val.length) {
      onUpdateNodes(val);
    }
    nodesValue = val.length;
    // Find the node where selected is true
    let node = val.find((node: Node) => node.selected === true);

    if (node) {
      selectedBlock = node;
      selectedNodeName = (node?.data?.requestData?.name as string) || "";
      selectedNodeId = node.id;
    } else {
      (selectedNodeName = ""), (selectedNodeId = "");
    }
  });

  // Subscribe to changes in the edges
  const edgesSubscriber = edges.subscribe((val) => {
    if (val) onUpdateEdges(val);
  });

  /**
   * Updates the active tab inside the Request Body section.
   * @param tab - The tab to update.
   * @returns- The updated request navigation.
   */
  const updateActiveTabInsideRequestBody = (tab: string) => {
    if (tab === "Request Body") {
      requestNavigation = "Request Body";
    } else if (tab === "Headers") {
      requestNavigation = "Headers";
    } else {
      requestNavigation = "Parameters";
    }

    return requestNavigation;
  };

  /**
   * Updates the navigation inside the Response section.
   * @param tab - The tab to update.
   * @returns - The updated response navigation.
   */
  function updateResponseNavigation(tab: string) {
    if (tab === "Response") {
      responseNavigation = "Response";
    } else if (tab === "Headers") {
      responseNavigation = "Headers";
    }
    return responseNavigation;
  }

  /**
   * Handles the deletion of a node and its related edges by filtering
   * the `nodes` and `edges` stores, and performs necessary cleanup actions.
   * @param id - The ID of the node to delete.
   */
  const handleDeleteNode = (id: string) => {
    nodes.update((_nodes) => {
      const remainingNodes = _nodes.filter(
        (node) => Number(node.id) < Number(id),
      );
      return remainingNodes;
    });

    edges.update((_edges) => {
      const remainingEdges = _edges.filter(
        (edge) =>
          Number(edge.source) !== Number(id) &&
          Number(edge.target) < Number(id),
      );
      return remainingEdges;
    });

    deleteNodeResponse($tab.tabId, selectedNodeId);
    unselectNodes();

    isDeleteNodeModalOpen = false;
  };

  /**
   *  Count nodes with an id greater than the one being deleted
   * @param id - node id from which count starts
   */
  const countNextDeletedNode = (id: string) => {
    nodes.subscribe((_nodes) => {
      deleteCount = _nodes.filter(
        (node) => Number(node.id) > Number(id),
      ).length;
    });
  };

  /**
   * Handles key press events, preventing default behavior for "Backspace" and "Delete" keys.
   * If "Delete" is pressed, it triggers the deletion modal for the selected node.
   *
   * @param event - The key press event object.
   */
  const handleKeyPress = async (event: KeyboardEvent) => {
    // if (event.key === "Backspace") {
    //   try {
    //     if (userOS === "macos") {
    //       event.preventDefault();
    //       handleDeleteModal(selectedNodeId);
    //     }
    //   } catch (error) {
    //     console.error("Failed to determine platform:", error);
    //   }
    // }
    // if (event.key === "Delete") {
    //   debugger;
    //   event.preventDefault();
    //   handleDeleteModal(selectedNodeId);
    // }
  };

  /**
   * Unselect all the existing nodes
   */
  const unselectNodes = () => {
    selectedBlock = undefined;
    nodes.update((_nodes: Node[] | any[]) => {
      _nodes.forEach((_nodeItem) => {
        _nodeItem.selected = false;
      });
      return _nodes;
    });
  };

  /**
   * Select all the existing nodes
   */
  const selectNode = (_id: string) => {
    nodes.update((_nodes: Node[] | any[]) => {
      _nodes.forEach((_nodeItem) => {
        if (_nodeItem.id === _id) {
          _nodeItem.selected = true;
        } else {
          _nodeItem.selected = false;
        }
      });
      return _nodes;
    });
  };

  /**
   * Focuses the div element by calling its focus method.
   */
  const focusDiv = () => {
    divElement.focus();
  };

  /**
   * Handles the drag enter event and updates all nodes to set `parentDrag` to true.
   */
  const handleDragEnter = new Debounce().debounce(() => {
    nodes.update((nodes) => {
      return nodes.map((node, index, array) => ({
        ...node,
        data: {
          ...node.data,
          parentDrag: true,
        },
      }));
    });
  }, 300);

  /**
   * Handles the drag end event with a debounce of 1000 milliseconds
   * and updates all nodes to set `parentDrag` to false.
   */
  const handleDragEnd = new Debounce().debounce(() => {
    nodes.update((nodes) =>
      nodes.map((node, index, array) => ({
        ...node,
        data: {
          ...node.data,
          parentDrag: false,
        },
      })),
    );
  }, 300);

  /**
   * Cleanup function to be called when the component is destroyed.
   * Unsubscribes from `collectionsSubscriber` and invokes the cleanup
   * functions for `nodesSubscriber` and `edgesSubscriber`.
   */
  onDestroy(() => {
    collectionsSubscriber.unsubscribe();
    nodesSubscriber();
    edgesSubscriber();
  });

  onMount(() => {
    setTimeout(() => {
      sampleApiData = onRunSampleApi();
    }, 0);
  });

  const partialRun = async (_id: string, _event: string) => {
    if (!testflowStore?.isTestFlowRunning) {
      unselectNodes();
      await onClickRun(_id, _event);
      selectNode(_id);
    }
  };
  let selectedAPI: any;
  let expression: string = "";
  let selectedApiRequestType: any = "";

  const handleAddingNested = (value: string) => {
    if (selectedApiRequestType === "body") {
      expression = expression + value;
    }
  };

  $: {
    if (selectedAPI && selectedApiRequestType) {
      const data: any = selectedAPI?.requestData[selectedApiRequestType];
      if (data && selectedApiRequestType === "body") {
        // selectedRequestTypes.set(data);
      } else if (data && selectedApiRequestType === "headers") {
        // selectedRequestTypes.set(data);
      } else if (data && selectedApiRequestType === "queryParams") {
        // selectedRequestTypes.set(data);
      }
    }
  }

  // const setIsCurrentOpenFalse = () => {
  //   isDynamicExpressionContent.update((items) =>
  //     items.map((item) =>
  //       item.isCurrentOpen ? { ...item, isCurrentOpen: false } : item,
  //     ),
  //   );
  // };

  let isDynamicExpressionModalOpen = false;
</script>

<div
  class="h-100 d-flex flex-column position-relative"
  on:dragenter={(e) => {
    // Listens item enter.
    e.preventDefault();
    handleDragEnter();
  }}
  on:drop={(e) => {
    // listens item drop.
    e.preventDefault();
    handleDragEnd();
  }}
  on:dragover={(e) => {
    // Necessary to enable dropping.
    e.preventDefault();
  }}
>
  <div class="p-3" style="position:absolute; z-index:3; top:0;">
    <!-- INSERT NAME COMPONENT HERE -->
    <TestFlowName {onUpdateTestFlowName} testFlowName={$tab?.name} />
  </div>
  <div
    class="d-flex justify-content-between position-absolute p-3"
    style="top:0; ;
  right:0;
  z-index:3;"
  >
    <div class="d-flex">
      {#if testflowStore?.isTestFlowRunning}
        <div class="d-flex testing-text-container">
          <div class="loader"></div>
          <p class="testing-txt">Running</p>
        </div>
      {/if}
      <div class="run-btn" style="margin-right: 5px; position:relative;">
        {#if nodesValue > 1}
          {#if testflowStore?.isTestFlowRunning}
            <Button
              type="secondary"
              size="medium"
              startIcon={StopFilled}
              title={"Stop Flow"}
              onClick={onClickStop}
            />
          {:else}
            <Button
              type="primary"
              size="medium"
              startIcon={PlayFilled}
              title="Run"
              onClick={async () => {
                unselectNodes();
                await onClickRun();
                selectNode("2");
                MixpanelEvent(Events.Run_TestFlows);
              }}
            />
          {/if}
        {/if}

        {#if $isTestFlowTourGuideOpen && $currentStep == 6}
          <div style="position:absolute;  top:60px; right:320px">
            <TestFlowTourGuide
              targetId="run-btn"
              title="Ready, Set, Run 🏃🏻‍♂️"
              pulsePosition={{ top: "-62px", left: "260px" }}
              description={`The flow is almost ready, just waiting for you to hit 'Run' and watch the magic happen! <br/> Alternatively, you can use the "Start" play button to initiate the flow as well.`}
              tipPosition="top-right"
              onNext={async () => {
                currentStep.set(7);
              }}
              onClose={() => {
                isTestFlowTourGuideOpen.set(false);
              }}
            />
          </div>
        {/if}
      </div>
      <div style="margin-right: 5px;">
        <Tooltip title="Clear Response" placement="bottom-center" size="small">
          <Button
            type="secondary"
            size="medium"
            disable={testflowStore?.isTestFlowRunning || isTestFlowEmpty}
            startIcon={BroomRegular}
            onClick={onClearTestflow}
          />
        </Tooltip>
      </div>
      <div>
        <SaveTestflow
          isSave={$tab.isSaved}
          {isTestflowEditable}
          {onSaveTestflow}
          testFlowRunning={testflowStore?.isTestFlowRunning}
        />
      </div>
      <div class="position-relative">
        <RunHistory
          {testflowStore}
          testflowName={$tab?.name}
          {toggleHistoryDetails}
          {toggleHistoryContainer}
        />
      </div>
    </div>
  </div>
  <div
    bind:this={divElement}
    tabindex="0"
    on:keydown={handleKeyPress}
    on:click={focusDiv}
    style="flex:1; overflow:auto; outline: none; position:realtive;"
  >
    <SvelteFlow {nodes} {edges} {nodeTypes}>
      <Background
        bgColor={"var(--bg-ds-surface-900)"}
        patternColor={"var(--bg-ds-surface-500)"}
        size={4}
        gap={20}
      />
    </SvelteFlow>

    {#if $isTestFlowTourGuideOpen && $currentStep == 3}
      <div style="position:absolute; top:260px; left:265px; z-index:1000;">
        <TestFlowTourGuide
          title="One Block At A Time 🧱"
          pulsePosition={{ top: "-64px", left: "30px" }}
          description={`Wow! You’ve made it to the canvas! Now, just click 'Add Block' and you’re almost there.`}
          tipPosition="top-left"
          onNext={() => {
            currentStep.set(4);
            createNewNode("1");
          }}
          onClose={() => {
            isTestFlowTourGuideOpen.set(false);
          }}
        />
      </div>
    {/if}

    {#if $isTestFlowTourGuideOpen && $currentStep == 4}
      <div style="position:absolute; top:232px; left:638px; z-index:1000;">
        <TestFlowTourGuide
          title="Block Added! 👏 "
          description={`Now, just one more step—click on the dropdown to select an API. Don’t worry, we’ve provided a sample API in case you don’t have one ready in your collection.`}
          tipPosition="left-top"
          pulsePosition={{ top: "8px", left: "-150px" }}
          onNext={() => {
            currentStep.set(5);
          }}
          onClose={() => {
            isTestFlowTourGuideOpen.set(false);
          }}
        />
      </div>
    {/if}

    {#if $isTestFlowTourGuideOpen && $currentStep == 5}
      <div style="position:absolute; top:265px; left:632px; z-index:1000;">
        <TestFlowTourGuide
          title="Sample API waiting...⏱️"
          description={`Ready for you to get selected and move ahead! Just choose it from the dropdown and you’re good to go.`}
          tipPosition="left-top"
          pulsePosition={{ top: "10px", left: "-145px" }}
          onNext={() => {
            currentStep.set(6);
          }}
          onClose={() => {
            isTestFlowTourGuideOpen.set(false);
          }}
        />
      </div>
    {/if}
  </div>
  <!-- Open the bottom panel when it contains the data -->
  {#if selectedBlock && selectedBlock?.data?.requestId}
    <div style=" background-color: transparent; margin: 0px 13px 12px 13px;">
      <TestFlowBottomPanel
        {selectedBlock}
        {environmentVariables}
        onClose={() => unselectNodes()}
        onRedirect={onRedrectRequest}
        {handleUpdateRequestData}
        {isWebApp}
        onClearResponse={() => {}}
        {userRole}
        {onUpdateEnvironment}
        {runSingleNode}
        {testflowStore}
        {handleOpenCurrentDynamicExpression}
      />
    </div>
  {:else if $isTestFlowTourGuideOpen && $currentStep === 7}
    <div style=" background-color: transparent; margin: 0px 13px 12px 13px;">
      <!-- Request Response Nav -->
      <TestFlowBottomPanel
        selectedBlock={{
          data: {
            name: "Sample API",
            method: "GET",
            blockName: "Block 1",
            requestData: {
              name: "Sample API",
              method: "GET",
              state: {
                requestBodyLanguage: RequestDataTypeEnum.TEXT,
                requestBodyNavigation: RequestDatasetEnum.NONE,
                requestAuthNavigation: HttpRequestAuthTypeBaseEnum.NO_AUTH,
                requestNavigation: RequestSectionEnum.PARAMETERS,
                responseNavigation: ResponseSectionEnum.RESPONSE,
                responseBodyLanguage: RequestDataTypeEnum.TEXT,
                responseBodyFormatter: ResponseFormatterEnum.PRETTY,
                requestExtensionNavigation: "",
                requestLeftSplitterWidthPercentage: 50,
                requestRightSplitterWidthPercentage: 50,
                isExposeEditDescription: true,
                isSendRequestInProgress: false,
                isSaveDescriptionInProgress: false,
                isSaveRequestInProgress: false,
                isParameterBulkEditActive: false,
                isHeaderBulkEditActive: false,
                isChatbotActive: false,
                isChatbotSuggestionsActive: true,
                isChatbotGeneratingResponse: false,
                isDocGenerating: false,
                isDocAlreadyGenerated: false,
              },
              url: "https://sparrowapp.dev/api/v1/docs",
              queryParams: [
                {
                  key: "",
                  value: "",
                  checked: false,
                },
              ],
              headers: [
                {
                  key: "",
                  value: "",
                  checked: false,
                },
              ],
            },
          },
        }}
        {environmentVariables}
        onClose={() => unselectNodes()}
        onRedirect={onRedrectRequest}
        {handleUpdateRequestData}
        {isWebApp}
        onClearResponse={() => {}}
        {userRole}
        {onUpdateEnvironment}
      />
    </div>
  {/if}

  <div class="p-3" style="position:absolute; z-index:3; bottom:0; right:0;">
    <p
      class="mb-0 pb-0 text-fs-14"
      style="color: var(--text-primary-300); font-weight:500; cursor:pointer;  "
      on:click={() => {
        currentStep.set(1);
        isTestFlowTourGuideOpen.set(true);
      }}
    >
      Need help?
    </p>
  </div>
</div>
<!-- <svelte:window on:keydown={handleKeyPress} /> -->

<Modal
  title={"Insert Dynamic Content"}
  type={"dark"}
  width={"851px"}
  zIndex={1000}
  isOpen={isDynamicExpressionModalOpen}
  handleModalState={() => {
    isDynamicExpressionModalOpen = false;
  }}
>
  <TestflowDynamicExpression
    {dynamicExpressionEditorContent}
    requestApis={$nodes}
    {onInsertExpression}
    {handleAddingNested}
    {environmentVariables}
    {onPreviewExpression}
  />
</Modal>

<Modal
  title={"Delete block?"}
  type={"dark"}
  width={"540px"}
  zIndex={1000}
  isOpen={isDeleteNodeModalOpen}
  handleModalState={(flag = false) => {
    isDeleteNodeModalOpen = flag;
  }}
>
  <DeleteNode
    {deletedNodeId}
    {deleteNodeName}
    {handleDeleteNode}
    {deleteCount}
    handleModalState={(flag = false) => {
      isDeleteNodeModalOpen = flag;
    }}
  />
</Modal>

<Modal
  title={"New Request"}
  type={"dark"}
  width={"540px"}
  zIndex={1000}
  isOpen={isAddCustomRequestModalOpen}
  handleModalState={(flag = false) => {
    isAddCustomRequestModalOpen = flag;
  }}
>
  <CustomRequest
    handleModalState={(flag = false) => {
      isAddCustomRequestModalOpen = flag;
    }}
    {handleCreateCustomRequest}
  />
</Modal>

<Modal
  title={"Unsaved Changes Detected"}
  type={"dark"}
  width={"540px"}
  zIndex={1000}
  isOpen={isSwitchNodeRequestModalOpen}
  handleModalState={(flag = false) => {
    isSwitchNodeRequestModalOpen = flag;
  }}
>
  <SaveNode
    requestName={unsavedChangesModal.requestName}
    blockName={unsavedChangesModal.blockName}
    handleModalState={(flag = false) => {
      isSwitchNodeRequestModalOpen = flag;
    }}
    onSaveRequest={async () => {
      await updateNodeRequest(
        updateNodeId,
        updateNodeName,
        updateNodeRequestId,
        updateNodeCollectionId,
        updateNodeMethod,
        updateNodeFolderId,
        updateNodeUrl,
      );
      isSwitchNodeRequestModalOpen = false;
    }}
  />
</Modal>

<style>
  :global(.svelte-flow__attribution) {
    display: none;
  }
  .loader {
    color: var(--bg-primary-300);
    width: 2px;
    aspect-ratio: 1;
    border-radius: 100%;
    box-shadow:
      9px 0 0 4px,
      18px 0 0 2px,
      27px 0 0 0;
    transform: translateX(-40px);
    animation: l21 0.5s infinite alternate linear;
  }

  @keyframes l21 {
    50% {
      box-shadow:
        9px 0 0 2px,
        18px 0 0 4px,
        27px 0 0 2px;
    }
    100% {
      box-shadow:
        9px 0 0 0,
        18px 0 0 2px,
        27px 0 0 4px;
    }
  }

  .request-rhs-container {
    height: 100%;
    overflow: auto;
    width: calc(100% - 190px);
  }

  .request-container {
    /* background-color: var(--bg-secondary-800); */
    width: 100%;
  }
  .testing-txt {
    color: var(--text-primary-300);
    font-size: 14;
    font-weight: 400;
    align-self: center;
    align-content: center;
    margin-top: 15%;
    margin-right: 6px;
  }
  .testing-text-container {
    align-items: center;
    justify-content: flex-end;
    height: 36px;
    background-color: var(--bg-tertiary-750);
    width: 110px;
    margin-right: 6px;
    padding-left: 12px;
    border-radius: 4px;
  }
</style>
