export enum Events {
  USER_LOGIN = "User_Login",
  USER_SIGNUP = "User_Signup",
  CREATE_COLLECTION = "Create_Collection",
  ADD_NEW_API_REQUEST = "Add_New_API_Request",
  IMPORT_COLLECTION = "Import_Collection",
  GLOBAL_SEARCH = "Global_Search",
  SEND_API_REQUEST = "Send_API_Request",
  SAVE_API_REQUEST = "Save_API_Request",
  COPY_API_RESPONSE = "Copy_API_Response",
  DOWNLOAD_API_RESPONSE = "Download_API_Response",
  CLEAR_API_RESPONSE = "Clear_API_Response",
  SAVE_API_DOCUMENTATION = "Save_API_Documentation",
  CHANGE_DEFAULT_VIEW = "Change_Default_View",
  ENVIRONMENT_SIDE_PANEL = "Environment_Side_Panel",
  SAVE_GLOBAL_ENVIRONMENT_VARIABLES = "Save_Global_Environment_Variables",
  CREATE_LOCAL_ENVIRONMENT = "Create_Local_Environment",
  SAVE_LOCAL_ENVIRONMENT_VARIABLES = "Save_Local_Environment_Variables",
  SEARCH_ENVIRONMENT_VARIABLES = "Search_Environment_Variables",
}
