<script lang="ts">
  import { Splitpanes, Pane } from "svelte-splitpanes";

  import Button from "$lib/components/buttons/Button.svelte";
  import Input from "$lib/components/inputs/Input.svelte";

  import floppyDisk from "$lib/assets/floppy-disk.svg";

  import {
    HttpUrlSection,
    RequestHeaders,
    ResponsePane,
    RequestNavigator,
    ResponseNavigator,
    RequestAuth,
  } from "$features/rest-explorer";

  import RestExplorerViewModel from "./RestExplorer.ViewModel";
  import { RequestSection } from "$lib/utils/enums";

  const _viewModel = new RestExplorerViewModel();
  let response = _viewModel.response;
  let requestState = _viewModel.requestState;
  let environmentVariables = [];

  const handleRequestNavigator = (event: CustomEvent<string>): void => {
    _viewModel.updateRequestState({ section: event.detail });
  };

  const handleRequestAuth = (event: CustomEvent<string>): void => {
    _viewModel.updateRequestState({ auth: event.detail });
  };
</script>

<div class="w-100 d-flex flex-column h-100">
  <!-- Request Name Header -->
  <div class="d-flex justify-content-between w-100 p-3">
    <Input
      value="New Request"
      noBackground={true}
      inputStyleProp="font-size: 1.5rem; font-weight: 500;"
      class="flex-1"
    />
    <!-- Save and Share Buttons -->
    <div class="d-flex justify-content-between">
      <Button
        title="Save Request"
        type="dark"
        buttonClassProp="ms-2"
        buttonStartIcon={floppyDisk}
      />
      <Button title="Share" type="dark" buttonClassProp="ms-2" />
    </div>
  </div>

  <!-- HTTP URL Section -->
  <HttpUrlSection
    class="py-1 px-3"
    bind:requestUrl={_viewModel.requestUrl}
    bind:httpMethod={_viewModel.httpMethod}
    onSendButtonClicked={_viewModel.sendRequest}
    onUpdateRequestUrl={_viewModel.updateRequestUrl}
    onUpdateRequestMethod={_viewModel.updateRequestMethod}
  />

  <Splitpanes class="h-100" dblClickSplitter={false}>
    <Pane>
      <!-- Request Pane -->
      <!-- <RequestPane /> -->
      <RequestNavigator
        requestStateSection={$requestState?.section}
        on:change={handleRequestNavigator}
      />
      <div class="d-flex align-items-center justify-content-start ps-4">
        {#if $requestState?.section === RequestSection.PARAMETERS}
          parameters
        {:else if $requestState?.section === RequestSection.REQUEST_BODY}
          requestbody
        {:else if $requestState?.section === RequestSection.HEADERS}
          <RequestHeaders
            bind:headers={_viewModel.requestHeaders}
            bind:autoGeneratedHeaders={_viewModel.requestAutoGeneratedHeaders}
            onHeadersChange={_viewModel.updateHeaders}
            onAutoGeneratedHeadersChange={_viewModel.updateAutoGeneratedHeaders}
          />
        {:else if $requestState?.section === RequestSection.AUTHORIZATION}
          <RequestAuth
            requestStateAuth={$requestState?.auth}
            on:change={handleRequestAuth}
            auth={_viewModel.requestAuth}
            onUpdateRequestAuth={_viewModel.updateRequestAuth}
          />
        {/if}
      </div>
    </Pane>
    <Pane>
      <!-- Response Pane -->
      <ResponseNavigator />
      <ResponsePane response={$response} />
    </Pane>
  </Splitpanes>
</div>

<style></style>
