<script lang="ts">
  import penIcon from "$lib/assets/pen.svg";
  import Headers from "../request-header-section/Headers.svelte";
  import RequestBody from "../request-body-section/RequestBody.svelte";
  import Authorization from "../request-authorization-section/Authorization.svelte";

  import Parameters from "../request-parameter-section/Parameters.svelte";
  import Loader from "$lib/components/Transition/Loader.svelte";

  import {
    bottomPanelHeight,
    collapsibleState,
    isHorizontal,
    leftPanelWidth,
    rightPanelWidth,
    topPanelHeight,
  } from "$lib/store/request-response-section";
  import ResponseParams from "../response-body-section/ResponseParams.svelte";
  import DefaultPage from "../response-body-section/DefaultPage.svelte";

  import { onDestroy, onMount } from "svelte";
  import ResponseError from "../response-error/ResponseError.svelte";
  import { RequestSection } from "$lib/utils/enums/request.enum";
  import {
    findAuthHeader,
    findAuthParameter,
  } from "$lib/utils/helpers/auth.helper";
  import { createDeepCopy } from "$lib/utils/helpers/conversion.helper";
  import type { CollectionsMethods } from "$lib/utils/interfaces/collections.interface";
  import type { NewTab } from "$lib/utils/interfaces/request.interface";
  import { Pane, Splitpanes } from "svelte-splitpanes";

  export let activeTab;
  export let collectionsMethods: CollectionsMethods;
  export let environmentVariables;

  let isHorizontalMode: boolean;
  let selectedTab: string = "";
  let rightPanelWidthSize: number;
  let leftPanelWidthSize: number;
  let topPanelHeightSize: number;
  let bottomPanelHeightSize: number;
  let progress: boolean = false;
  let isCollaps: boolean = false;
  let headersCount: number | string = 0;
  let parametersCount: number | string = 0;
  let response;
  let request;
  let pencilIconState: boolean = false;
  let apiState;
  let currentTabId: string = "";

  const tabSubscribe = activeTab.subscribe((event: NewTab) => {
    if (event) {
      currentTabId = event.id;
      apiState = event?.property?.request?.state;
      selectedTab = event?.property?.request?.state.section;
      progress = event?.property?.request?.requestInProgress;
      request = event?.property?.request;

      response = event?.property?.request?.response;
      headersCount =
        request?.autoGeneratedHeaders?.length + request?.headers?.length - 1;
      parametersCount = request?.queryParams?.length - 1;
      pencilIconState = false;

      // Triggers active auth header
      if (
        request &&
        (findAuthHeader(request).key || findAuthHeader(request).value)
      ) {
        headersCount += 1;
        pencilIconState = true;
      }

      // Triggers active auth query parameters
      if (
        request &&
        (findAuthParameter(request).key || findAuthParameter(request).value)
      ) {
        parametersCount += 1;
        pencilIconState = true;
      }
    }
  });

  const isHorizontalUnsubscribe = isHorizontal.subscribe((value) => {
    isHorizontalMode = value;
    stylePanes();
  });

  const rightPanelWidthSubscribe = rightPanelWidth.subscribe((value) => {
    rightPanelWidthSize = value;
  });
  const leftPanelWidthSubscribe = leftPanelWidth.subscribe((value) => {
    leftPanelWidthSize = value;
  });
  const topPanelHeightSubscribe = topPanelHeight.subscribe((value) => {
    topPanelHeightSize = value;
  });
  const bottomPanelHeightSubscribe = bottomPanelHeight.subscribe((value) => {
    bottomPanelHeightSize = value;
  });

  collapsibleState.subscribe((value) => {
    isCollaps = value;
  });

  onDestroy(() => {
    leftPanelWidthSubscribe();
    rightPanelWidthSubscribe();
    topPanelHeightSubscribe();
    bottomPanelHeightSubscribe();
    isHorizontalUnsubscribe();
    tabSubscribe();
  });
  const handleKeyPress = (event) => {
    if (event.altKey && event.code === "KeyP") {
      collectionsMethods.updateRequestState(
        RequestSection.PARAMETERS,
        "section",
      );
    } else if (event.altKey && event.code === "KeyH") {
      collectionsMethods.updateRequestState(RequestSection.HEADERS, "section");
    } else if (event.altKey && event.code === "KeyB") {
      collectionsMethods.updateRequestState(
        RequestSection.REQUEST_BODY,
        "section",
      );
    }
  };
  onMount(() => {
    const splitter = document.querySelector(".splitpanes__splitter");
    const leftPanel = document.getElementsByClassName("left-panel");
    const rightPanel = document.getElementsByClassName("right-panel");
    if (splitter && leftPanel && rightPanel) {
      splitter.addEventListener("mousedown" || "mouseover", () => {
        splitter.style.border = "solid #1193f0";
        splitter.style.cursor = isHorizontalMode ? "row-resize" : "col-resize";
        if (
          isHorizontalMode &&
          leftPanel[0].style.height &&
          rightPanel[0].style.height
        ) {
          topPanelHeight.set(parseInt(leftPanel[0].style.height));
          bottomPanelHeight.set(parseInt(rightPanel[0].style.height));
          topPanelHeight.subscribe((value) => {
            topPanelHeightSize = value;
          });
          bottomPanelHeight.subscribe((value) => {
            bottomPanelHeightSize = value;
          });
        } else if (
          !isHorizontalMode &&
          leftPanel[0].style.width &&
          rightPanel[0].style.width
        ) {
          leftPanelWidth.set(parseInt(leftPanel[0].style.width));
          rightPanelWidth.set(parseInt(rightPanel[0].style.width));
          leftPanelWidth.subscribe((value) => {
            leftPanelWidthSize = value;
          });
          rightPanelWidth.subscribe((value) => {
            rightPanelWidthSize = value;
          });
        }
      });
      window.addEventListener("mouseup", () => {
        splitter.style.border = "solid #313233";
      });
    }
  });
  function stylePanes() {
    rightPanelWidth.subscribe((value) => {
      rightPanelWidthSize = value;
    });
    leftPanelWidth.subscribe((value) => {
      leftPanelWidthSize = value;
    });
    topPanelHeight.subscribe((value) => {
      topPanelHeightSize = value;
    });
    bottomPanelHeight.subscribe((value) => {
      bottomPanelHeightSize = value;
    });

    const splitter = document.querySelector(".splitpanes__splitter");
    if (splitter && isHorizontalMode) {
      splitter.style.border = "solid #313233";
      splitter.style.height = "0%";
      splitter.style.width = "100%";
    } else if (splitter && !isHorizontalMode) {
      splitter.style.border = "solid #313233";
      splitter.style.height = "85vh";
      splitter.style.width = "2px";
    }
  }
</script>

<Splitpanes
  style={isHorizontal && "height: 78vh; "}
  on:ready={stylePanes}
  theme=""
  class="d-flex align-items-start {isHorizontalMode
    ? 'flex-column'
    : 'flex-row'} justify-content-between w-100"
  horizontal={isHorizontalMode ? true : false}
  dblClickSplitter={false}
>
  <Pane
    class="left-panel d-flex flex-column align-items-top overflow-y-auto pt-3 ps-4 pe-2"
    minSize={35}
    size={isHorizontalMode ? topPanelHeightSize : leftPanelWidthSize}
  >
    <div
      class="{isCollaps
        ? 'ps-2 pt-2 pe-5'
        : 'pt-1 ps-1 pe-5'} d-flex align-items-start text-requestBodyColor"
    >
      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            collectionsMethods.updateRequestState(
              RequestSection.PARAMETERS,
              "section",
            );
          }}
          role="button"
          tabindex="0"
          on:keydown={() => {}}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.PARAMETERS}
          >Parameters
          <p style="font-size: 12px;" class="mb-0 text-labelColor ps-1">
            ({parametersCount})
          </p>
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            collectionsMethods.updateRequestState(
              RequestSection.REQUEST_BODY,
              "section",
            );
          }}
          role="button"
          tabindex="0"
          on:keydown={() => {}}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.REQUEST_BODY}
        >
          Body
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            collectionsMethods.updateRequestState(
              RequestSection.HEADERS,
              "section",
            );
          }}
          role="button"
          tabindex="0"
          on:keydown={() => {}}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.HEADERS}
          >Headers
          <p style="font-size: 12px;" class="mb-0 text-labelColor ps-1">
            ({headersCount})
          </p>
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center gap-1 text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            collectionsMethods.updateRequestState(
              RequestSection.AUTHORIZATION,
              "section",
            );
          }}
          role="button"
          tabindex="0"
          on:keydown={() => {}}
          class="team-menu__link d-flex pb-1 gap-1 align-items-center"
          class:tab-active={selectedTab === RequestSection.AUTHORIZATION}
          >Authorization
          {#if pencilIconState}
            <img src={penIcon} alt="penIcon" class="w-100 h-100" />
          {/if}
        </span>
      </span>
    </div>
    <div class="d-flex align-items-center justify-content-start">
      {#if selectedTab === RequestSection.PARAMETERS}
        <Parameters
          request={createDeepCopy(request)}
          params={createDeepCopy(request.queryParams)}
          url={createDeepCopy(request.url)}
          {currentTabId}
          {collectionsMethods}
          {environmentVariables}
        />
      {:else if selectedTab === RequestSection.REQUEST_BODY}
        <RequestBody {activeTab} {collectionsMethods} {environmentVariables} />
      {:else if selectedTab === RequestSection.HEADERS}
        <Headers
          request={createDeepCopy(request)}
          {collectionsMethods}
          {currentTabId}
          {environmentVariables}
        />
      {:else if selectedTab === RequestSection.AUTHORIZATION}
        <Authorization
          request={createDeepCopy(request)}
          {collectionsMethods}
          {environmentVariables}
        />
      {/if}
    </div>
  </Pane>

  <Pane
    class="right-panel pt-3 px-4 position-relative overflow-y-auto"
    minSize={35}
    size={isHorizontalMode ? bottomPanelHeightSize : rightPanelWidthSize}
  >
    <div class=" d-flex flex-column">
      {#if !response?.status}
        <DefaultPage />
      {:else if response?.status === "Not Found"}
        <ResponseError />
      {:else if response?.status}
        <ResponseParams
          {apiState}
          {collectionsMethods}
          {response}
          {currentTabId}
        />
      {/if}
      {#if progress}
        <div
          class="position-absolute"
          style="    
          top: 10px;
          left: 0;
          right: 0;
          bottom: 0;
          z-index:3;"
        >
          <Loader />
        </div>
      {/if}
    </div>
  </Pane>
</Splitpanes>
<svelte:window on:keydown={handleKeyPress} />

<style>
  .team-menu__link {
    color: #8a9299;
  }

  .tab-active {
    color: white;

    border-bottom: 3px solid var(--send-button);
  }
  .cursor-pointer {
    cursor: pointer;
  }
  .border-left {
    border-left: 1px solid var(--border-color);
  }
  .border-top {
    border-top: 1px solid var(--border-color);
  }
</style>
