<script lang="ts">
  import penIcon from "$lib/assets/pen.svg";
  import Headers from "../request-header-section/Headers.svelte";
  import RequestBody from "../request-body-section/RequestBody.svelte";
  import Authorization from "../request-authorization-section/Authorization.svelte";

  import Parameters from "../request-parameter-section/Parameters.svelte";
  import Loader from "$lib/components/Transition/Loader.svelte";

  import {
    collapsibleState,
    currentTab,
    handleRequestStateChange,
    isHorizontalVertical,
    tabs,
  } from "$lib/store/request-response-section";
  import ResponseParams from "../response-body-section/ResponseParams.svelte";
  import DefaultPage from "../response-body-section/DefaultPage.svelte";

  import { onDestroy } from "svelte";
  import ResponseError from "../response-error/ResponseError.svelte";
  import type { NewTab } from "$lib/utils/interfaces/request.interface";
  import { RequestSection } from "$lib/utils/enums/request.enum";
  import {
    findAuthHeader,
    findAuthParameter,
  } from "$lib/utils/helpers/auth.helper";
  import { createDeepCopy } from "$lib/utils/helpers/conversion.helper";
  import type { Observable } from "rxjs";
  import type { TabDocument } from "$lib/database/app.database";
  import { RequestParamViewModel } from "./RequestParam.ViewModel";

  let isHorizontalVerticalMode: boolean;
  let selectedTab: string = "";
  let currentTabId: string = "";
  let tabList: NewTab[] = [];
  let progress: boolean = false;
  let responseBody;
  let responseHeader;
  let requestData: NewTab;
  let isCollaps: boolean = false;
  let headersCount: number | string = 0;
  let parametersCount: number | string = 0;
  let statusCode: string;
  let timeTaken: number;
  let sizeinKb: number;
  let request;
  const _viewModel = new RequestParamViewModel();
  const tab: Observable<TabDocument> = _viewModel.tab;

  const tabSubscribe = tab.subscribe((event: TabDocument) => {
    selectedTab = event?.get("property").request.state.section;
    progress = event?.get("property").request.requestInProgress;
    request = event?.get("property").request;
    //////////////////////////// response
    statusCode = event?.get("property").request?.response?.status;
          timeTaken = event?.get("property").request.response.time;
          sizeinKb = event?.get("property").request.response.size;
          responseBody = event?.get("property").request?.response?.body;
          responseHeader = Object.entries(
            JSON.parse(event?.get("property").request?.response?.headers || "{}"),
          );
  });

  const isHorizontalVerticalUnsubscribe = isHorizontalVertical.subscribe(
    (value) => {
      isHorizontalVerticalMode = value;
    },
  );

  collapsibleState.subscribe((value) => {
    isCollaps = value;
  });

  const fetchComponentData = (id: string, list: NewTab[]) => {
    list.forEach((elem: NewTab) => {
      if (elem.id === id) {
        requestData = elem;
      
        headersCount =
          request.autoGeneratedHeaders.length +
          request.headers.length -
          1;
        parametersCount = request.queryParams.length - 1;

        if (findAuthHeader(request).key) {
          headersCount += 1;
        }

        if (findAuthParameter(request).key) {
          parametersCount += 1;
        }

        if (elem.request?.response) {
          // statusCode = elem.request?.response?.status;
          // timeTaken = elem.request.response.time;
          // sizeinKb = elem.request.response.size;
          // responseBody = elem.request?.response?.body;
          // responseHeader = Object.entries(
          //   JSON.parse(elem.request?.response?.headers || "{}"),
          // );
        } 
      }
    });
  };

  const tabsUnsubscribe = tabs.subscribe((value) => {
    tabList = value;
    if (currentTabId && tabList) {
      fetchComponentData(currentTabId, tabList);
    }
  });

  const currentTabUnsubscribe = currentTab.subscribe((value) => {
    if (value && value.id) {
      currentTabId = value.id;
      if (currentTabId && tabList) {
        fetchComponentData(currentTabId, tabList);
      }
    }
  });

  onDestroy(() => {
    currentTabUnsubscribe();
    tabsUnsubscribe();
    isHorizontalVerticalUnsubscribe();
    tabSubscribe.unsubscribe();
  });
</script>

<div
  class="d-flex align-items-start {isHorizontalVerticalMode
    ? 'flex-column'
    : 'flex-row'} justify-content-between w-100"
>
  <div
    class="right-panel d-flex flex-column align-items-top justify-content-center pt-3 ps-4 pe-2"
    style="width:{isHorizontalVerticalMode ? '100%' : '50%'}; "
  >
    <div
      class="{isCollaps
        ? 'ps-2 pt-2 pe-5'
        : 'pt-1 ps-1 pe-5'} d-flex align-items-start text-requestBodyColor"
    >
      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            _viewModel.updateRequestState(RequestSection.PARAMETERS ,"section");
          }}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.PARAMETERS}
          >Parameters
          <p style="font-size: 12px;" class="mb-0 text-labelColor ps-1">
            ({parametersCount})
          </p>
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            _viewModel.updateRequestState(RequestSection.REQUEST_BODY ,"section");
          }}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.REQUEST_BODY}
          >Request Body
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            _viewModel.updateRequestState(RequestSection.HEADERS ,"section");
          }}
          class="team-menu__link d-flex pb-1"
          class:tab-active={selectedTab === RequestSection.HEADERS}
          >Headers
          <p style="font-size: 12px;" class="mb-0 text-labelColor ps-1">
            ({headersCount})
          </p>
        </span>
      </span>

      <span
        style="font-size: 12px;font-weight:500; margin-right:15px;"
        class="cursor-pointer d-flex align-items-center justify-content-center gap-1 text-requestBodyColor text-decoration-none"
        ><span
          on:click={() => {
            _viewModel.updateRequestState(RequestSection.AUTHORIZATION ,"section");
          }}
          class="team-menu__link d-flex pb-1 gap-1 align-items-center"
          class:tab-active={selectedTab === RequestSection.AUTHORIZATION}
          >Authorization <img src={penIcon} alt="penIcon" class="w-100 h-100" />
        </span>
      </span>
    </div>
    <div class="d-flex align-items-center justify-content-start">
      {#if selectedTab === RequestSection.PARAMETERS}
        <Parameters
          request={createDeepCopy(request)}
          params={createDeepCopy(request.queryParams)}
          url={createDeepCopy(request.url)}
          {currentTabId}
        />
      {:else if selectedTab === RequestSection.REQUEST_BODY}
        <RequestBody />
      {:else if selectedTab === RequestSection.HEADERS}
        <Headers request={createDeepCopy(request)}/>
      {:else if selectedTab === RequestSection.AUTHORIZATION}
        <Authorization
          request={createDeepCopy(request)}
        />
      {/if}
    </div>
  </div>

  <div
    style="width:{isHorizontalVerticalMode
      ? '100%'
      : '50%'};border-left:1px solid #313233; height:calc(100vh - 200px);"
    class="left-panel pt-3 px-4 position-relative"
  >
    <div class=" d-flex flex-column" style="height:100%;">
      {#if !statusCode}
        <DefaultPage />
      {:else if statusCode === "Not Found"}
        <ResponseError/>
      {:else if statusCode}
        <ResponseParams
          {responseBody}
          {responseHeader}
          {statusCode}
          {timeTaken}
          {sizeinKb}
        />
      {/if}

      {#if progress}
        <div
          class="position-absolute"
          style="    
          top: 10px;
          left: 0;
          right: 0;
          bottom: 0;
          z-index:999;"
        >
          <Loader />
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .team-menu__link {
    color: #8a9299;
  }

  .tab-active {
    color: white;

    border-bottom: 3px solid #85c2ff;
  }
  .cursor-pointer {
    cursor: pointer;
  }
</style>
