<script lang="ts">
  // ---- Assets
  import floppyDisk from "$lib/assets/floppy-disk.svg";
  import angleDown from "$lib/assets/angle-down.svg";

  // ---- Components
  import {
    HttpUrlSection,
    RequestHeaders,
    RequestNavigator,
    ResponseNavigator,
    RequestAuth,
    ResponseDefaultScreen,
    ResponseErrorScreen,
    ResponseHeaders,
    ResponseBodyNavigator,
    RequestBody,
    RequestName,
    ResponseBody,
    RestExtensionPanel,
    SaveAsRequest,
    RequestParameters,
  } from "@workspaces/features/rest-explorer/components";
  import Loader from "$lib/components/Transition/loader/Loader.svelte";
  import { ModalWrapperV1 } from "$lib/components";
  import Dropdown from "$lib/components/dropdown/Dropdown.svelte";
  import { notifications } from "$lib/components/toast-notification/ToastNotification";
  import { Splitpanes, Pane } from "svelte-splitpanes";
  import Button from "$lib/components/buttons/Button.svelte";

  // ---- types
  import { RequestSection, ResponseSection } from "$lib/utils/enums";
  import type {
    Auth,
    Body,
    KeyValuePair,
    Path,
    Response,
    State,
  } from "$lib/utils/interfaces/request.interface";
  import type {
    CollectionDocument,
    TabDocument,
    WorkspaceDocument,
  } from "$lib/database/app.database";
  import type { Observable } from "rxjs";

  export let tab: Observable<TabDocument>;
  export let collections: Observable<CollectionDocument[]>;
  export let requestAuthHeader: Observable<KeyValuePair>;
  export let requestAuthParameter: Observable<KeyValuePair>;
  export let onUpdateRequestUrl: (
    url: string,
    effectQueryParams?: boolean,
  ) => void;
  export let onSendRequest: () => void;
  export let onUpdateRequestMethod: (method: string) => void;
  export let onUpdateRequestParams: (
    params: KeyValuePair[],
    effectURL?: boolean,
  ) => void;
  export let onUpdateRequestName: (name: string) => void;
  export let onUpdateRequestBody: (body: Body) => void;
  export let onUpdateRequestAuth: (auth: Auth) => void;
  export let onUpdateHeaders: (headers: KeyValuePair[]) => void;
  export let onUpdateAutoGeneratedHeaders: (headers: KeyValuePair[]) => void;
  export let onUpdateRequestState: (state: State) => void;
  export let onClearResponse: () => Promise<void>;
  export let onSaveRequest: (
    saveDescriptionOnly?: boolean,
  ) => Promise<{ status: string; message?: string }>;
  export let onUpdateRequestDescription: (description: string) => void;
  export let readRequestOrFolderInCollection: (
    collectionId: string,
    uuid: string,
  ) => Promise<object>;
  export let readCollection: (uuid: string) => Promise<CollectionDocument>;
  export let readWorkspace: (uuid: string) => Promise<WorkspaceDocument>;
  export let onSaveAsRequest: (
    workspaceMeta: { id: string; name: string },
    path: { name: string; id: string; type: string }[],
    tabName: string,
    description: string,
    type: string,
  ) => Promise<
    { status: string; message?: string; data?: { id: string } } | unknown
  >;
  export let onCreateFolder: (
    workspaceMeta: { id: string; name: string },
    collectionId: string,
    folderName: string,
  ) => Promise<{ status: string; data?: object; message?: string }>;
  export let onCreateCollection: (
    workspaceMeta: { id: string; name: string },
    collectionName: string,
  ) => Promise<{ status: string; data?: object; message?: string }>;

  let isExposeSaveAsRequest = false;
</script>

{#if $tab.tabId}
  <div class="d-flex">
    <div class="w-100 d-flex flex-column h-100">
      <!-- Request Name Header -->
      <div class="d-flex justify-content-between w-100 p-3">
        <RequestName name={$tab.name} {onUpdateRequestName} />
        <!-- Save and Share Buttons -->
        <div class="d-flex justify-content-between">
          <Button
            title="Save Request"
            type="dark"
            loader={false}
            buttonClassProp="ms-2"
            buttonStartIcon={floppyDisk}
            onClick={async () => {
              const x = await onSaveRequest();
              if (
                x.status === "error" &&
                x.message ===
                  "request is not a part of any workspace or collection"
              ) {
                isExposeSaveAsRequest = true;
              } else if (x.status === "success") {
                notifications.success("API request saved");
              }
            }}
          />

          <span class="position-relative" style="width:35px;">
            <Dropdown
              disabled={false}
              dropdownId={"saveAsDropdown"}
              dropDownType={{ type: "img", title: angleDown }}
              data={[
                {
                  name: "Save As",
                  id: "collection",
                  dynamicClasses: "text-whiteColor",
                },
              ]}
              onclick={() => {
                isExposeSaveAsRequest = true;
              }}
              staticCustomStyles={[
                {
                  id: "saveAsDropdown-options-container",
                  styleKey: "minWidth",
                  styleValue: "180px",
                },
              ]}
              staticClasses={[
                {
                  id: "saveAsDropdown-img",
                  classToAdd: ["btn", "bg-dullBackground", "px-2", "py-1"],
                },
                {
                  id: "saveAsDropdown-options-name",
                  classToAdd: ["fs-6"],
                },
                {
                  id: "saveAsDropdown-options-container",
                  classToAdd: ["end-0", "mt-1", "rounded"],
                },
              ]}
            ></Dropdown>
          </span>
          <Button
            title="Share"
            type="dark"
            buttonClassProp="ms-2"
            onClick={() => {}}
          />
        </div>
      </div>

      <!-- HTTP URL Section -->
      <HttpUrlSection
        class="py-1 px-3"
        requestUrl={$tab.property.request?.url}
        httpMethod={$tab.property.request?.method}
        splitterDirection={$tab.property.request?.state
          ?.requestSplitterDirection}
        onSendButtonClicked={onSendRequest}
        {onUpdateRequestUrl}
        {onUpdateRequestMethod}
        {onUpdateRequestState}
      />

      <Splitpanes
        class=""
        id={"rest-splitter"}
        style="height: calc(100vh - 240px); margin-top:10px;"
        horizontal={$tab.property.request?.state?.requestSplitterDirection ===
        "horizontal"
          ? true
          : false}
        dblClickSplitter={false}
        on:resize={(e) => {
          onUpdateRequestState({
            requestLeftSplitterWidthPercentage: e.detail[0].size,
          });
          onUpdateRequestState({
            requestRightSplitterWidthPercentage: e.detail[1].size,
          });
        }}
      >
        <Pane
          minSize={30}
          size={$tab.property.request?.state
            ?.requestLeftSplitterWidthPercentage}
        >
          <!-- Request Pane -->
          <div class="px-3 pb-3 h-100 position-relative">
            <RequestNavigator
              requestStateSection={$tab.property.request?.state
                ?.requestNavigation}
              {onUpdateRequestState}
            />
            {#if $tab.property.request?.state?.requestNavigation === RequestSection.PARAMETERS}
              <RequestParameters
                params={$tab.property.request.queryParams}
                {onUpdateRequestParams}
                authParameter={$requestAuthParameter}
              />
            {:else if $tab.property.request?.state?.requestNavigation === RequestSection.REQUEST_BODY}
              <RequestBody
                body={$tab.property.request.body}
                method={$tab.property.request.method}
                requestState={$tab.property.request.state}
                {onUpdateRequestBody}
                {onUpdateRequestState}
              />
            {:else if $tab.property.request?.state?.requestNavigation === RequestSection.HEADERS}
              <RequestHeaders
                headers={$tab.property.request.headers}
                autoGeneratedHeaders={$tab.property.request
                  .autoGeneratedHeaders}
                authHeader={$requestAuthHeader}
                onHeadersChange={onUpdateHeaders}
                onAutoGeneratedHeadersChange={onUpdateAutoGeneratedHeaders}
              />
            {:else if $tab.property.request?.state?.requestNavigation === RequestSection.AUTHORIZATION}
              <RequestAuth
                requestStateAuth={$tab.property.request.state
                  .requestAuthNavigation}
                {onUpdateRequestState}
                auth={$tab.property.request.auth}
                {onUpdateRequestAuth}
              />
            {/if}
          </div>
        </Pane>
        <Pane
          minSize={30}
          size={$tab.property.request?.state
            ?.requestRightSplitterWidthPercentage}
          class="position-relative"
        >
          <!-- Response Pane -->
          <div class="d-flex flex-column h-100 px-3">
            {#if $tab.property.request?.state?.isSendRequestInProgress}
              <ResponseDefaultScreen />
              <div
                style="top: 10px; left: 0; right: 0; bottom: 0; z-index:3; position:absolute;"
              >
                <Loader loaderSize={"80px"} />
              </div>
            {:else if !$tab.property.request?.response?.status}
              <ResponseDefaultScreen />
            {:else if $tab.property.request?.response?.status === "Not Found"}
              <ResponseErrorScreen />
            {:else if $tab.property.request?.response?.status}
              <ResponseNavigator
                requestStateSection={$tab.property.request.state
                  ?.responseNavigation}
                {onUpdateRequestState}
              />
              {#if $tab.property.request.state?.responseNavigation === ResponseSection.RESPONSE}
                <ResponseBodyNavigator
                  response={$tab.property.request.response}
                  apiState={$tab.property.request.state}
                  {onUpdateRequestState}
                  {onClearResponse}
                />
                <ResponseBody
                  response={$tab.property.request.response}
                  apiState={$tab.property.request.state}
                />
              {:else if $tab.property.request.state?.responseNavigation === ResponseSection.HEADERS}
                <ResponseHeaders
                  responseHeader={$tab.property.request.response.headers}
                />
              {/if}
            {/if}
          </div></Pane
        >
      </Splitpanes>
    </div>
    <div>
      <RestExtensionPanel
        state={$tab.property.request?.state}
        requestMethod={$tab.property.request?.method}
        requestUrl={$tab.property.request?.url}
        requestName={$tab.name}
        requestDescription={$tab.description}
        requestPath={$tab.path}
        collections={$collections}
        {onSaveRequest}
        {readCollection}
        {readWorkspace}
        {onSaveAsRequest}
        {onCreateFolder}
        {onCreateCollection}
        {onUpdateRequestState}
        {onUpdateRequestDescription}
        {readRequestOrFolderInCollection}
      />
    </div>
  </div>
  <ModalWrapperV1
    title={"Save Request"}
    type={"dark"}
    width={"55%"}
    zIndex={10000}
    isOpen={isExposeSaveAsRequest}
    handleModalState={(flag = false) => {
      isExposeSaveAsRequest = flag;
    }}
  >
    <SaveAsRequest
      onClick={(flag = false) => {
        isExposeSaveAsRequest = flag;
      }}
      requestMethod={$tab.property.request?.method}
      requestUrl={$tab.property.request?.url}
      requestName={$tab.name}
      requestDescription={$tab.description}
      requestPath={$tab.path}
      collections={$collections}
      {readWorkspace}
      {onSaveAsRequest}
      {onCreateFolder}
      {onCreateCollection}
    />
  </ModalWrapperV1>
{/if}
