<script lang="ts">
  // ---- Assets
  import floppyDisk from "$lib/assets/floppy-disk.svg";
  import angleDown from "$lib/assets/angle-down.svg";

  // ---- Components
  import {
    HttpUrlSection,
    RequestHeaders,
    RequestNavigator,
    ResponseNavigator,
    RequestAuth,
    ResponseDefaultScreen,
    ResponseErrorScreen,
    ResponseHeaders,
    ResponseBodyNavigator,
    RequestBody,
    RequestName,
    ResponseBody,
    RestExtensionPanel,
    SaveAsRequest,
    RequestParameters,
  } from "@workspaces/features/rest-explorer/components";
  import Loader from "$lib/components/Transition/loader/Loader.svelte";
  import { ModalWrapperV1 } from "$lib/components";
  import Dropdown from "$lib/components/dropdown/Dropdown.svelte";
  import { notifications } from "$lib/components/toast-notification/ToastNotification";
  import { Splitpanes, Pane } from "svelte-splitpanes";
  import Button from "$lib/components/buttons/Button.svelte";

  // ---- View Model
  //   import RestExplorerViewModel from "./RestExplorer.ViewModel";

  // ---- types
  import { RequestSection, ResponseSection } from "$lib/utils/enums";

  // ---- Store
  import {
    restLeftPanelWidth,
    restRightPanelWidth,
    restSplitterDirection,
  } from "@workspaces/features/rest-explorer/store";
  import { user } from "$lib/store";

  const handleRequestNavigator = (event: CustomEvent<string>): void => {
    onUpdateRequestState({ requestNavigation: event.detail });
  };
  const handleRequestAuth = (event: CustomEvent<string>): void => {
    onUpdateRequestState({ requestAuthNavigation: event.detail });
  };
  const handleResponseNavigator = (event: CustomEvent<string>): void => {
    onUpdateRequestState({ responseNavigation: event.detail });
  };

  export let collections;
  export let requestUrl;
  export let response;
  export let requestParams;
  export let requestState;
  export let requestBody;
  export let requestAutoGeneratedHeaders;
  export let requestMethod;
  export let requestAuthHeader;
  export let requestAuthParameter;
  export let requestAuth;
  export let requestName;
  export let requestDescription;
  export let requestPath;
  export let requestHeaders;
  export let onSendRequest;
  export let onUpdateRequestUrl;
  export let onUpdateRequestMethod;
  export let onUpdateRequestParams;
  export let onUpdateRequestName;
  export let onUpdateRequestBody;
  export let onUpdateRequestAuth;
  export let onUpdateHeaders;
  export let onUpdateAutoGeneratedHeaders;
  export let onUpdateRequestState;
  export let onClearResponse;
  export let onSaveRequest;
  export let onUpdateRequestDescription;
  export let readRequestOrFolderInCollection;
  export let readCollection;
  export let readWorkspace;
  export let onSaveAsRequest;
  export let onCreateFolder;
  export let onCreateCollection;

  let isExposeSaveAsRequest = false;
</script>

<div class="d-flex">
  <div class="w-100 d-flex flex-column h-100">
    <!-- Request Name Header -->
    <div class="d-flex justify-content-between w-100 p-3">
      <RequestName name={$requestName} {onUpdateRequestName} />
      <!-- Save and Share Buttons -->
      <div class="d-flex justify-content-between">
        <Button
          title="Save Request"
          type="dark"
          loader={$requestState.isSaveRequestInProgress}
          buttonClassProp="ms-2"
          buttonStartIcon={floppyDisk}
          onClick={async () => {
            const x = await onSaveRequest();
            if (
              x.status === "error" &&
              x.message ===
                "request is not a part of any workspace or collection"
            ) {
              isExposeSaveAsRequest = true;
            } else if (x.status === "success") {
              notifications.success("API request saved");
            }
          }}
        />

        <span class="position-relative" style="width:35px;">
          <Dropdown
            disabled={false}
            dropdownId={"saveAsDropdown"}
            dropDownType={{ type: "img", title: angleDown }}
            data={[
              {
                name: "Save As",
                id: "collection",
                dynamicClasses: "text-whiteColor",
              },
            ]}
            onclick={() => {
              isExposeSaveAsRequest = true;
            }}
            staticCustomStyles={[
              {
                id: "saveAsDropdown-options-container",
                styleKey: "minWidth",
                styleValue: "180px",
              },
            ]}
            staticClasses={[
              {
                id: "saveAsDropdown-img",
                classToAdd: ["btn", "bg-dullBackground", "px-2", "py-1"],
              },
              {
                id: "saveAsDropdown-options-name",
                classToAdd: ["fs-6"],
              },
              {
                id: "saveAsDropdown-options-container",
                classToAdd: ["end-0", "mt-1", "rounded"],
              },
            ]}
          ></Dropdown>
        </span>
        <Button
          title="Share"
          type="dark"
          buttonClassProp="ms-2"
          onClick={() => {}}
        />
      </div>
    </div>

    <!-- HTTP URL Section -->
    <HttpUrlSection
      class="py-1 px-3"
      requestUrl={$requestUrl}
      httpMethod={$requestMethod}
      splitterDirection={$requestState.requestSplitterDirection}
      onSendButtonClicked={onSendRequest}
      {onUpdateRequestUrl}
      {onUpdateRequestMethod}
      {onUpdateRequestState}
    />

    <Splitpanes
      class=""
      id={"rest-splitter"}
      style="height: calc(100vh - 240px); margin-top:10px;"
      horizontal={$requestState.requestSplitterDirection === "horizontal"
        ? true
        : false}
      dblClickSplitter={false}
      on:resize={(e) => {
        onUpdateRequestState({
          requestLeftSplitterWidthPercentage: e.detail[0].size,
        });
        onUpdateRequestState({
          requestRightSplitterWidthPercentage: e.detail[1].size,
        });
        // restLeftPanelWidth.set(e.detail[0].size);
        // restRightPanelWidth.set(e.detail[1].size);
      }}
    >
      <Pane
        minSize={30}
        size={$requestState.requestLeftSplitterWidthPercentage}
      >
        <!-- Request Pane -->
        <div class="px-3 pb-3 h-100 position-relative">
          <RequestNavigator
            requestStateSection={$requestState.requestNavigation}
            on:change={handleRequestNavigator}
          />
          {#if $requestState?.requestNavigation === RequestSection.PARAMETERS}
            <RequestParameters
              params={$requestParams}
              {onUpdateRequestParams}
              authParameter={$requestAuthParameter}
            />
          {:else if $requestState?.requestNavigation === RequestSection.REQUEST_BODY}
            <RequestBody
              body={$requestBody}
              method={$requestMethod}
              requestState={$requestState}
              {onUpdateRequestBody}
              {onUpdateRequestState}
            />
          {:else if $requestState?.requestNavigation === RequestSection.HEADERS}
            <RequestHeaders
              headers={$requestHeaders}
              autoGeneratedHeaders={$requestAutoGeneratedHeaders}
              authHeader={$requestAuthHeader}
              onHeadersChange={onUpdateHeaders}
              onAutoGeneratedHeadersChange={onUpdateAutoGeneratedHeaders}
            />
          {:else if $requestState?.requestNavigation === RequestSection.AUTHORIZATION}
            <RequestAuth
              requestStateAuth={$requestState?.requestAuthNavigation}
              on:change={handleRequestAuth}
              auth={$requestAuth}
              {onUpdateRequestAuth}
            />
          {/if}
        </div>
      </Pane>
      <Pane
        minSize={30}
        size={$requestState.requestRightSplitterWidthPercentage}
        class="position-relative"
      >
        <!-- Response Pane -->
        <!-- <ResponsePane response={$response} /> -->
        <div class="d-flex flex-column h-100 px-3">
          {#if $requestState?.isSendRequestInProgress}
            <ResponseDefaultScreen />
            <div
              style="    
            top: 10px;
            left: 0;
            right: 0;
            bottom: 0;
            z-index:3;
            position:absolute;
            "
            >
              <Loader loaderSize={"80px"} />
            </div>
          {:else if !$response?.status}
            <ResponseDefaultScreen />
          {:else if $response?.status === "Not Found"}
            <ResponseErrorScreen />
          {:else if $response?.status}
            <ResponseNavigator
              requestStateSection={$requestState.responseNavigation}
              on:change={handleResponseNavigator}
            />
            {#if $requestState.responseNavigation === ResponseSection.RESPONSE}
              <ResponseBodyNavigator
                response={$response}
                apiState={$requestState}
                {onUpdateRequestState}
                {onClearResponse}
              />
              <ResponseBody response={$response} apiState={$requestState} />
            {:else if $requestState.responseNavigation === ResponseSection.HEADERS}
              <ResponseHeaders responseHeader={$response?.headers} />
            {/if}
          {/if}
        </div></Pane
      >
    </Splitpanes>
  </div>
  <div>
    <RestExtensionPanel
      state={$requestState}
      requestMethod={$requestMethod}
      requestUrl={$requestUrl}
      requestName={$requestName}
      requestDescription={$requestDescription}
      requestPath={$requestPath}
      collections={$collections}
      {onSaveRequest}
      {readCollection}
      {readWorkspace}
      {onSaveAsRequest}
      {onCreateFolder}
      {onCreateCollection}
      {onUpdateRequestState}
      {onUpdateRequestDescription}
      {readRequestOrFolderInCollection}
    />
  </div>
</div>
<ModalWrapperV1
  title={"Save Request"}
  type={"dark"}
  width={"55%"}
  zIndex={10000}
  isOpen={isExposeSaveAsRequest}
  handleModalState={(flag = false) => {
    isExposeSaveAsRequest = flag;
  }}
>
  <SaveAsRequest
    onClick={(flag = false) => {
      isExposeSaveAsRequest = flag;
    }}
    requestMethod={$requestMethod}
    requestUrl={$requestUrl}
    requestName={$requestName}
    requestDescription={$requestDescription}
    requestPath={$requestPath}
    collections={$collections}
    {readCollection}
    {readWorkspace}
    {onSaveAsRequest}
    {onCreateFolder}
    {onCreateCollection}
  />
</ModalWrapperV1>
