<script lang="ts">
  // ---- Assets
  import { floppyDiskIcon as floppyDisk } from "@sparrow/library/assets";

  // ---- Components
  import {
    HttpUrlSection,
    RequestHeaders,
    RequestNavigator,
    ResponseNavigator,
    RequestAuth,
    ResponseDefaultScreen,
    ResponseHeaders,
    ResponseBodyNavigator,
    RequestBody,
    RequestName,
    ResponseBody,
    RequestParameters,
  } from "../components";
  import { notifications } from "@sparrow/library/ui";
  import { Splitpanes, Pane } from "svelte-splitpanes";
  import { Button } from "@sparrow/library/ui";

  import type { CollectionDocument } from "@app/database/database";
  import type { Observable } from "rxjs";
  import { SaveAsCollectionItem } from "@sparrow/workspaces/features";
  import type {
    ClearResponseType,
    CreateCollectionType,
    CreateFolderType,
    ReadCollectionType,
    ReadRequestOrFolderInCollectionType,
    ReadWorkspaceType,
    SaveAsRequestType,
    SaveRequestType,
    SendRequestType,
    UpdateAutoGeneratedHeadersType,
    UpdateHeadersType,
    UpdateParamsType,
    UpdateRequestAuthType,
    UpdateRequestBodyType,
    UpdateRequestDescriptionType,
    UpdateRequestMethodType,
    UpdateRequestNameType,
    UpdateRequestStateType,
    UpdateRequestUrlType,
  } from "@sparrow/workspaces/type";
  import {
    RequestSectionEnum,
    ResponseSectionEnum,
    type KeyValue,
  } from "@sparrow/common/types/workspace";
  import { requestSplitterDirection } from "../store";
  import { Popover } from "@sparrow/library/ui";
  import { onMount } from "svelte";
  import { Carousel, Modal } from "@sparrow/library/ui";
  import RequestDoc from "../components/request-doc/RequestDoc.svelte";
  import {
    AdvanceAPI,
    CreateCollection,
    SendingApiRequest,
  } from "@sparrow/workspaces/constants";

  import type { CancelRequestType } from "@workspaces/common/type/actions";
  import type { restExplorerData } from "../store/rest-explorer";
  import type { Tab } from "@sparrow/common/types/workspace/tab";
  import { ChevronRightRegular } from "@sparrow/library/icons";

  export let tab: Observable<Tab>;
  export let collections: Observable<CollectionDocument[]>;
  export let requestAuthHeader: Observable<KeyValue>;
  export let requestAuthParameter: Observable<KeyValue>;
  export let onUpdateRequestUrl: UpdateRequestUrlType;
  export let onSendRequest: SendRequestType;
  export let onCancelRequest: CancelRequestType;
  export let onUpdateRequestMethod: UpdateRequestMethodType;
  export let onUpdateRequestParams: UpdateParamsType;
  export let onUpdateRequestName: UpdateRequestNameType;
  export let onUpdateRequestBody: UpdateRequestBodyType;
  export let onUpdateRequestAuth: UpdateRequestAuthType;
  export let onUpdateHeaders: UpdateHeadersType;
  export let onUpdateAutoGeneratedHeaders: UpdateAutoGeneratedHeadersType;
  export let onUpdateRequestState: UpdateRequestStateType;
  export let onUpdateResponseState;
  export let onUpdateResponseBody;
  export let onClearResponse: ClearResponseType;
  export let onSaveRequest: SaveRequestType;
  export let onUpdateRequestDescription: UpdateRequestDescriptionType;
  export let readRequestOrFolderInCollection: ReadRequestOrFolderInCollectionType;
  export let readCollection: ReadCollectionType;
  export let readWorkspace: ReadWorkspaceType;
  export let onSaveAsRequest: SaveAsRequestType;
  export let onCreateFolder: CreateFolderType;
  export let onCreateCollection: CreateCollectionType;
  export let onUpdateEnvironment;
  export let environmentVariables;
  export let isGuestUser = false;
  // export let isLoginBannerActive = false;
  export let isPopoverContainer = true;
  export let onFetchCollectionGuide: (query) => void;
  export let onUpdateCollectionGuide: (query, isActive) => void;
  // export let onUpdateAiPrompt;
  // export let onUpdateAiConversation;
  export let onGenerateDocumentation;
  /**
   * Role of user in active workspace
   */
  export let userRole;
  export let storeData: restExplorerData | undefined;
  export let isTourGuideOpen = false;
  export let isWebApp = false;
  export let azureBlobCDN;
  export let onFetchParentRequest;

  const closeCollectionHelpText = () => {
    onUpdateCollectionGuide({ id: "collection-guide" }, false);
    isPopoverContainer = !isPopoverContainer;
  };
  let parentRequest;

  onMount(async () => {
    const event = await onFetchCollectionGuide({
      id: "collection-guide",
    });
    event?.$.subscribe((e) => {
      if (e.isActive === false) {
        isPopoverContainer = false;
      } else {
        isPopoverContainer = true;
      }
    });
  });
  export let onRenameCollection;
  export let onRenameFolder;

  let isExposeSaveAsRequest = false;
  let isLoading = true;
  $: {
    if ($tab?.property?.savedRequest?.url?.length > 0) {
      isLoading = false;
    }
  }
  $: {
    if (isTourGuideOpen) {
      isGuidePopup = true;
    }
  }
  const fetchRequestData = async () => {
    parentRequest = await onFetchParentRequest(
      $tab.path.collectionId,
      $tab.path.requestId,
      $tab.path.folderId,
    );
  };
  $: {
    if ($tab.tabId) {
      fetchRequestData();
    }
  }
  const toggleSaveRequest = (flag: boolean): void => {
    isExposeSaveAsRequest = flag;
  };
  let isGuidePopup = false;
</script>

{#if $tab.tabId}
  <div class="d-flex rest-explorer-layout h-100">
    <div class="w-100 d-flex flex-column h-100 px-3 pt-3 pb-2">
      <!-- Request Name Header -->
      <!-- 
        --
        -- Rest name header is set to display none 
        --
      -->
      <div class="d-flex justify-content-between w-100 p-3 d-none">
        <RequestName name={$tab.name} {onUpdateRequestName} />

        <div class="d-flex justify-content-between">
          <Button
            title="Save Request"
            type={"secondary"}
            loader={false}
            buttonClassProp="ms-2"
            buttonStartIcon={floppyDisk}
            onClick={async () => {
              const x = await onSaveRequest();
              if (
                x.status === "error" &&
                x.message ===
                  "request is not a part of any workspace or collection"
              ) {
                isExposeSaveAsRequest = true;
              } else if (x.status === "success") {
                notifications.success("API request saved successfully.");
              }
            }}
          />

          <span class="position-relative" style="width:35px;"> </span>
          <Button
            title="Share"
            type={"secondary"}
            buttonClassProp="ms-2"
            onClick={() => {}}
          />
        </div>
      </div>

      <!-- HTTP URL Section -->
      <HttpUrlSection
        class=""
        isSave={$tab.isSaved}
        bind:userRole
        requestUrl={$tab.property.savedRequest?.url}
        httpMethod={$tab.property.savedRequest?.method}
        isSendRequestInProgress={storeData?.isSendRequestInProgress}
        onSendButtonClicked={onSendRequest}
        onCancelButtonClicked={onCancelRequest}
        {onUpdateEnvironment}
        {environmentVariables}
        {onUpdateRequestUrl}
        {onUpdateRequestMethod}
        {toggleSaveRequest}
        {onSaveRequest}
        {isGuestUser}
      />
      <!--Disabling the Quick Help feature, will be taken up in next release-->
      <div class="" style="margin-top: 10px;">
        {#if isPopoverContainer}
          <Popover
            onClose={closeCollectionHelpText}
            heading={`Welcome to Sparrow`}
          >
            <p class="mb-0 text-fs-12">
              Your one-stop solution for API testing and management. Start
              organizing your API requests into collections, utilize environment
              variables, and streamline your development process. Get started
              now by creating your first collection or exploring our features
              <span
                on:click={() => {
                  isGuidePopup = true;
                }}
                class="link p-0 border-0"
                style="font-size: 12px;"
                >See how it works.
              </span>
            </p>
          </Popover>
        {/if}
      </div>
      <div class="pt-2"></div>
      <div style="flex:1; overflow:auto;">
        {#if !isLoading}
          <Splitpanes
            class="rest-splitter-saved w-100 h-100"
            id={"rest-splitter-saved"}
            horizontal={$requestSplitterDirection === "horizontal"
              ? true
              : false}
            dblClickSplitter={false}
            on:resize={(e) => {
              onUpdateRequestState({
                requestLeftSplitterWidthPercentage: e.detail[0].size,
              });
              onUpdateRequestState({
                requestRightSplitterWidthPercentage: e.detail[1].size,
              });
            }}
          >
            <Pane
              minSize={30}
              size={$tab.property.savedRequest?.state
                ?.requestLeftSplitterWidthPercentage}
              class="position-relative bg-transparent"
            >
              <!-- Request Pane -->
              <div
                class="h-100 d-flex flex-column position-relative {$requestSplitterDirection ===
                'horizontal'
                  ? 'pb-1'
                  : 'pe-2'}"
              >
                <div class="d-flex breadcrump-txt">
                  <span class="parent-txt">{parentRequest?.name}</span>
                  <ChevronRightRegular
                    size={"12px"}
                    color="var(--icon-ds-neutral-400)"
                  />
                  <span class="request-txt">{$tab.name}</span>
                </div>
                <div class="breadcrump-line" />
                <RequestNavigator
                  requestStateSection={$tab.property.savedRequest?.state
                    ?.requestNavigation}
                  {onUpdateRequestState}
                  authParameterLength={$requestAuthParameter.value ? 1 : 0}
                  authHeaderLength={$requestAuthHeader.value ? 1 : 0}
                  paramsLength={$tab.property?.savedRequest?.queryParams
                    ?.length || 0}
                  headersLength={$tab.property?.savedRequest?.headers?.length ||
                    0}
                  autoGeneratedHeadersLength={$tab.property?.savedRequest
                    ?.autoGeneratedHeaders?.length || 0}
                />
                <div style="flex:1; overflow:auto;" class="p-0">
                  {#if $tab.property.savedRequest?.state?.requestNavigation === RequestSectionEnum.PARAMETERS}
                    <RequestParameters
                      isBulkEditActive={$tab?.property?.savedRequest.state
                        ?.isParameterBulkEditActive}
                      {onUpdateRequestState}
                      params={$tab.property.savedRequest.queryParams}
                      {onUpdateRequestParams}
                      authParameter={$requestAuthParameter}
                      {onUpdateEnvironment}
                      {environmentVariables}
                    />
                  {:else if $tab.property.savedRequest?.state?.requestNavigation === RequestSectionEnum.REQUEST_BODY}
                    <RequestBody
                      body={$tab.property.savedRequest.body}
                      method={$tab.property.savedRequest.method}
                      requestState={$tab.property.savedRequest.state}
                      {onUpdateRequestBody}
                      {onUpdateRequestState}
                      {onUpdateEnvironment}
                      {environmentVariables}
                      {isWebApp}
                    />
                  {:else if $tab.property.savedRequest?.state?.requestNavigation === RequestSectionEnum.HEADERS}
                    <RequestHeaders
                      isBulkEditActive={$tab?.property?.savedRequest.state
                        ?.isHeaderBulkEditActive}
                      {onUpdateRequestState}
                      {environmentVariables}
                      {onUpdateEnvironment}
                      headers={$tab.property.savedRequest.headers}
                      autoGeneratedHeaders={$tab.property.savedRequest
                        .autoGeneratedHeaders}
                      authHeader={$requestAuthHeader}
                      onHeadersChange={onUpdateHeaders}
                      onAutoGeneratedHeadersChange={onUpdateAutoGeneratedHeaders}
                      {isWebApp}
                    />
                  {:else if $tab.property.savedRequest?.state?.requestNavigation === RequestSectionEnum.AUTHORIZATION}
                    <RequestAuth
                      requestStateAuth={$tab.property.savedRequest.state
                        .requestAuthNavigation}
                      {onUpdateRequestState}
                      auth={$tab.property.savedRequest.auth}
                      {onUpdateRequestAuth}
                      {onUpdateEnvironment}
                      {environmentVariables}
                    />
                  {:else if $tab.property.savedRequest?.state?.requestNavigation === RequestSectionEnum.DOCUMENTATION}
                    <RequestDoc
                      isDocGenerating={$tab.property.savedRequest?.state
                        ?.isDocGenerating}
                      isDocAlreadyGenerated={$tab.property.savedRequest?.state
                        ?.isDocAlreadyGenerated}
                      {onGenerateDocumentation}
                      {onUpdateRequestDescription}
                      requestDoc={$tab.description}
                      {isGuestUser}
                    />
                  {/if}
                </div>
              </div>
            </Pane>
            <Pane
              minSize={30}
              size={$tab.property.savedRequest?.state
                ?.requestRightSplitterWidthPercentage}
              class="bg-transparent position-relative"
            >
              <!-- Response Pane -->
              <div
                class="d-flex flex-column h-100 {$requestSplitterDirection ===
                'horizontal'
                  ? 'pt-1'
                  : 'ps-2'}"
                style="overflow:auto;"
              >
                <div class="h-100 d-flex flex-column">
                  <div style="flex:1; overflow:auto;">
                    <div class="h-100 d-flex flex-column">
                      <!-- <ResponseStatus response={storeData.response} /> -->
                      <ResponseNavigator
                        requestStateSection={$tab.property.savedRequest?.state
                          ?.responseNavigation}
                        statusCodes={$tab.property.savedRequest?.responseStatus}
                        date={$tab.property.savedRequest?.responseDate}
                        {onUpdateRequestState}
                        responseHeadersLength={$tab.property.savedRequest
                          ?.responseHeaders?.length || 0}
                      />
                      {#if $tab.property.savedRequest?.state?.responseNavigation === ResponseSectionEnum.RESPONSE}
                        {#if $tab.property.savedRequest?.state?.responseBodyLanguage !== "Image"}
                          <ResponseBodyNavigator
                            response={$tab.property.savedRequest?.headers || []}
                            body={$tab.property.savedRequest?.responseBody}
                            apiState={$tab.property.savedRequest?.state}
                            {onUpdateRequestState}
                            {onClearResponse}
                            {isWebApp}
                          />
                        {/if}
                        <div style="flex:1; overflow:auto;">
                          <ResponseBody
                            response={$tab.property.savedRequest?.responseBody}
                            apiState={$tab.property.savedRequest?.state}
                            {onUpdateResponseBody}
                          />
                        </div>
                      {:else if $tab.property.savedRequest?.state?.responseNavigation === ResponseSectionEnum.HEADERS}
                        <div style="flex:1; overflow:auto;">
                          <ResponseHeaders
                            responseHeader={$tab.property.savedRequest
                              ?.responseHeaders || []}
                          />
                        </div>
                      {/if}
                    </div>
                  </div>
                </div>
              </div></Pane
            >
          </Splitpanes>
        {:else}
          <!-- loading state -->
          <ResponseDefaultScreen isMainScreen={true} />
        {/if}
      </div>
    </div>
  </div>
  <Modal
    title={"Save Request"}
    type={"dark"}
    width={"55%"}
    zIndex={10000}
    isOpen={isExposeSaveAsRequest}
    handleModalState={(flag = false) => {
      isExposeSaveAsRequest = flag;
    }}
  >
    <SaveAsCollectionItem
      onClick={(flag = false) => {
        isExposeSaveAsRequest = flag;
      }}
      requestMethod={$tab.property.savedRequest?.method}
      requestUrl={$tab.property.savedRequest?.url}
      requestName={$tab.name}
      requestDescription={$tab.description}
      requestPath={$tab.path}
      collections={$collections}
      {readWorkspace}
      onSave={onSaveAsRequest}
      {onCreateFolder}
      {onCreateCollection}
      {onRenameCollection}
      {onRenameFolder}
    />
  </Modal>
{/if}

<Modal
  title={""}
  type={"dark"}
  width={"474px"}
  zIndex={10000}
  isOpen={isGuidePopup}
  handleModalState={(flag = false) => {
    isGuidePopup = flag;
    isTourGuideOpen = false;
  }}
>
  <div style="position: relative;">
    <Carousel
      handleClosePopup={(flag = false) => {
        isGuidePopup = flag;
        isTourGuideOpen = false;
      }}
      data={[
        {
          id: 1,
          heading: "Creating a Collection: Import existing or Start a new one",
          subheading: `Organize your APIs efficiently within "Collections" for streamlined API management and testing. Click the + Add Collection button in the side panel to create a collection. Choose 'Import Collection' to bring in existing API collections or create an empty Collection. `,
          gif: `${azureBlobCDN}${CreateCollection}`,
        },
        {
          id: 2,
          heading: "Sending an API Request",
          subheading:
            "In the request builder, input your API endpoint URL in the URL field. Click the 'Send' button to dispatch the request. Instantly see the server's response, which includes status codes, response time, and data.",
          gif: `${azureBlobCDN}${SendingApiRequest}`,
        },
        {
          id: 3,
          heading: "Advanced API Request with Detailed Inputs",
          subheading:
            "Enter the endpoint URL in the URL field. Utilize 'Parameters' tab for parameters, 'Body' tab to input data payloads, 'Headers' tab for custom headers, and 'Auth' tab to manage access credentials. After filling in the required fields, click 'Send' to execute the request and view the detailed server response.",
          gif: `${azureBlobCDN}${AdvanceAPI}`,
        },
      ]}
    />
  </div>
</Modal>

<style>
  .rest-explorer-layout {
    background-color: var(--bg-ds-surface-900);
  }

  :global(.rest-splitter-saved.splitpanes--vertical > .splitpanes__splitter) {
    width: 11px !important;
    height: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-left: 5px solid var(--border-ds-surface-900) !important;
    border-right: 5px solid var(--border-ds-surface-900) !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
  }
  :global(.rest-splitter-saved.splitpanes--horizontal > .splitpanes__splitter) {
    height: 11px !important;
    width: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-top: 5px solid var(--border-ds-surface-900) !important;
    border-bottom: 5px solid var(--border-ds-surface-900) !important;
    border-left: 0 !important;
    border-right: 0 !important;
  }
  :global(
    .rest-splitter-saved > .splitpanes__splitter:active,
    .rest-splitter-saved > .splitpanes__splitter:hover
  ) {
    background-color: var(--bg-primary-200) !important;
  }
  .link {
    color: var(--text-primary-300);
    text-decoration: underline;
    cursor: pointer;
  }
  .parent-txt {
    color: var(--text-ds-neutral-100);
    font-size: 12px;
    font-weight: 500;
    padding-right: 10px;
  }
  .request-txt {
    color: var(--text-ds-neutral-500);
    font-size: 12px;
    font-weight: 500;
    padding-left: 10px;
  }
  .breadcrump-txt {
    padding-left: 12px;
    padding-bottom: 14px;
  }
  .breadcrump-line {
    width: 100%;
    border: 1px solid var(--border-ds-surface-50);
    margin-bottom: 2px;
  }
</style>
