import {
  type Auth,
  type KeyValueChecked,
  type StatePartial,
} from "@sparrow/common/types/workspace";
import {
  TabTypeEnum,
  type Tab,
  type Path,
} from "@sparrow/common/types/workspace/tab";
import { v4 as uuidv4 } from "uuid";
import {
  GraphqlRequestAuthTypeTabEnum,
  GraphqlRequestSectionTabEnum,
} from "../types/workspace/graphql-request-tab";
import { GraphqlRequestDefaultAliasBaseEnum } from "../types/workspace/graphql-request-base";

class InitGraphqlTab {
  private _tab: Tab;
  /**
   *
   * @param _id - Request mongo id
   * @param _workspaceId - Workspace Id to which Request belongs to
   */
  constructor(_id: string, _workspaceId: string) {
    this._tab = {
      id: _id,
      tabId: uuidv4(),
      name: "New " + GraphqlRequestDefaultAliasBaseEnum.NAME,
      type: TabTypeEnum.GRAPHQL,
      description: "",
      source: "USER",
      isDeleted: false,
      activeSync: false,
      property: {
        graphql: {
          url: "",
          query: "",
          schema: "",
          headers: [
            {
              key: "",
              value: "",
              checked: false,
            },
          ],
          autoGeneratedHeaders: [
            {
              key: "Accept",
              value: "*/*",
              checked: true,
            },
            {
              key: "Connection",
              value: "keep-alive",
              checked: true,
            },
            {
              key: "User-Agent",
              value:
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
              checked: true,
            },
            {
              key: "Accept-Encoding",
              value: "gzip, br",
              checked: true,
            },
          ],
          state: {
            requestNavigation: GraphqlRequestSectionTabEnum.QUERY,
            requestAuthNavigation: GraphqlRequestAuthTypeTabEnum.NO_AUTH,
            requestLeftSplitterWidthPercentage: 50,
            requestRightSplitterWidthPercentage: 50,
            isHeaderBulkEditActive: false,
          },
          auth: {
            bearerToken: "",
            basicAuth: {
              username: "",
              password: "",
            },
            apiKey: {
              authKey: "",
              authValue: "",
            },
          },
        },
      },
      path: {
        workspaceId: _workspaceId,
        collectionId: "",
        folderId: "",
      },
      isSaved: true,
      index: 0,
      isActive: true,
      timestamp: new Date().toString(),
    };
    if (!_id || !_workspaceId) {
      console.error("invalid id or workspace id on create new tab request!");
    }
  }
  public getValue(): Tab {
    return this._tab;
  }
  public updateId(_id: string) {
    this._tab.id = _id;
  }
  public updateName(_name: string) {
    this._tab.name = _name;
  }
  public updateDescription(_description: string) {
    this._tab.description = _description;
  }
  public updatePath(_path: Path) {
    this._tab.path = _path;
  }
  public updateUrl(_url: string) {
    if (_url && this._tab.property.request) {
      this._tab.property.request.url = _url;
    }
  }

  public updateHeaders(_headers: KeyValueChecked[]) {
    if (_headers && this._tab.property.request) {
      this._tab.property.request.headers = _headers;
    }
  }
  public updateAuth(_auth: Auth) {
    if (_auth && this._tab.property.request) {
      this._tab.property.request.auth = _auth;
    }
  }
  public updateAutoGeneratedHeaders(_autoGeneratedHeaders: KeyValueChecked[]) {
    if (this._tab.property.request) {
      this._tab.property.request.autoGeneratedHeaders = _autoGeneratedHeaders;
    }
  }
  public updateIsSave(_isSave: boolean) {
    this._tab.isSaved = _isSave;
  }
  public updateState(_state: StatePartial) {
    if (this._tab.property.request) {
      this._tab.property.request.state = {
        ...this._tab.property.request.state,
        ..._state,
      };
    }
  }
}

export { InitGraphqlTab };
