<script lang="ts">
  import type {
    KeyValuePair,
    KeyValuePairWithBase,
  } from "@sparrow/common/interfaces/request.interface";
  import { TabularInputTheme } from "../../utils";
  import { onMount, tick } from "svelte";
  import { Tooltip, Button } from "@sparrow/library/ui";
  import { Checkbox } from "@sparrow/library/forms";
  import { ErrorInfoIcon, Information } from "@sparrow/library/icons";
  import BulkEditEditor from "./sub-component/BulkEditEditor.svelte";
  import LazyElement from "./LazyElement.svelte";
  import { Toggle } from "@sparrow/library/ui";

  export let environmentVariables;
  export let onUpdateEnvironment;
  export let onToggleBulkEdit;
  export let isBulkEditActive = false;
  export let isBulkEditRequired = false;
  export let isBulkEditHeaderInfoRequired = false;
  export let isCheckBoxEditable = true;
  export let isTopHeaderRequired = true;
  export let isInputBoxEditable = true;
  export let bulkEditPlaceholder = "";
  // export let type: "file" | "text" = "text";

  // exports
  export let keyValue: KeyValuePair[];
  export let callback: (pairs: KeyValuePair[]) => void;
  export let readable: { key: string; value: string } = {
    key: "",
    value: "",
  };

  // New props for merge/diff view **anish
  export let showMergeView = false;
  export let isMergeViewLoading = false;
  export let newModifiedPairs: KeyValuePair[] = [];

  let enableKeyValueHighlighting = true;
  let pairs: KeyValuePair[] = keyValue;
  let controller: boolean = false;

  let bulkText = "";
  let diffBulkText = "";
  let bulkToggle = isBulkEditActive;

  $: {
    if (diffBulkText) console.log("diffBulkText changed :>> ", diffBulkText);
  }

  let isErrorIconHovered = false;
  let isAutoGeneratedInfoHovered = false;

  let isValidSyntax = true;
  let pairsContainer: HTMLElement;

  const theme = new TabularInputTheme().build();

  // Calculate diff between original and current data **anish
  type DiffType = "added" | "deleted" | "modified" | "unchanged";
  type DiffPair = KeyValuePair & {
    diffType: DiffType;
    originalIndex?: number;
    currentIndex?: number;
  };
  let diffPairs: DiffPair[] = [];

  // Funtion to calculate diff. b/w origional data (pairs) and new data (newModifiedPairs)
  function calculateDiff(): DiffPair[] {
    // Set a flag to indicate calculation is in progress
    isMergeViewLoading = true;

    // if (!showMergeView || !pairs || pairs.length === 0) {
    //   console.log("pairs ", pairs.length);
    //   return newModifiedPairs.map((pair) => ({
    //     ...pair,
    //     diffType: "unchanged",
    //   }));
    // }

    // If table data is empty but we have new data, then consider everything as an addition
    // if (!pairs || pairs.length === 0) {
    //   console.log("pairs ", pairs.length);
    //   return newModifiedPairs.map((pair) => ({
    //     ...pair,
    //     diffType: "added",
    //     currentIndex: newModifiedPairs.indexOf(pair),
    //   }));
    // }

    const result: DiffPair[] = [];
    const origMap = new Map();

    // Create a map of original items using key as a unique identifier
    pairs.forEach((pair, index) => {
      origMap.set(pair.key, { pair, index });
    });
    // Check for modified or added items
    newModifiedPairs.forEach((currentPair, currentIndex) => {
      if (currentPair.key === "") return; // Skip empty rows

      const originalEntry = origMap.get(currentPair.key);

      if (originalEntry) {
        // Key exists in both - check if value changed
        if (originalEntry.pair.value !== currentPair.value) {
          result.push({
            ...currentPair,
            diffType: "modified",
            originalIndex: originalEntry.index,
            currentIndex,
          });

          // Also add the original version to show what changed
          result.push({
            ...originalEntry.pair,
            diffType: "deleted",
            originalIndex: originalEntry.index,
          });
        } else {
          // Unchanged
          result.push({
            ...currentPair,
            diffType: "unchanged",
            originalIndex: originalEntry.index,
            currentIndex,
          });
        }

        // Mark as processed
        origMap.delete(currentPair.key);
      } else {
        // New item
        result.push({
          ...currentPair,
          diffType: "added",
          currentIndex,
        });
      }
    });

    // Add deleted items (those in original but not in current)
    origMap.forEach(({ pair, index }) => {
      if (pair.key !== "") {
        // Skip empty rows
        result.push({
          ...pair,
          diffType: "deleted",
          originalIndex: index,
        });
      }
    });

    // Sort by original position to maintain a logical order
    result.sort((a, b) => {
      // First priority: Group items with the same key together
      if (a.key === b.key) {
        // When keys match, deleted comes before added
        if (
          a.diffType === "deleted" &&
          (b.diffType === "added" || b.diffType === "modified")
        ) {
          return -1; // Deletion comes first
        }
        if (
          (a.diffType === "added" || a.diffType === "modified") &&
          b.diffType === "deleted"
        ) {
          return 1; // Addition comes second
        }
      }

      // Second priority: Put completely new items at the end
      const aIsNew = a.diffType === "added" && a.originalIndex === undefined;
      const bIsNew = b.diffType === "added" && b.originalIndex === undefined;

      if (aIsNew && !bIsNew) {
        return 1; // a is new but b is not - push a to the end
      } else if (!aIsNew && bIsNew) {
        return -1; // b is new but a is not - push b to the end
      }

      // Then sort by original position for existing items
      if (a.originalIndex !== undefined && b.originalIndex !== undefined) {
        return a.originalIndex - b.originalIndex;
      }

      // Fall back to current position
      if (a.currentIndex !== undefined && b.currentIndex !== undefined) {
        return a.currentIndex - b.currentIndex;
      }

      return 0;
    });

    const lastEmptyRow: DiffPair = {
      key: "",
      value: "",
      checked: false,
      diffType: "unchanged",
      originalIndex: result.length - 1,
      currentIndex: result.length - 1,
    };

    isMergeViewLoading = false;
    return [...result, lastEmptyRow];
  }

  // Convert diffPairs to bulk text format for BulkEditEditor
  function diffPairsToBulkText(): string {
    if (!diffPairs || !diffPairs.length) return "";

    return diffPairs
      .filter((pair) => pair.diffType !== "deleted" && (pair.key || pair.value))
      .map((pair) => `${pair.key}:${pair.value}`)
      .join("\n");
  }

  // Convert pairs to bulk text format
  function pairsToBulkText(pairsToConvert: KeyValuePair[]): string {
    return pairsToConvert
      .filter((pair) => pair.key || pair.value)
      .map((pair) => `${pair.key}:${pair.value}`)
      .join("\n");
  }

  const updateDiffPairsWithLoading = async () => {
    isMergeViewLoading = true;
    await sleep(1000);
    diffPairs = calculateDiff();
    diffBulkText = diffPairsToBulkText();
  };
  $: if (showMergeView) updateDiffPairsWithLoading();

  // Update diff when inputs change
  $: {
    if (keyValue) {
      identifySelectAllState();
    }
  }

  // Toggle merge view **anish
  const toggleMergeView = async (show: boolean) => {
    showMergeView = show;
    if (show) {
      isMergeViewLoading = true;
      await sleep(1000);
      diffPairs = calculateDiff();

      // Update bulk text to reflect diff if bulk edit is active
      if (isBulkEditActive) {
        bulkText = diffPairsToBulkText();
      }
    }
  };

  // Function to apply all changes from diff view to the original data
  const applyChanges = async () => {
    if (!showMergeView) return;

    isMergeViewLoading = true;

    // Extract all valid pairs from diffPairs (excluding deleted ones)
    const updatedPairs = diffPairs
      .filter((pair) => pair.diffType !== "deleted")
      .map((pair) => ({
        key: pair.key,
        value: pair.value,
        checked: pair.checked || false,
      }));

    // Add an empty row at the end if needed
    if (
      updatedPairs.length > 0 &&
      (updatedPairs[updatedPairs.length - 1].key !== "" ||
        updatedPairs[updatedPairs.length - 1].value !== "")
    ) {
      updatedPairs.push({ key: "", value: "", checked: false });
    }

    pairs = updatedPairs; // Update the pairs array with the new data
    showMergeView = false; // Turn off merge view after applying changes
    callback(pairs); // Notify parent component of the changes
    // newModifiedPairs = JSON.parse(JSON.stringify(pairs)); // Save current state for potential future comparison
    newModifiedPairs = [];

    await sleep(1000);
    isMergeViewLoading = false; // Reset loading state
  };

  // Function to undo all changes and revert to original state
  const undoChanges = async () => {
    if (!showMergeView) return;
    showMergeView = false;
    newModifiedPairs = [];
    diffPairs = []; // Reset any potential changes by discarding diffPairs
    callback(pairs); // Notify parent of unchanged data

    isMergeViewLoading = true;
    await sleep(1000);
    isMergeViewLoading = false; // Reset loading state
  };

  onMount(() => {
    handleBulkTextUpdate();

    if (showMergeView) {
      diffPairs = calculateDiff();
      diffBulkText = diffPairsToBulkText();
    }
  });

  // Utility function to create a delay
  const sleep = (ms: number): Promise<void> => {
    return new Promise((resolve) => setTimeout(resolve, ms));
  };

  /**
   * @description - calculates the select all checkbox state - weather checked or not
   */
  const identifySelectAllState = () => {
    pairs = [];
    pairs = keyValue;
    controller = false;
    if (pairs.length > 1) {
      let isUncheckedExist: boolean = false;
      for (let i = 0; i < pairs.length - 1; i++) {
        if (pairs[i].checked === false) {
          isUncheckedExist = true;
          break;
        }
      }
      if (isUncheckedExist) {
        controller = false;
      } else {
        controller = true;
      }
    }
  };

  /**
   * Scrolls the container to bring the newly added row into view
   */
  const scrollToNewRow = async () => {
    await tick();

    if (pairsContainer) {
      const lastRow = pairsContainer.lastElementChild;

      if (lastRow) {
        lastRow.scrollIntoView({ behavior: "smooth", block: "end" });
      }
    }
  };

  const updateParam = async (index: number): Promise<void> => {
    pairs = pairs;
    if (
      pairs.length - 1 === index &&
      // although in readonly mode input is disabled
      // but codemirror internally invokes this function and updates key value
      // so one more extra check here for read only mode
      isInputBoxEditable &&
      (pairs[index].key !== "" || pairs[index].value !== "")
    ) {
      pairs[pairs.length - 1].checked = true;
      pairs.push({ key: "", value: "", checked: false });
      pairs = pairs;
      callback(pairs);

      // Recalculate diff if merge view is active (althrough will disable the edit while in merge view) **anish
      if (showMergeView) {
        diffPairs = calculateDiff();

        // ToDo: Calculate only if Bulk Edit mode is active (change in every place)
        diffBulkText = diffPairsToBulkText();
      }

      await scrollToNewRow();
    } else {
      callback(pairs);
    }
  };

  let isBulkEditLoaded = false;

  /**
   * Updates the bulk text based on the key-value pairs.
   */
  const handleBulkTextUpdate = () => {
    // Define the syntax validation regex pattern (key:value)
    const syntaxPattern = /^[^:]+:.+$/;

    // Map each pair to a formatted line (key:value), validate syntax, and filter out invalid lines
    const res = pairs
      .map((elem) => {
        // Create a line from key and value, or empty string if both are empty
        const line = elem.key || elem.value ? `${elem.key}:${elem.value}` : "";

        // Validate syntax for each non-empty line
        if (line && !syntaxPattern.test(line)) {
          isValidSyntax = false;
        }

        return line;
      })
      .filter((item) => item) // Filter out empty lines
      .join("\n"); // Join lines with newline characters

    // Update the bulkText with the formatted and validated text
    bulkText = res;
    isBulkEditLoaded = true;
  };

  const handleBulkTextarea = (event) => {
    bulkText = event.detail;

    // remove all empty lines
    const res = bulkText.split("\n").filter((line) => line.trim() !== "");

    // Pushing a blank string to add a blank key value at the end
    res.push("");

    // Define the syntax validation regex pattern (key:value)
    const syntaxPattern = /^[^:]+:.+$/;

    // Initialize isValidSyntax to true
    isValidSyntax = true;

    const newPairs = res.map((elem) => {
      if (elem.length) {
        const firstColonIndex = elem.indexOf(":");
        let key, value;

        if (firstColonIndex !== -1) {
          key = elem.substring(0, firstColonIndex).trim();
          value = elem.substring(firstColonIndex + 1).trim();
        } else {
          key = elem.trim();
          value = "";
        }

        // Validate syntax for each non-empty line
        if (elem && !syntaxPattern.test(elem)) {
          isValidSyntax = false;
        }

        return {
          key: key,
          value: value,
          checked: true,
        };
      } else {
        return {
          key: "",
          value: "",
          checked: false,
        };
      }
    });

    // If in merge view mode, update the newModifiedPairs
    if (showMergeView) {
      newModifiedPairs = newPairs;
      diffPairs = calculateDiff();
      diffBulkText = diffPairsToBulkText();
    } else {
      pairs = newPairs;
      callback(pairs);
    }
  };

  const toggleBulkEdit = (event) => {
    onToggleBulkEdit(event.target.checked);

    // Update bulk text if toggling to bulk edit mode
    if (event.target.checked) {
      handleBulkTextUpdate();
      diffBulkText = diffPairsToBulkText();
    }
  };

  // Apply changes from bulk editor diff view
  const handleBulkEditorApplyChanges = () => {
    console.log("called handleBulkEditorApplyChanges() :>> ");
    applyChanges();
    // handleBulkTextUpdate(); // Synchronize the bulk text with the updated pairs
  };

  // Undo changes from bulk editor diff view
  const handleBulkEditorUndoChanges = () => {
    console.log("called handleBulkEditorUndoChanges() :>> ");
    undoChanges();
    // handleBulkTextUpdate(); // Reset bulk text to original pairs
  };

  const deleteParam = (index: number): void => {
    if (pairs.length > 1) {
      let filteredKeyValue = pairs.filter((elem, i) => {
        if (i !== index) {
          return true;
        }
        return false;
      });
      pairs = filteredKeyValue;
    }
    callback(pairs);
    setTimeout(() => {
      pairs[pairs.length - 1].key = "";
      pairs[pairs.length - 1].value = "";
    }, 0);
  };

  const updateCheck = (index: number): void => {
    let filteredKeyValue = pairs.map((elem, i) => {
      if (i === index) {
        elem.checked = !elem.checked;
      }
      return elem;
    });
    pairs = filteredKeyValue;
    callback(pairs);
  };

  const handleCheckAll = (): void => {
    let flag: boolean;
    if (controller === true) {
      flag = false;
    } else {
      flag = true;
    }
    let filteredKeyValue = pairs.map((elem, i) => {
      if (i !== pairs.length - 1) {
        elem.checked = flag;
      } else if (!isInputBoxEditable) {
        elem.checked = flag;
      }
      return elem;
    });
    pairs = filteredKeyValue;
    callback(pairs);
  };

  const handleErrorHover = () => {
    isErrorIconHovered = !isErrorIconHovered;
  };

  const handleAutoGeneratedInfoHover = () => {
    isAutoGeneratedInfoHovered = !isAutoGeneratedInfoHovered;
  };
</script>

<div>
  {#if !isBulkEditActive}
    <section class="mb-0 me-0 py-0 section-layout w-100" style="">
      <div
        class="d-flex align-items-center pair-header-row {!isTopHeaderRequired
          ? 'd-none'
          : ''}"
        style="position:relative; padding-right:1rem; padding-left:4px; border-top-left-radius: 4px; border-top-right-radius: 4px;"
      >
        <div style="width:24px; margin-right:12px" class="">
          <Checkbox
            size="small"
            disabled={pairs.length === 1 || !isCheckBoxEditable}
            checked={controller}
            on:input={handleCheckAll}
          />
        </div>

        <div class="d-flex gap-0" style="width: calc(100% - 188px);">
          <div
            class="w-50 position-relative header-text"
            style="padding-left: 6px;"
          >
            Key
          </div>
          <div
            class="w-50 position-relative header-text"
            style="padding-left: 69px;"
          >
            Value
          </div>
        </div>
        <div style="width:140px;" class="ms-3 d-flex align-items-center">
          <div class="w-100 d-flex">
            <div class="w-100 d-flex justify-content-end gap-2">
              {#if isBulkEditRequired}
                <Toggle
                  bind:isActive={bulkToggle}
                  label="Bulk Edit"
                  fontSize="12px"
                  textColor="var(--text-ds-neutral-200)"
                  fontWeight="400"
                  onClick={handleBulkTextUpdate}
                  onChange={toggleBulkEdit}
                />
              {/if}
              <!-- <Toggle
                isActive={showMergeView}
                label="Show Diff"
                fontSize="12px"
                textColor="var(--text-ds-neutral-200)"
                fontWeight="400"
                onChange={() => toggleMergeView(!showMergeView)}
              /> -->
            </div>
          </div>
        </div>
      </div>
      <div
        class="w-100"
        style="display:block; position:relative;"
        bind:this={pairsContainer}
      >
        {#if readable.key || readable.value}
          <LazyElement
            element={{
              key: readable.key,
              value: readable.value,
              checked: true,
            }}
            index={0}
            pairs={[]}
            {theme}
            {environmentVariables}
            onUpdateEnvironment={() => {}}
            updateParam={() => {}}
            updateCheck={() => {}}
            deleteParam={() => {}}
            isInputBoxEditable={false}
            isCheckBoxEditable={false}
          />
        {/if}

        {#if !isMergeViewLoading && showMergeView}
          {#each diffPairs as element, index (index)}
            <LazyElement
              element={{
                key: element.key,
                value: element.value,
                checked: element.checked,
              }}
              {index}
              pairs={diffPairs}
              {theme}
              {environmentVariables}
              {onUpdateEnvironment}
              {updateParam}
              {updateCheck}
              {deleteParam}
              isInputBoxEditable={false}
              isCheckBoxEditable={true}
              customClass={`diff-row diff-${element.diffType}`}
            />
            <!-- isInputBoxEditable={element.diffType !== "deleted"} -->
            <!-- isCheckBoxEditable={element.diffType !== "deleted"} -->
          {/each}
        {:else}
          {#each pairs as element, index (index)}
            <LazyElement
              {element}
              {index}
              {pairs}
              {theme}
              {environmentVariables}
              {onUpdateEnvironment}
              {updateParam}
              {updateCheck}
              {deleteParam}
              {isInputBoxEditable}
              {isCheckBoxEditable}
            />
          {/each}
        {/if}

        {#if !isMergeViewLoading && showMergeView}
          <div class="d-flex justify-content-end mt-3 me-0 gap-2">
            <Button
              title={"Keep the Changes!!"}
              type={"primary"}
              onClick={applyChanges}
            ></Button>
            <Button title={"Undo"} type={"secondary"} onClick={undoChanges}
            ></Button>
          </div>
        {/if}
      </div>
    </section>
  {:else}
    <!-- Bulk Edit section Start -->
    <section>
      <div class="d-flex flex-column w-100" style="font-size:12px;">
        <!-- Bulk Edit Heading -->
        <div
          class="px-3 d-flex align-items-center"
          style="justify-content: space-between; background-color: var(--bg-ds-surface-400);border-radius: 2px;padding:1px 0px;"
        >
          <!-- Bulk Edit Text  -->
          <div class="d-flex align-items-center">
            <p
              class="mb-0 text-fs-12 fw-medium"
              style="color:var(--text-ds-neutral-200)"
            >
              Bulk Edit
            </p>

            <div>
              {#if isBulkEditHeaderInfoRequired}
                <div
                  class="d-flex align-items-center rounded-1 justify-content-center position-relative"
                  style="height: 18px; width:18px; "
                >
                  <div
                    on:mouseenter={handleAutoGeneratedInfoHover}
                    on:mouseleave={handleAutoGeneratedInfoHover}
                    style="cursor: pointer; margin-bottom:2px"
                  >
                    <Tooltip
                      size="medium"
                      title="Auto-Generated Headers"
                      subtext="Auto-generated headers cannot be updated in Bulk Edit
                          mode. In order to manage auto-generated headers,
                          switch back to the Key-Value edit view."
                      placement="bottom-center"
                    >
                      <Information
                        height={"12px"}
                        width={"12px"}
                        color={"var(--bg-secondary-950)"}
                      />
                    </Tooltip>
                  </div>
                </div>
              {/if}
            </div>
          </div>

          <!-- Bulk Edit Button -->
          {#if bulkEditPlaceholder}
            <div class="pe-0 d-flex align-items-center gap-1">
              {#if !isValidSyntax}
                <div
                  class="d-flex align-items-center justify-content-center position-relative border-radius-3 me-1"
                  style="height: 18px; width:18px; z-index:1; "
                >
                  <div
                    on:mouseenter={handleErrorHover}
                    on:mouseleave={handleErrorHover}
                    style="cursor: pointer;"
                  >
                    <Tooltip
                      size="medium"
                      title="Status Error"
                      subtext="Please verify the syntax for keys and values, & ensure you follow the correct format when adding them. For example: userId:12345."
                      placement="left-top"
                    >
                      <ErrorInfoIcon
                        height={"12px"}
                        width={"12px"}
                        color={"var(--dangerColor)"}
                      />
                    </Tooltip>
                  </div>
                </div>
              {/if}
              <div style="margin-right: 2px;">
                <Toggle
                  bind:isActive={bulkToggle}
                  label="Bulk Edit"
                  fontSize="12px"
                  fontWeight="400"
                  onClick={handleBulkTextUpdate}
                  textColor="var(--text-ds-neutral-200)"
                  onChange={toggleBulkEdit}
                />
              </div>
            </div>
          {/if}
        </div>

        <!-- Bulk Edit TextArea starts -->
        <div style="height:100%">
          {#if isBulkEditLoaded}
            <BulkEditEditor
              bind:value={bulkText}
              on:change={handleBulkTextarea}
              {enableKeyValueHighlighting}
              class={`sparrow-fs-18 me-0 outline-none`}
              placeholder={bulkEditPlaceholder}
              bind:isMergeViewLoading
              bind:isMergeViewEnabled={showMergeView}
              bind:newModifiedContent={diffBulkText}
            />
          {/if}
        </div>
        <!-- Bulk Edit TextArea end -->
      </div>
    </section>
  {/if}
</div>

<style>
  .pair-header-row {
    /* border-top: 0.5px solid var(--border-secondary-315); */
    padding-top: 3px;
    padding-bottom: 3px;
    background-color: var(--bg-ds-surface-400);
    height: 28px;
  }
  .header-text {
    color: var(--text-ds-neutral-200);
    font-family: "Inter", sans-serif;
    font-weight: 500;
    font-size: 12px;
  }

  .merge-view-label {
    font-size: 12px;
    color: var(--text-ds-neutral-200);
    font-weight: 400;
    display: flex;
    align-items: center;
  }

  :global(.diff-row.diff-added) {
    background-color: #113b21 !important ;
  }

  :global(.diff-row.diff-deleted) {
    background-color: #3d1514 !important;
  }

  :global(.diff-row.diff-modified) {
    background-color: #113b21 !important ;
    /* background-color: rgba(246, 184, 59, 0.288) !important; */
  }
</style>
