<script lang="ts">
  import type {
    KeyValuePair,
    KeyValuePairWithBase,
  } from "@sparrow/common/interfaces/request.interface";
  import { TabularInputTheme } from "../../utils";
  import { CodeMirrorInput } from "../";
  import { onMount } from "svelte";
  import { Tooltip } from "@sparrow/library/ui";
  import { Switch } from "@sparrow/library/forms";
  import { ErrorInfoIcon, Information } from "@sparrow/library/icons";
  import BulkEditEditor from "./sub-component/BulkEditEditor.svelte";
  import LazyElement from "./LazyElement.svelte";

  // exports
  export let keyValue: KeyValuePair[] | KeyValuePairWithBase[];
  export let callback: (pairs: KeyValuePair[]) => void;
  export let readable: { key: string; value: string } = {
    key: "",
    value: "",
  };
  export let environmentVariables;
  export let onUpdateEnvironment;
  export let onToggleBulkEdit;
  export let isBulkEditActive = false;
  export let isBulkEditRequired = false;
  export let isBulkEditHeaderInfoRequired = false;
  export let isCheckBoxEditable = true;
  export let isTopHeaderRequired = true;
  export let isInputBoxEditable = true;
  export let bulkEditPlaceholder = "";
  // export let type: "file" | "text" = "text";

  let enableKeyValueHighlighting = true;
  let pairs: KeyValuePair[] = keyValue;
  let controller: boolean = false;

  let bulkText = "";
  let bulkToggle = isBulkEditActive;

  let isErrorIconHovered = false;
  let isAutoGeneratedInfoHovered = false;

  let isValidSyntax = true;

  const theme = new TabularInputTheme().build();

  $: {
    if (keyValue) {
      identifySelectAllState();
    }
  }

  /**
   * @description - calculates the select all checkbox state - weather checked or not
   */
  const identifySelectAllState = () => {
    pairs = [];
    pairs = keyValue;
    controller = false;
    if (pairs.length > 1) {
      let isUncheckedExist: boolean = false;
      for (let i = 0; i < pairs.length - 1; i++) {
        if (pairs[i].checked === false) {
          isUncheckedExist = true;
          break;
        }
      }
      if (isUncheckedExist) {
        controller = false;
      } else {
        controller = true;
      }
    }
  };

  const updateParam = (index: number): void => {
    pairs = pairs;
    if (
      pairs.length - 1 === index &&
      // although in readonly mode input is disabled
      // but codemirror internally invokes this function and updates key value
      // so one more extra check here for read only mode
      isInputBoxEditable &&
      (pairs[index].key !== "" || pairs[index].value !== "")
    ) {
      pairs[pairs.length - 1].checked = true;
      pairs.push({ key: "", value: "", checked: false });
      pairs = pairs;
    }
    callback(pairs);
  };

  const deleteParam = (index: number): void => {
    if (pairs.length > 1) {
      let filteredKeyValue = pairs.filter((elem, i) => {
        if (i !== index) {
          return true;
        }
        return false;
      });
      pairs = filteredKeyValue;
    }
    callback(pairs);
    setTimeout(() => {
      pairs[pairs.length - 1].key = "";
      pairs[pairs.length - 1].value = "";
    }, 0);
  };

  const updateCheck = (index: number): void => {
    let filteredKeyValue = pairs.map((elem, i) => {
      if (i === index) {
        elem.checked = !elem.checked;
      }
      return elem;
    });
    pairs = filteredKeyValue;
    callback(pairs);
  };

  // const extractFileName = (url) => {
  //   const parts = url.split("\\");
  //   const fileName = parts[parts.length - 1];
  //   return fileName;
  // };

  // const uploadFormFile = async (index) => {
  //   const filePathResponse = await invoke("fetch_file_command");
  //   if (filePathResponse !== "Canceled") {
  //     const filename = extractFileName(filePathResponse);
  //     const updatedFilePath = filePathResponse;
  //     let filteredPair = pairs.map((elem, i) => {
  //       if (i == index) {
  //         elem.value = filename;
  //         elem.base = updatedFilePath;
  //       }
  //       return elem;
  //     });
  //     pairs = filteredPair;
  //     callback(pairs);
  //     updateParam(index);
  //   }
  // };

  // const removeFormFile = (index) => {
  //   let filteredPair = pairs.map((elem, i) => {
  //     if (i == index) {
  //       elem.value = "";
  //       elem.base = "";
  //     }
  //     return elem;
  //   });
  //   pairs = filteredPair;
  //   callback(pairs);
  // };

  const handleCheckAll = (): void => {
    let flag: boolean;
    if (controller === true) {
      flag = false;
    } else {
      flag = true;
    }
    let filteredKeyValue = pairs.map((elem, i) => {
      if (i !== pairs.length - 1) {
        elem.checked = flag;
      } else if (!isInputBoxEditable) {
        elem.checked = flag;
      }
      return elem;
    });
    pairs = filteredKeyValue;
    callback(pairs);
  };

  let isBulkEditLoaded = false;

  /**
   * Updates the bulk text based on the key-value pairs.
   */
  const handleBulkTextUpdate = () => {
    // Define the syntax validation regex pattern (key:value)
    const syntaxPattern = /^[^:]+:.+$/;

    // Map each pair to a formatted line (key:value), validate syntax, and filter out invalid lines
    const res = pairs
      .map((elem) => {
        // Create a line from key and value, or empty string if both are empty
        const line = elem.key || elem.value ? `${elem.key}:${elem.value}` : "";

        // Validate syntax for each non-empty line
        if (line && !syntaxPattern.test(line)) {
          isValidSyntax = false;
        }

        return line;
      })
      .filter((item) => item) // Filter out empty lines
      .join("\n"); // Join lines with newline characters

    // Update the bulkText with the formatted and validated text
    bulkText = res;
    isBulkEditLoaded = true;
  };

  const handleBulkTextarea = (event) => {
    bulkText = event.detail;

    // remove all empty lines
    const res = bulkText.split("\n").filter((line) => line.trim() !== "");

    // Pushing a blank string to add a blank key value at the end
    res.push("");

    // Define the syntax validation regex pattern (key:value)
    const syntaxPattern = /^[^:]+:.+$/;

    // Initialize isValidSyntax to true
    isValidSyntax = true;

    pairs = res.map((elem) => {
      if (elem.length) {
        const firstColonIndex = elem.indexOf(":");
        let key, value;

        if (firstColonIndex !== -1) {
          key = elem.substring(0, firstColonIndex).trim();
          value = elem.substring(firstColonIndex + 1).trim();
        } else {
          key = elem.trim();
          value = "";
        }

        // Validate syntax for each non-empty line
        if (elem && !syntaxPattern.test(elem)) {
          isValidSyntax = false;
        }

        return {
          key: key,
          value: value,
          checked: true,
        };
      } else {
        return {
          key: "",
          value: "",
          checked: false,
        };
      }
    });
    callback(pairs);
  };

  const handleErrorHover = () => {
    isErrorIconHovered = !isErrorIconHovered;
  };

  const handleAutoGeneratedInfoHover = () => {
    isAutoGeneratedInfoHovered = !isAutoGeneratedInfoHovered;
  };

  const toggleBulkEdit = (event) => {
    onToggleBulkEdit(event.target.checked);
  };

  onMount(() => {
    handleBulkTextUpdate();
  });
</script>

<div class="outer-section">
  {#if !isBulkEditActive}
    <div
      class="mb-0 me-0 w-100 bg-secondary-700 ps-3 py-0 border-radius-2 section-layout"
    >
      <div
        class="d-flex gap-3 py-1 mb-1 align-items-center w-100 ps-2 {!isTopHeaderRequired
          ? 'd-none'
          : ''}"
        style="height:26px;"
      >
        <div style="width:30px;">
          <!-- <input
      class="form-check-input"
      type="checkbox"
      bind:checked={controller}
      on:input={handleCheckAll}
    /> -->
          <label class="container">
            <input
              type="checkbox"
              disabled={pairs.length === 1 || !isCheckBoxEditable}
              bind:checked={controller}
              on:input={handleCheckAll}
            />
            <span class="checkmark"></span>
          </label>
        </div>
        <div
          class="d-flex pair-title bg-secondary-700 align-items-center w-100"
          style="font-size: 12px; font-weight: 500;"
        >
          <p
            class="mb-0 w-50 text-secondary-200 text-fs-12 p-1 ps-1"
            style="font-weight: 1000;"
          >
            Key
          </p>
          <p
            class="mb-0 w-50 text-secondary-200 text-fs-12 p-1 ps-0 ms-3"
            style="font-weight: 1000;"
          >
            Value
          </p>

          {#if isBulkEditRequired}
            <div class="me-3">
              <button class="bg-transparent border-0 mt-1 d-flex" style="">
                <p
                  class="text-nowrap text-primary-300 mb-0 me-0"
                  style="font-size: 10px; font-weight:400;"
                >
                  Bulk Edit
                </p>

                <Switch
                  bind:checked={bulkToggle}
                  onClick={handleBulkTextUpdate}
                  onChange={toggleBulkEdit}
                />
              </button>
            </div>
          {/if}

          {#if !isBulkEditRequired}
            <div class="h-75 pe-1">
              <button class=" border-0" style="width:70px;" />
            </div>
          {/if}
        </div>
      </div>
      <div
        class="w-100"
        style="display:block; position:relative;
    width:200px;
    "
      >
        {#if readable.key || readable.value}
          <div
            aria-label="Toggle Hover"
            class="sortable > div"
            style=" width:100%;"
          >
            <div
              style="padding-top: 1px; background-color:backgroundColor;display: flex;flex-direction: column;width:100%;"
            >
              <div
                class="d-flex w-100 align-items-center justify-content-center gap-3"
                style="padding-top:3px; padding-bottom:3px; height:24px;"
              >
                <div style="width:30px;">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    disabled
                    checked={true}
                  />
                </div>

                <div class="d-flex gap-0" style="width:calc(100% - 120px)">
                  <div class="w-50 position-relative">
                    <input
                      type="text"
                      placeholder=""
                      class=" keyValuePair ps-1 py-1 w-100"
                      style="font-size: 12px;"
                      disabled
                      bind:value={readable.key}
                    />
                  </div>
                  <div class="w-50 position-relative">
                    <input
                      type="text"
                      placeholder=""
                      class=" keyValuePair ps-1 py-1 w-100"
                      style="font-size: 12px;"
                      disabled
                      bind:value={readable.value}
                    />
                  </div>
                </div>
                <div class="h-75 pe-1">
                  <button class=" border-0" style="width:40px;" />
                </div>
              </div>
            </div>
          </div>
        {/if}
        {#each pairs as element, index (index)}
          <LazyElement
            {element}
            {index}
            {pairs}
            {theme}
            {environmentVariables}
            {onUpdateEnvironment}
            {updateParam}
            {updateCheck}
            {deleteParam}
            {isInputBoxEditable}
            {isCheckBoxEditable}
          />
        {/each}
      </div>
    </div>
  {:else}
    <!-- Bulk Edit section Start -->
    <div>
      <div class="d-flex flex-column" style="height: 234px; font-size:12px;">
        <div
          class="d-flex align-items-center"
          style="justify-content: space-between;"
        >
          <!-- Bulk Edit Text  -->
          <div class="d-flex align-items-center">
            <div
              class="ps-1 me-1"
              style="font-size:12px; font-weight:500; color:var(--sparrow-text-color);"
            >
              Bulk Edit
            </div>
            <div>
              {#if isBulkEditHeaderInfoRequired}
                <div
                  class="d-flex align-items-center rounded-1 justify-content-center position-relative"
                  style="height: 18px; width:18px; "
                >
                  <div
                    on:mouseenter={handleAutoGeneratedInfoHover}
                    on:mouseleave={handleAutoGeneratedInfoHover}
                    style="cursor: pointer; margin-bottom:2px"
                  >
                    <Information
                      height={"12px"}
                      width={"12px"}
                      color={"var(--bg-secondary-950)"}
                    />
                  </div>

                  {#if isAutoGeneratedInfoHovered}
                    <div
                      class="d-flex align-items-center justify-content-center ps-3 pe-3 position-absolute text-fs-12 bg-tertiary-650 border-radius-5"
                      style="top:105px; right: -380px; width: 373px; height: 106px; transform: translateY(-100%); z-index:1;"
                    >
                      <div>
                        <div
                          class="pb-1 d-flex align-items-center justify-content-start"
                        >
                          <span>
                            <Information
                              height={"12px"}
                              width={"12px"}
                              color={"var(--white-color)"}
                            /></span
                          >
                          <span class="ps-2 text-fs-16 text-colorWhite fw-bold"
                            >Auto-Generated Headers</span
                          >
                        </div>
                        <p
                          class="mb-0 mt-1"
                          style="text-align: start; font-weight:400;"
                        >
                          Auto-generated headers cannot be updated in Bulk Edit
                          mode. In order to manage auto-generated headers,
                          switch back to the Key-Value edit view.
                        </p>
                      </div>
                    </div>
                  {/if}
                </div>
              {/if}
            </div>
          </div>

          <!-- Bulk Edit Button -->
          {#if bulkEditPlaceholder}
            <div class="pe-0 d-flex align-items-center gap-1 bulkEdit-btn-div">
              {#if !isValidSyntax}
                <div
                  class="d-flex align-items-center justify-content-center position-relative border-radius-3 me-1"
                  style="height: 18px; width:18px; z-index:1; "
                >
                  <div
                    on:mouseenter={handleErrorHover}
                    on:mouseleave={handleErrorHover}
                    style="cursor: pointer;"
                  >
                    <ErrorInfoIcon
                      height={"12px"}
                      width={"12px"}
                      color={"var(--dangerColor)"}
                    />
                  </div>

                  {#if isErrorIconHovered}
                    <div
                      class="d-flex align-items-center justify-content-center ps-3 pe-3 position-absolute text-fs-12 bg-tertiary-650 border-radius-5"
                      style="top:105px; right: 25px; width: 290px; height: 106px; transform: translateY(-100%);"
                    >
                      <div>
                        <div
                          class="pb-1 d-flex align-items-center justify-content-start"
                        >
                          <span>
                            <ErrorInfoIcon
                              height={"12px"}
                              width={"12px"}
                              color={"var(--dangerColor)"}
                            /></span
                          >
                          <span class="ps-2 text-fs-16 text-colorWhite fw-bold"
                            >Syntax Error</span
                          >
                        </div>
                        <p class="mb-0 mt-1" style="text-align: start;">
                          Please verify the syntax for keys and values, and
                          ensure you follow the correct format when adding them.
                          For example: userId:12345.
                        </p>
                      </div>
                    </div>
                  {/if}
                </div>
              {/if}

              <button class="bg-transparent border-0 mt-2 d-flex">
                <p
                  class="text-nowrap text-primary-300 mb-2"
                  style="font-size: 10px; font-weight:400;"
                >
                  Bulk Edit
                </p>

                <Switch
                  bind:checked={bulkToggle}
                  onChange={toggleBulkEdit}
                  onClick={handleBulkTextUpdate}
                />
              </button>
            </div>
          {/if}
        </div>

        <!-- Bulk Edit TextArea starts -->
        <div style="height:100%">
          {#if isBulkEditLoaded}
            <BulkEditEditor
              bind:value={bulkText}
              on:change={handleBulkTextarea}
              {enableKeyValueHighlighting}
              class={`px-2 sparrow-fs-18 outline-none`}
              placeholder={bulkEditPlaceholder}
            />
          {/if}
        </div>
        <!-- Bulk Edit TextArea end -->
      </div>
    </div>
  {/if}
</div>

<style>
  .bulkEdit-btn-div {
    margin-right: 16px;
  }

  .keyValuePair {
    background-color: transparent;
    border-radius: 0;
    border: 1px solid transparent;
  }
  .pair-container:nth-child(odd) {
    margin-top: -1px;
  }
  .section-layout {
    border-top: 1px solid var(--border-secondary-500);
    border-bottom: 1px solid var(--border-secondary-500);
  }

  /* The container */
  .container {
    display: block;
    position: relative;
    padding-left: 35px;
    margin-bottom: 12px;
    cursor: pointer;
    font-size: 22px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  /* Hide the browser's default checkbox */
  .container input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
    height: 0;
    width: 0;
    background-color: transparent;
    border: 2px solid var(--text-secondary-500);
  }

  /* Create a custom checkbox */
  .checkmark {
    position: absolute;
    top: 0;
    left: 0;
    height: 14px;
    width: 14px;
    border-radius: 3px;
    background-color: transparent;
    border: 2px solid var(--text-secondary-500);
  }

  /* On mouse-over, add a grey background color */
  /* .container:hover input ~ .checkmark {
    background-color: #ccc;
  } */

  /* When the checkbox is checked, add a blue background */
  .container input:checked ~ .checkmark {
    border: none;
    background-color: var(--bg-primary-300);
  }

  /* Create the checkmark/indicator (hidden when not checked) */
  .checkmark:after {
    content: "";
    position: absolute;
    display: none;
  }

  /* Show the checkmark when checked */
  .container input:checked ~ .checkmark:after {
    display: block;
  }

  /* Style the checkmark/indicator */
  .container .checkmark:after {
    left: 5px;
    top: 2px;
    width: 4px;
    height: 8px;
    border: solid var(--text-secondary-800);
    border-width: 0 2px 2px 0;
    -webkit-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    transform: rotate(45deg);
  }
</style>
