<script lang="ts">
  import { Loader } from "@sparrow/library/ui";
  import { Modal } from "@sparrow/library/ui";
  import { Splitpanes, Pane } from "svelte-splitpanes";

  import type { Observable } from "rxjs";
  import { SaveAsCollectionItem } from "@sparrow/workspaces/features";

  import type {
    CreateCollectionType,
    CreateFolderType,
    ReadWorkspaceType,
    SaveAsRequestType,
    SaveRequestType,
    UpdateAutoGeneratedHeadersType,
    UpdateHeadersType,
    UpdateParamsType,
    UpdateRequestUrlType,
  } from "@sparrow/workspaces/type";
  import { type Tab } from "@sparrow/common/types/workspace/tab";
  import { TabTypeEnum } from "@sparrow/common/types/workspace/tab";

  import {
    HttpUrlSection,
    ResponseDefaultScreen,
    ResponsePreview,
    ResponsePreviewNavigator,
    RequestHeaders,
    RequestMessage,
    RequestNavigator,
    RequestParameters,
    ResponseData,
    RequestEvents,
  } from "../components";
  import { writable } from "svelte/store";
  import { SocketSectionEnum } from "@sparrow/common/types/workspace/socket-io-request-tab";
  import { loadingState } from "../../../../../@sparrow-common/src/store";

  export let tab: Observable<Tab>;
  export let collections: Observable<any[]>;
  export let onUpdateRequestUrl: UpdateRequestUrlType;
  export let onUpdateRequestEventName;
  export let onUpdateRequestParams: UpdateParamsType;
  export let onUpdateMessage;
  export let onUpdateHeaders: UpdateHeadersType;
  export let onUpdateAutoGeneratedHeaders: UpdateAutoGeneratedHeadersType;
  export let onUpdateRequestState;
  export let onSaveSocket: SaveRequestType;
  export let readWorkspace: ReadWorkspaceType;
  export let onSaveAsSocket: SaveAsRequestType;
  export let onCreateFolder: CreateFolderType;
  export let onCreateCollection: CreateCollectionType;
  export let onUpdateEnvironment;
  export let environmentVariables;
  export let isGuestUser = false;
  export let onUpdateEvents;
  const loading = writable<boolean>(false);
  /**
   * Role of user in active workspace
   */
  export let userRole: string;
  export let onRenameCollection;
  export let onRenameFolder;
  export let onConnect;
  export let onSendMessage;
  export let socketIoStoreData;
  export let onDisconnect;
  export let onSearchMessage;
  export let onDeleteMessage;
  export let onUpdateMessageBody;
  export let onUpdateContentType;
  export let onClearInput;
  export let onUpdateFilterType;
  export let isWebApp;

  let isExposeSaveAsSocket = false;
  const toggleSaveRequest = (flag: boolean): void => {
    isExposeSaveAsSocket = flag;
  };

  loadingState.subscribe((tab) => {
    const tabIdValue = tab.get($tab.tabId);
    if (tabIdValue === undefined) {
      loading.set(false);
    } else {
      loading.set(tabIdValue);
    }
  });
</script>

{#if $tab.tabId}
  <div class="d-flex rest-explorer-layout h-100">
    <div class="w-100 d-flex flex-column h-100 p-3">
      <!-- HTTP URL Section -->
      <HttpUrlSection
        isSaveLoad={$loading}
        class=""
        isSave={$tab.isSaved}
        bind:userRole
        requestUrl={$tab.property.socketio?.url}
        {onUpdateEnvironment}
        {environmentVariables}
        {onUpdateRequestUrl}
        {toggleSaveRequest}
        {onSaveSocket}
        {isGuestUser}
        {onConnect}
        webSocket={socketIoStoreData}
        {onDisconnect}
      />

      <div style="padding-top:12px"></div>
      <div style="flex:1; overflow:auto;">
        <!-- {#if !isLoading} -->
        <Splitpanes
          class="socketio-splitter w-100 h-100"
          id={"socketio-splitter"}
          horizontal={false}
          dblClickSplitter={false}
          on:resize={(e) => {
            onUpdateRequestState({
              leftSplitterWidthPercentage: e.detail[0].size,
            });
            onUpdateRequestState({
              rightSplitterWidthPercentage: e.detail[1].size,
            });
          }}
        >
          <Pane
            minSize={30}
            size={$tab.property.socketio?.state?.leftSplitterWidthPercentage}
            class="position-relative bg-transparent"
          >
            <!-- Request Pane -->
            <div class="h-100 d-flex flex-column position-relative pe-2">
              <RequestNavigator
                requestStateSection={$tab.property.socketio?.state
                  ?.requestNavigation}
                {onUpdateRequestState}
                paramsLength={$tab.property?.socketio?.queryParams?.length || 0}
                headersLength={$tab.property?.socketio?.headers?.length || 0}
                eventsLength={$tab.property?.socketio?.events?.length || 0}
                autoGeneratedHeadersLength={isWebApp
                  ? 0
                  : $tab.property?.socketio?.autoGeneratedHeaders?.length || 0}
              />
              <div style="flex:1; overflow:auto;margin-top:12px" class="p-0">
                {#if $tab.property.socketio?.state?.requestNavigation === SocketSectionEnum.MESSAGE}
                  <RequestMessage
                    body={$tab?.property?.socketio?.message}
                    requestState={$tab?.property?.socketio?.state}
                    {onUpdateMessage}
                    {onUpdateRequestState}
                    {onSendMessage}
                    {onClearInput}
                    webSocket={socketIoStoreData}
                    {onUpdateRequestEventName}
                    requestEventName={$tab.property.socketio?.eventName}
                  />
                {:else if $tab.property.socketio?.state?.requestNavigation === SocketSectionEnum.PARAMETERS}
                  <RequestParameters
                    isBulkEditActive={$tab?.property?.socketio.state
                      ?.isParameterBulkEditActive}
                    {onUpdateRequestState}
                    params={$tab.property.socketio.queryParams}
                    {onUpdateRequestParams}
                    {onUpdateEnvironment}
                    {environmentVariables}
                  />
                {:else if $tab.property.socketio?.state?.requestNavigation === SocketSectionEnum.HEADERS}
                  <RequestHeaders
                    isBulkEditActive={$tab?.property?.socketio.state
                      ?.isHeaderBulkEditActive}
                    {onUpdateRequestState}
                    {environmentVariables}
                    {onUpdateEnvironment}
                    headers={$tab.property.socketio.headers}
                    autoGeneratedHeaders={$tab.property.socketio
                      .autoGeneratedHeaders}
                    onHeadersChange={onUpdateHeaders}
                    onAutoGeneratedHeadersChange={onUpdateAutoGeneratedHeaders}
                    {isWebApp}
                  />
                {:else if $tab.property.socketio?.state?.requestNavigation === SocketSectionEnum.EVENTS}
                  <RequestEvents
                    callback={(pairs) => {
                      onUpdateEvents(pairs);
                    }}
                    keyValue={$tab.property.socketio.events}
                  />
                {/if}
              </div>
            </div>
          </Pane>
          <Pane
            minSize={30}
            size={$tab.property.socketio?.state?.rightSplitterWidthPercentage}
            class="bg-transparent position-relative"
          >
            <!-- Response Pane -->
            <div class="d-flex flex-column h-100 ps-2" style="overflow:auto;">
              <div class="h-100 d-flex flex-column">
                <div style="flex:1; overflow:auto;">
                  {#if !socketIoStoreData}
                    <ResponseDefaultScreen />
                  {:else}
                    <div class="h-100 flex-column">
                      <div style="overflow:auto; height:50%;">
                        <ResponseData
                          webSocket={socketIoStoreData}
                          {onSearchMessage}
                          {onDeleteMessage}
                          {onUpdateMessageBody}
                          {onUpdateContentType}
                          {onUpdateFilterType}
                        />
                      </div>
                      <div style="overflow:auto; height:50%;">
                        <div
                          class="h-100 d-flex flex-column"
                          style="border-top: 1px solid var(--border-ds-surface-100);padding-top: 8px;"
                        >
                          <ResponsePreviewNavigator
                            webSocket={socketIoStoreData}
                            {onUpdateContentType}
                            {isWebApp}
                          />
                          <div class="pt-2"></div>
                          <div
                            style="flex:1; overflow:auto;border: 1px solid var(--border-ds-surface-100);border-radius:2px;"
                          >
                            <ResponsePreview webSocket={socketIoStoreData} />
                          </div>
                        </div>
                      </div>
                    </div>
                  {/if}
                </div>
              </div>
            </div></Pane
          >
        </Splitpanes>
        <!-- {:else}
          <ResponseDefaultScreen isMainScreen={true} />
        {/if} -->
      </div>
    </div>
  </div>
  <Modal
    title={"Save Request"}
    type={"dark"}
    width={"55%"}
    zIndex={10000}
    isOpen={isExposeSaveAsSocket}
    handleModalState={(flag = false) => {
      isExposeSaveAsSocket = flag;
    }}
  >
    <SaveAsCollectionItem
      onClick={(flag = false) => {
        isExposeSaveAsSocket = flag;
      }}
      requestMethod={TabTypeEnum.SOCKET_IO}
      requestUrl={$tab.property.socketio?.url}
      requestName={$tab.name}
      requestDescription={$tab.description}
      requestPath={$tab.path}
      collections={$collections}
      {readWorkspace}
      onSave={onSaveAsSocket}
      {onCreateFolder}
      {onCreateCollection}
      {onRenameCollection}
      {onRenameFolder}
    />
  </Modal>
{/if}

<style>
  .rest-explorer-layout {
    background-color: var(--bg-ds-surface-900);
  }

  :global(.socketio-splitter.splitpanes--vertical > .splitpanes__splitter) {
    width: 11px !important;
    height: 100% !important;
    background-color: var(--bg-ds-surface-100) !important;
    border-left: 5px solid var(--border-ds-surface-900) !important;
    border-right: 5px solid var(--border-ds-surface-900) !important;
    border-top: 0 !important;
    border-bottom: 0 !important;
  }
  :global(.socketio-splitter.splitpanes--horizontal > .splitpanes__splitter) {
    height: 11px !important;
    width: 100% !important;
    background-color: var(--bg-secondary-500) !important;
    border-top: 5px solid var(--border-ds-surface-900) !important;
    border-bottom: 5px solid var(--border-ds-surface-900) !important;
    border-left: 0 !important;
    border-right: 0 !important;
  }
  :global(
    .socketio-splitter > .splitpanes__splitter:active,
    .socketio-splitter > .splitpanes__splitter:hover
  ) {
    background-color: var(--bg-primary-200) !important;
  }
</style>
