<script lang="ts">
  import { type UpdateRequestStateType } from "@sparrow/workspaces/type";
  import { RequestSectionEnum } from "@sparrow/common/types/workspace";
  import { Label } from "@sparrow/library/ui";
  export let requestStateSection: string;
  export let authParameterLength = 0;
  export let authHeaderLength = 0;
  export let paramsLength = 0;
  export let headersLength = 0;
  export let autoGeneratedHeadersLength = 0;
  export let onUpdateRequestState: UpdateRequestStateType;

  let tabs: {
    name: string;
    id: RequestSectionEnum;
    count: number;
  }[] = [];

  /**
   * @description - refresh tabs label count
   * @param _paramsLength - query parameter length
   * @param _authParameterLength - auth parameter length
   * @param _headersLength - headers length
   * @param _autoGeneratedHeadersLength - auto generated headers length
   * @param _authHeaderLength - auth headers length
   */
  const refreshTabs = (
    _paramsLength: number,
    _authParameterLength: number,
    _headersLength: number,
    _autoGeneratedHeadersLength: number,
    _authHeaderLength: number,
  ) => {
    return [
      {
        name: "Parameters",
        id: RequestSectionEnum.PARAMETERS,
        count: _paramsLength + _authParameterLength - 1,
      },
      { name: "Body", id: RequestSectionEnum.REQUEST_BODY, count: 0 },
      {
        name: "Headers",
        id: RequestSectionEnum.HEADERS,
        count:
          _headersLength + _autoGeneratedHeadersLength + _authHeaderLength - 1,
      },
      { name: "Auth", id: RequestSectionEnum.AUTHORIZATION, count: 0 },
      { name: "Doc", id: RequestSectionEnum.DOCUMENTATION, count: 0 },
    ];
  };

  /**
   * @description - re-calculates value when dependency changes
   */
  $: {
    if (
      authParameterLength ||
      authHeaderLength ||
      paramsLength ||
      headersLength ||
      autoGeneratedHeadersLength
    ) {
      tabs = refreshTabs(
        paramsLength,
        authParameterLength,
        headersLength,
        autoGeneratedHeadersLength,
        authHeaderLength,
      );
    }
  }

  /**
   * @description - handles different key press
   * @param event - keyboard events
   */
  const handleKeyPress = (event: KeyboardEvent) => {
    if (event.altKey && event.code === "KeyP") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.PARAMETERS,
      });
    } else if (event.altKey && event.code === "KeyH") {
      onUpdateRequestState({ requestNavigation: RequestSectionEnum.HEADERS });
    } else if (event.altKey && event.code === "KeyB") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.REQUEST_BODY,
      });
    } else if (event.altKey && event.code === "KeyA") {
      onUpdateRequestState({
        requestNavigation: RequestSectionEnum.AUTHORIZATION,
      });
    }
  };
</script>

<div class="pb-2">
  <!-- Tabs -->
  <div class="d-flex mb-2">
    {#each tabs as tab}
      <button
        class="navigation__link border-0 sparrow-fs-12 request-tab me-3 {tab.id ===
        requestStateSection
          ? 'tab-active'
          : ''}"
        role="tab"
        on:click={() => {
          onUpdateRequestState({ requestNavigation: tab.id });
        }}
      >
        <span class="d-flex align-items-center ps-1 pe-1"
          ><span>{tab.name}</span>
          {#if tab.count}
            <span class="ms-1"></span>
            <Label number={tab.count} />
          {/if}
        </span>
      </button>
    {/each}
  </div>
</div>
<svelte:window on:keydown={handleKeyPress} />

<style>
  .navigation__link {
    color: var(--text-secondary-100);
    background-color: transparent;
    border-bottom: 2px transparent;
  }

  .navigation__link:hover {
    background-color: var(--text-secondary-500);
    border-radius: 2px;
  }
  .tab-active {
    color: var(--text-secondary-100);
    border-bottom: 2px solid var(--border-primary-300) !important;
  }
</style>
