#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Sync version across all files
# yarn sync-version

# Add updated files to git
git add package.json apps/*/package.json packages/*/package.json apps/@sparrow-desktop/src-tauri/tauri.conf.json

pnpm npx lint-staged