name: Build & Release Snap

on:
  push:
    branches:
      - build-snap

jobs:
  build-snap:
    runs-on: ubuntu-latest

    env:
      SNAP_CHANNEL: ${{ secrets.SNAP_RELEASE_CHANNEL || 'edge' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Snapcraft Login
        run: |
          echo "${{ secrets.SNAPCRAFT_PASSWORD }}" | snapcraft login --with -
        env:
          SNAPCRAFT_STORE_CREDENTIALS: '{"email": "${{ secrets.SNAPCRAFT_EMAIL }}", "password": "${{ secrets.SNAPCRAFT_PASSWORD }}"}'

      - name: Set up Sparrow APT Repo
        run: |
          mkdir -p "$HOME/.apt-keyrings"
          curl -fsSL https://sparrow-assest.s3.us-east-1.amazonaws.com/linux/sparrow-repo-key.gpg -o $HOME/.apt-keyrings/sparrow.asc
          
          echo "deb [signed-by=$HOME/.apt-keyrings/sparrow.asc] https://sparrow-assest.s3.us-east-1.amazonaws.com/linux stable main" | sudo tee /etc/apt/sources.list.d/sparrow.list

          sudo apt-get update

      - name: Download Latest Sparrow DEB
        run: |
          mkdir -p deb-download
          cd deb-download
          apt download sparrow

      - name: Build Snap from DEB
        run: |
          snapcraft --destructive-mode

      - name: Upload Snap to Snap Store
        run: |
          SNAP_FILE=$(ls *.snap | head -n 1)
          echo "Uploading $SNAP_FILE to $SNAP_CHANNEL"
          snapcraft upload "$SNAP_FILE" --release="$SNAP_CHANNEL"
