name: Development Snap

on:
  push:
    branches:
      - build-snap

jobs:
  build-snap:
    runs-on: ubuntu-latest

    env:
      SNAP_CHANNEL: ${{ secrets.SNAP_RELEASE_CHANNEL || 'edge' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Snapcraft
        run: |
          sudo snap install snapcraft --classic

      - name: Set Snapcraft Credentials from Base64
        run: |
          echo "${{ secrets.SNAPCRAFT_STORE_CREDENTIALS_B64 }}" | base64 --decode > snaplogin
          export SNAPCRAFT_STORE_CREDENTIALS="$(cat snaplogin)"
          snapcraft whoami || echo "Logged in successfully"
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ""


      - name: Set up Sparrow APT Repo
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://sparrow-assest.s3.us-east-1.amazonaws.com/linux/sparrow-repo-key.gpg | sudo tee /etc/apt/keyrings/sparrow.asc > /dev/null
          echo "deb [signed-by=/etc/apt/keyrings/sparrow.asc] https://sparrow-assest.s3.us-east-1.amazonaws.com/linux stable main" | sudo tee /etc/apt/sources.list.d/sparrow.list
          sudo apt-get update


      - name: Download Latest Sparrow DEB
        run: |
          apt download sparrow

      - name: Build Snap from DEB
        run: |
          sudo snapcraft --destructive-mode

      - name: Upload Snap to Snap Store
        run: |
          SNAP_FILE=$(ls *.snap | head -n 1)
          echo "Uploading $SNAP_FILE to $SNAP_CHANNEL"
          snapcraft upload "$SNAP_FILE" --release="$SNAP_CHANNEL"
