name: Build and Push Multi-Arch Sparrow Web Self Host Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to build"
        required: true
        default: main
        type: string
      image_version:
        description: "Docker image version (e.g. 1.2.3)"
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    env:
      DOCKER_IMAGE_VERSION: ${{ inputs.image_version }}
      BUILD_BRANCH: ${{ inputs.branch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BUILD_BRANCH }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        run: |
          set -euo pipefail
          docker buildx build --platform linux/amd64,linux/arm64 \
          -f SelfHost-Sparrow-Web.Dockerfile \
          -t sparrowapi/sparrow-web:${DOCKER_IMAGE_VERSION} \
          -t sparrowapi/sparrow-web:latest \
          --push .

      - name: Logout from Docker Hub
        run: |
          docker logout