name: storyook-design-system-dev
on:
  push:
    branches:
      - design-system

jobs:
   build:
      runs-on: ubuntu-latest
      environment: sparrow_storybook_Dev
      steps:
         - uses: actions/checkout@master

         - uses: Azure/docker-login@v1
           with:
              login-server: sparrowprod.azurecr.io
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

         - run: |
              docker build -f ./Storybook.Dockerfile -t sparrowprod.azurecr.io/storybook-design-system:${{ github.run_number }} .
              docker push sparrowprod.azurecr.io/storybook-design-system:${{ github.run_number }}

   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master
         - uses: richardrigutins/replace-in-files@v1
           with:
              files: "./apps/@sparrow-storybook/deploymentManifests/deployment-design-system.yml"
              search-text: '_BUILD__ID_'
              replacement-text: '${{ github.run_number }}'

         - uses: azure/setup-kubectl@v2.0

         - uses: Azure/k8s-set-context@v2
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              namespace: sparrow-dev
              manifests: |
                 ./apps/@sparrow-storybook/deploymentManifests/deployment-design-system.yml